import {Link} from 'react-router-dom';
import {ArrowRight,FileText,Table2,CheckCircle2,ScanLine} from 'lucide-react';
import {MarketingHeader,MarketingFooter} from '../marketing/MarketingShell';
import {useSession} from '../../lib/session';
import '../marketing/marketing.css';
import './bank-statements.css';

export default function BankLanding(){
  const session=useSession();
  const start=session.data?'/app/bank-statements':'/sign-up?next=%2Fapp%2Fbank-statements';
  return <div className="marketing-page bank-landing"><a className="marketing-skip-link" href="#main-content">Skip to content</a><MarketingHeader startTo={start} startLabel="Convert a statement" signInTo="/sign-in?next=%2Fapp%2Fbank-statements"/><main id="main-content">
    <section className="marketing-container bank-hero"><div><p className="bank-eyebrow">MaintainFlow · Bank statement converter</p><h1>Your statements.<br/><span>Ready for a spreadsheet.</span></h1><p className="bank-hero-description">Turn bank statements into a transaction table. Check the details beside the original, resolve flagged amounts, then download CSV or Excel.</p><Link className="button primary marketing-cta" to={start}>Convert a statement<ArrowRight size={18}/></Link><p className="small muted">Your review comes before every export.</p></div>
      <div className="bank-sample" aria-label="Illustrative statement conversion"><div className="bank-sample-title"><FileText size={22}/><span>Monthly statement</span><span className="bank-label">Illustration</span></div><div className="bank-sample-lines"><span/><span/><span/></div><div className="bank-sample-arrow"><ArrowRight size={24}/><span>Review transactions</span></div><div className="bank-sample-table"><div><strong>Date</strong><strong>Description</strong><strong>Debit</strong></div><div><span>04 Sep</span><span>Office supplies</span><span>42.50</span></div><div><span>07 Sep</span><span>Internet service</span><span>65.00</span></div><div><span>12 Sep</span><span>Travel</span><span>18.20</span></div></div><p><CheckCircle2 size={16}/>Approve the values you have checked.</p></div>
    </section>
    <section className="marketing-container bank-public-steps" aria-label="How bank statement conversion works">{[{Icon:FileText,title:'1. Add your statements',text:'Upload up to 20 files at a time. Choose how dates and decimal separators are written.'},{Icon:ScanLine,title:'2. Check every account',text:'Review transactions beside the original. Correct, add or exclude rows, with source evidence kept visible.'},{Icon:Table2,title:'3. Download approved data',text:'Export the approved revision as CSV or Excel. Select several approved statements for one download.'}].map(({Icon,title,text})=><div key={title}><Icon size={28} strokeWidth={1.5}/><h2>{title}</h2><p>{text}</p></div>)}</section>
    <section className="marketing-container bank-public-details"><div><h2>Clear checks.<br/>You make the final call.</h2><p>Keep accounts and currencies separate. Missing values, possible duplicates and balance discrepancies are flagged for review. Enter amounts exactly as written; MaintainFlow does not invent missing transactions.</p></div><div><h3>Before you upload</h3><ul><li>Each file can be up to 10 MB and 30 pages. Very dense statements can exceed extraction limits. Each account supports up to 1,000 extracted transaction rows; split larger statements into smaller files.</li><li>PDF, PNG, JPEG, TIFF, text, CSV, XLSX, DOCX, HTML and EML are supported source formats.</li><li>Scans and images need the configured extraction provider. Document content is sent to that provider when AI extraction is used.</li><li>Extraction can miss or misread details. Review the original before approving; support for every bank or layout is not guaranteed.</li></ul><Link className="link" to="/privacy">Read the privacy information</Link></div></section>
    <section className="marketing-container bank-public-cta"><h2>Less copying. More checking.</h2><Link className="button primary marketing-cta" to={start}>Start with your statement<ArrowRight size={18}/></Link></section>
  </main><MarketingFooter/></div>;
}
