import {useEffect,useMemo,useRef,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {ArrowLeft,ArrowUp,ArrowDown,Plus,Eye,CheckCircle2,Download,RotateCw,AlertCircle,Pencil,History} from 'lucide-react';
import type {BankAccount,BankTransaction,BankValues,BankSource,BankIssue} from '../../../shared/bank-statements';
import type {Evidence} from '../../../shared/types';
import {useSession} from '../../lib/session';
import {post,useAction,useData} from '../../lib/api';
import {Button,Field,Notice,Loading,ErrorState,Status,Tabs,Modal,dateTime} from '../../components/ui';
import DocumentPreview from '../documents/DocumentPreview';
import {bankLocales,exportBankStatements,rawSourceAt,type BankDocument,type BankRun,type BankLocale} from './bank-ui';
import BankExtractionStatus,{type BankExtractionJob} from './BankExtractionStatus';
import '../documents/review.css';
import './bank-statements.css';

type Detail={document:BankDocument;parser:{id:string;useCase?:string};runs:BankRun[];jobs:BankExtractionJob[];lifecycle?:unknown[]};
const metadata=[['bank_name','Bank name'],['account_identifier','Account identifier'],['currency','Currency'],['statement_start','Statement start'],['statement_end','Statement end'],['opening_balance','Opening balance'],['closing_balance','Closing balance'],['total_debits','Total debits'],['total_credits','Total credits']] as const;
const transactionFields=[['date','Date'],['description','Description'],['reference','Reference'],['debit','Debit'],['credit','Credit'],['balance','Balance'],['currency','Currency']] as const;
const moneyFields=new Set(['opening_balance','closing_balance','total_debits','total_credits','debit','credit','balance']);
const moneyHint='Use a decimal point with no thousands separators or currency symbols, e.g. 1234.56. Leave unknown amounts blank.';
const emptyRow=():BankTransaction=>({id:crypto.randomUUID(),origin:'user',excluded:false,exclusion_reason:null,date:null,description:null,reference:null,debit:null,credit:null,balance:null,currency:null});
const emptyAccount=():BankAccount=>({id:crypto.randomUUID(),origin:'user',excluded:false,exclusion_reason:null,bank_name:null,account_identifier:null,currency:null,statement_start:null,statement_end:null,opening_balance:null,closing_balance:null,total_debits:null,total_credits:null,balance_convention:'unknown',transactions:[]});
const titleFor=(account:BankAccount,index:number)=>`${account.bank_name||`Account ${index+1}`}${account.account_identifier?` · ${account.account_identifier}`:''}${account.currency?` · ${account.currency}`:''}${account.excluded?' · Excluded':''}`;
const scalar=(value:string|null)=>value??'—';

export default function BankReview(){
  const {id}=useParams();return <BankReviewScreen key={id} id={id!}/>;
}
function BankReviewScreen({id}:{id:string}){
  const query=useData<Detail>(`/api/bank-statements/${id}`,2500),session=useSession().data,action=useAction();
  const [selectedRun,setSelectedRun]=useState(''),[page,setPage]=useState(1),[evidence,setEvidence]=useState<Evidence|null>(null),[mobileTab,setMobileTab]=useState('Transactions');
  const [reviewState,setReviewState]=useState({dirty:false,busy:false}),[pendingRun,setPendingRun]=useState(''),[extractOpen,setExtractOpen]=useState(false),[extractLocale,setExtractLocale]=useState<BankLocale|''>('');
  const [sourceRequest,setSourceRequest]=useState(0);
  const reviewRoot=useRef<HTMLDivElement>(null),runSelect=useRef<HTMLSelectElement>(null),extractButton=useRef<HTMLButtonElement>(null);
  const firstRunId=query.data?.runs[0]?.id;
  // Pin the first loaded run so background extraction cannot replace a review draft.
  useEffect(()=>{if(!selectedRun&&firstRunId)setSelectedRun(firstRunId);},[selectedRun,firstRunId]);
  // Run after the selected page/mobile tab commits, including repeated links to the same page.
  useEffect(()=>{if(!sourceRequest)return;const preview=reviewRoot.current?.querySelector<HTMLElement>('.document-preview');preview?.scrollIntoView({block:'start'});preview?.focus({preventScroll:true});},[sourceRequest]);
  const canEdit=Boolean(session&&['owner','admin','editor'].includes(session.workspace.role));
  if(query.isPending)return <Loading/>;
  if(query.error)return <ErrorState error={query.error} retry={()=>void query.refetch()}/>;
  const {document:doc,runs,jobs}=query.data,run=runs.find(item=>item.id===selectedRun)||(!selectedRun?runs[0]:undefined);
  function switchRun(next:string){if(next===run?.id)return;if(reviewState.dirty){setPendingRun(next);return;}setSelectedRun(next);setEvidence(null);}
  const onSource=(item:Evidence)=>{setEvidence(item);setPage(Math.max(1,Math.min(doc.pageCount,item.page)));if(window.matchMedia('(max-width:1000px)').matches)setMobileTab('Original');setSourceRequest(value=>value+1);};
  return <div ref={reviewRoot} className="bank-review"><div className="bank-review-heading"><Link className="link bank-back" to="/app/bank-statements"><ArrowLeft size={17}/>Bank statements</Link><div className="bank-review-title"><div><h1>{doc.name}</h1><p>Check the original, review each account, then approve a spreadsheet.</p></div><Status value={doc.status}/></div><div className="bank-review-tools">{runs.length>1&&<Field label="Extraction run"><select name="bank-extraction-run" aria-label="Extraction run" ref={runSelect} value={run?.id||''} disabled={reviewState.busy} onChange={event=>switchRun(event.target.value)}>{runs.map((item,index)=><option key={item.id} value={item.id}>Run {runs.length-index}{doc.approvedRunId===item.id?' · Approved':''}</option>)}</select></Field>}<Button variant="secondary" disabled={!canEdit||action.busy||reviewState.busy||jobs.some(job=>['queued','processing'].includes(job.state))} onClick={event=>{extractButton.current=event.currentTarget;setExtractLocale('');setExtractOpen(true);}}><RotateCw/>Extract again</Button><span className="small muted">Extracting again uses this statement’s page count.</span></div><Notice error={action.error} message={action.message}/><BankExtractionStatus documentStatus={doc.status} documentError={doc.error} latestJob={jobs[0]} hasRun={Boolean(run)} canEdit={canEdit}/>{run&&runs[0]?.id!==run.id&&<div className="bank-callout" role="status"><strong>A newer extraction is available.</strong><p>You are still reviewing your selected run. Unsaved changes stay here until you choose another run.</p><Button variant="secondary" disabled={reviewState.busy} onClick={()=>switchRun(runs[0].id)}>Review newest extraction</Button></div>}</div>
    <div className="bank-mobile-tabs"><Tabs items={['Transactions','Original']} value={mobileTab} onChange={setMobileTab} label="Statement view"/></div>
    <div className={`bank-review-grid bank-show-${mobileTab.toLowerCase()}`}><DocumentPreview key={doc.id} document={doc} page={page} setPage={value=>{setPage(value);setEvidence(null);}} evidence={evidence}/>
      {run?<BankReviewPane key={`${doc.id}:${run.id}:${session?.user.id}:${session?.workspace.id}`} doc={doc} run={run} canEdit={canEdit} onSource={onSource} onReviewStateChange={setReviewState}/>:<section className="bank-review-pane bank-processing"><RotateCw size={30}/><h2>No transactions to review yet.</h2><p>You can return to your statements and come back when the extraction is ready.</p><Link className="button secondary" to="/app/bank-statements">Back to statements</Link></section>}
    </div>
    <Modal title="Change extraction run?" description="Your unsaved corrections belong to the current run." open={Boolean(pendingRun)} onOpenChange={open=>{if(!open)setPendingRun('');}} onCloseAutoFocus={event=>{event.preventDefault();runSelect.current?.focus({preventScroll:true});}}><p>Changing runs discards this draft. Stay here to save your corrections first.</p><div className="actions"><Button variant="secondary" onClick={()=>setPendingRun('')}>Keep editing</Button><Button onClick={()=>{setSelectedRun(pendingRun);setPendingRun('');setEvidence(null);}}>Discard draft & change run</Button></div></Modal>
    <Modal title="Extract this statement again?" description="Create a new extraction from the same original file." open={extractOpen} onOpenChange={setExtractOpen} onCloseAutoFocus={event=>{event.preventDefault();extractButton.current?.focus({preventScroll:true});}}><p>This uses {doc.pageCount} page{doc.pageCount===1?'':'s'} from your allowance. Existing approvals and your selected review stay available.</p><Field label="Date and number format for the new extraction" hint="Keep the current statement setting unless you need to correct how its dates or amounts were read."><select name="bank-reprocess-locale" aria-label="Date and number format for the new extraction" value={extractLocale} disabled={action.busy} onChange={event=>setExtractLocale(event.target.value as BankLocale|'')}><option value="">Keep current format{runs[0]?.bankContext?.locale?` (${runs[0].bankContext.locale})`:''}</option>{bankLocales.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Notice error={action.error}/><div className="actions"><Button variant="secondary" disabled={action.busy} onClick={()=>setExtractOpen(false)}>Cancel</Button><Button disabled={action.busy} onClick={()=>void action.run(async()=>{await post(`/api/documents/${doc.id}/reprocess`,extractLocale?{bankLocale:extractLocale}:{});setExtractOpen(false);},'Extraction queued. Existing approvals remain available.')}>{action.busy?'Queueing…':'Start new extraction'}</Button></div></Modal>
  </div>;
}

function BankReviewPane({doc,run,canEdit,onSource,onReviewStateChange}:{doc:BankDocument;run:BankRun;canEdit:boolean;onSource:(value:Evidence)=>void;onReviewStateChange:(state:{dirty:boolean;busy:boolean})=>void}){
  const initial=run.bankValues||run.effectiveValues;
  const [values,setValues]=useState<BankValues>(initial),[baseline,setBaseline]=useState({values:initial,revision:run.effectiveRevision}),[accountId,setAccountId]=useState(initial.accounts[0]?.id||''),[tab,setTab]=useState('Transactions'),[acknowledged,setAcknowledged]=useState(''),[editingRow,setEditingRow]=useState<string|null>(null),[sourceId,setSourceId]=useState<string|null>(null),[chosenApproval,setChosenApproval]=useState(''),[rowPage,setRowPage]=useState(1),[issueLimit,setIssueLimit]=useState(30);
  const action=useAction(),mounted=useRef(true),observedRevision=useRef(run.effectiveRevision),returnFocus=useRef<HTMLElement|null>(null),focusSourceOnClose=useRef(false);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
  const dirty=JSON.stringify(values)!==JSON.stringify(baseline.values),stale=baseline.revision!==run.effectiveRevision;
  useEffect(()=>{onReviewStateChange({dirty,busy:action.busy});},[dirty,action.busy,onReviewStateChange]);
  useEffect(()=>{if(observedRevision.current===run.effectiveRevision)return;observedRevision.current=run.effectiveRevision;if(!dirty){setValues(run.bankValues||run.effectiveValues);setBaseline({values:run.bankValues||run.effectiveValues,revision:run.effectiveRevision});setAcknowledged('');}},[run.effectiveRevision,run.bankValues,run.effectiveValues,dirty]);
  const account=values.accounts.find(item=>item.id===accountId)||values.accounts[0],accountIndex=values.accounts.findIndex(item=>item.id===account?.id),row=account?.transactions.find(item=>item.id===editingRow);
  const issues=run.bankIssues||[],errors=issues.filter(issue=>issue.severity==='error'),warnings=issues.filter(issue=>issue.severity==='warning');
  const ackKey=`${run.effectiveRevision}:${run.bankReviewToken}`,approval=run.approvals.find(item=>item.id===chosenApproval)||run.approvals[0];
  const source=sourceId?(run.bankContext?.transactions[sourceId]||run.bankContext?.accounts[sourceId]):undefined;
  function change(next:BankValues){setValues(next);setAcknowledged('');}
  function updateAccount(patch:Partial<BankAccount>){if(account)change({...values,accounts:values.accounts.map(item=>item.id===account.id?{...item,...patch}:item)});}
  function openRow(id:string,trigger:HTMLElement){returnFocus.current=trigger;setEditingRow(id);}
  function updateRow(id:string,patch:Partial<BankTransaction>){if(account)updateAccount({transactions:account.transactions.map(item=>item.id===id?{...item,...patch}:item)});}
  function moveRow(index:number,delta:number){if(!account)return;const transactions=account.transactions.slice();[transactions[index],transactions[index+delta]]=[transactions[index+delta],transactions[index]];updateAccount({transactions});}
  function accept(saved:BankRun){if(!mounted.current)return;const next=saved.bankValues||saved.effectiveValues;setValues(next);setBaseline({values:next,revision:saved.effectiveRevision});setAcknowledged('');}
  const blocked=!canEdit||action.busy||stale;
  const issuesByTransaction=useMemo(()=>{const result=new Map<string,BankIssue[]>();for(const issue of run.bankIssues||[]){if(!issue.transactionId)continue;const entries=result.get(issue.transactionId)||[];entries.push(issue);result.set(issue.transactionId,entries);}return result;},[run.bankIssues]);
  const activeRowIssue=(transactionId:string)=>issuesByTransaction.get(transactionId)||[];
  const rowPages=Math.max(1,Math.ceil((account?.transactions.length||0)/50)),visibleRowPage=Math.min(rowPage,rowPages);
  const visibleRows=account?.transactions.slice((visibleRowPage-1)*50,visibleRowPage*50)||[];
  function showIssue(issue:BankIssue,trigger:HTMLElement){if(issue.accountId)setAccountId(issue.accountId);setRowPage(1);if(issue.transactionId){setSourceId(issue.transactionId);openRow(issue.transactionId,trigger);}setTab('Transactions');}
  return <section className="bank-review-pane" aria-label="Bank statement transactions"><Tabs items={['Transactions','Approvals & history']} value={tab} onChange={setTab} label="Bank statement sections"/><div className="bank-pane-content"><Notice error={action.error} message={action.message}/>
    {stale&&<div className="bank-callout" role="status"><strong>A newer correction was saved.</strong><p>{dirty?'Your draft is preserved. Load the latest values before saving or approving.':'Load the latest values to continue.'}</p><Button variant="secondary" onClick={()=>accept(run)}>{dirty?'Discard draft & load latest':'Load latest values'}</Button></div>}
    {tab==='Transactions'?<><div className="bank-checks" aria-label="Statement validation"><div className="bank-section-heading"><h2>Review checks</h2><span>{errors.length} errors · {warnings.length} warnings</span></div>{issues.length?<ul>{issues.slice(0,issueLimit).map((issue,index)=><li className={`bank-issue ${issue.severity}`} key={`${issue.code}:${issue.accountId}:${issue.transactionId}:${index}`}><AlertCircle size={16}/><div><strong>{issue.severity==='error'?'Needs correction':'Review warning'}</strong><p>{issue.message}</p>{issue.relatedDocumentIds?.length?<p>{issue.relatedDocumentIds.map(id=><Link key={id} className="link" to={`/app/bank-statements/${id}`}>Open related statement</Link>)}</p>:null}</div>{(issue.accountId||issue.transactionId)&&<button className="link" type="button" onClick={event=>showIssue(issue,event.currentTarget)}>View</button>}</li>)}</ul>:<p className="small muted">No automatic issues found in the saved result. Check it against the original before approving.</p>}{issues.length>issueLimit&&<Button variant="ghost" onClick={()=>setIssueLimit(value=>value+30)}>Show more checks ({issues.length-issueLimit} remaining)</Button>}{dirty&&<p className="bank-check-stale" role="status">Your changes are not checked yet. Save corrections to refresh these checks.</p>}</div>
      <div className="bank-account-picker"><Field label="Account and currency"><select name="bank-account" aria-label="Account and currency" value={account?.id||''} onChange={event=>{setAccountId(event.target.value);setRowPage(1);setEditingRow(null);setSourceId(null);}}>{values.accounts.map((item,index)=><option key={item.id} value={item.id}>{titleFor(item,index)}</option>)}</select></Field><Button variant="ghost" disabled={blocked||values.accounts.length>=100} onClick={()=>{const added=emptyAccount();change({...values,accounts:[...values.accounts,added]});setAccountId(added.id);setRowPage(1);}}><Plus/>Add account</Button></div>
      {account?<><details className="bank-account-details"><summary>Statement details <span>{account.origin==='user'?'User-added account':`Account ${accountIndex+1}`}</span></summary><fieldset disabled={blocked} className="bank-metadata"><legend className="sr-only">Statement details</legend>{metadata.map(([key,label])=><Field key={key} label={label} hint={moneyFields.has(key)?moneyHint:undefined}><input name={`bank-account-${key}`} aria-label={label} type="text" maxLength={4000} inputMode={moneyFields.has(key)?'decimal':undefined} value={account[key]??''} placeholder={key.includes('statement_')?'YYYY-MM-DD':key==='currency'?'EUR, USD…':'Not found'} onChange={event=>updateAccount({[key]:event.target.value||null})}/></Field>)}<Field label="How does the balance change?" hint="Choose only what the statement supports. Leave unknown if it is unclear."><select name="bank-balance-convention" aria-label="How does the balance change?" value={account.balance_convention} onChange={event=>updateAccount({balance_convention:event.target.value as BankAccount['balance_convention']})}><option value="unknown">Unknown / needs review</option><option value="credit_increases">Credits increase the balance</option><option value="debit_increases">Debits increase the balance</option></select></Field></fieldset><div className="bank-account-actions"><label className="bank-check-label"><input name="bank-account-excluded" type="checkbox" disabled={blocked} checked={account.excluded} onChange={event=>updateAccount({excluded:event.target.checked})}/>Exclude this account from export</label><Button variant="ghost" onClick={()=>setSourceId(account.id)}><Eye/>Original details</Button></div>{account.excluded&&<Field label="Reason for excluding this account"><input name="bank-account-exclusion-reason" maxLength={4000} disabled={blocked} value={account.exclusion_reason||''} onChange={event=>updateAccount({exclusion_reason:event.target.value||null})} placeholder="Explain why this account should be left out"/></Field>}</details>
        <div className="bank-section-heading"><h2>Transactions <span>{account.transactions.length}</span></h2><div className="actions"><Button variant="secondary" disabled={blocked||account.excluded} onClick={event=>{returnFocus.current=event.currentTarget;const added=emptyRow();updateAccount({transactions:[...account.transactions,added]});setRowPage(Math.ceil((account.transactions.length+1)/50));setEditingRow(added.id);}}><Plus/>Add row</Button><Button variant="ghost" disabled={blocked||account.excluded||account.transactions.length<2} onClick={()=>updateAccount({transactions:[...account.transactions].reverse()})}>Reverse row order</Button></div></div><p className="small muted">Check the source order before reversing rows; save to run the balance checks again. Scroll the table sideways on smaller screens to see every column. Debit, credit and balance are kept as exact amounts. Excluded rows stay in the review history and are left out of exports.</p>
        {account.transactions.length?<div className="bank-table-scroll" tabIndex={0} role="region" aria-label="Transactions table, scroll horizontally for all columns"><table className="bank-transactions"><caption className="sr-only">Transactions for {titleFor(account,accountIndex)}</caption><thead><tr><th scope="col">Date</th><th scope="col">Description</th><th scope="col">Debit</th><th scope="col">Credit</th><th scope="col">Balance</th><th scope="col">Review</th></tr></thead><tbody>{visibleRows.map((item,visibleIndex)=>{const index=(visibleRowPage-1)*50+visibleIndex;return <tr key={item.id} className={item.excluded?'bank-row-excluded':''}><td>{scalar(item.date)}</td><td><strong>{scalar(item.description)}</strong>{item.reference&&<span>{item.reference}</span>}<div className="bank-row-labels">{item.origin==='user'&&<span className="bank-label">User-added</span>}{item.excluded&&<span className="bank-label">Excluded</span>}{item.currency&&item.currency!==account.currency&&<span className="bank-label">{item.currency}</span>}</div></td><td className="bank-money">{scalar(item.debit)}</td><td className="bank-money">{scalar(item.credit)}</td><td className="bank-money">{scalar(item.balance)}</td><td><div className="bank-row-actions"><button type="button" className="icon-button" aria-label={`Edit transaction ${index+1}`} disabled={blocked} onClick={event=>openRow(item.id,event.currentTarget)}><Pencil size={16}/></button><button type="button" className="icon-button" aria-label={`View source for transaction ${index+1}`} onClick={()=>setSourceId(item.id)}><Eye size={16}/></button><button type="button" className="icon-button" aria-label={`Move transaction ${index+1} up`} disabled={blocked||index===0} onClick={()=>moveRow(index,-1)}><ArrowUp size={15}/></button><button type="button" className="icon-button" aria-label={`Move transaction ${index+1} down`} disabled={blocked||index===account.transactions.length-1} onClick={()=>moveRow(index,1)}><ArrowDown size={15}/></button></div>{activeRowIssue(item.id).length>0&&<button type="button" className="bank-row-issue" onClick={event=>openRow(item.id,event.currentTarget)}><AlertCircle size={13}/>{activeRowIssue(item.id).length} checks</button>}</td></tr>;})}</tbody></table></div>:<div className="bank-empty"><p>No transactions were found for this account. Compare the original and add missing rows yourself.</p></div>}{rowPages>1&&<nav className="bank-pagination" aria-label="Transaction pages"><Button variant="secondary" disabled={visibleRowPage===1} onClick={()=>setRowPage(visibleRowPage-1)}>Previous</Button><span>Rows {(visibleRowPage-1)*50+1}–{Math.min(visibleRowPage*50,account.transactions.length)} of {account.transactions.length}</span><Button variant="secondary" disabled={visibleRowPage===rowPages} onClick={()=>setRowPage(visibleRowPage+1)}>Next</Button></nav>}
      </>:<div className="bank-empty"><h3>No accounts were found.</h3><p>Add an account using the original statement to start your review.</p></div>}
      {sourceId&&<SourcePanel key={sourceId} source={source} rawValues={run.rawValues} onSource={onSource} onClose={()=>setSourceId(null)}/>}
    </>:<><h2>Approved revisions</h2><p className="small muted">An approval is a saved snapshot. Exports below use that exact revision, including older approvals. Excel keeps unusually precise amounts as text to preserve every digit.</p>{run.approvals.length?<><Field label="Approval to export"><select name="bank-approval" aria-label="Approval to export" value={approval?.id||''} onChange={event=>setChosenApproval(event.target.value)}>{run.approvals.map((item,index)=><option key={item.id} value={item.id}>{dateTime(item.createdAt)}{index===0?' · Most recent':''}</option>)}</select></Field><div className="actions"><Button variant="secondary" disabled={action.busy||!approval} onClick={()=>void action.run(()=>exportBankStatements('csv',[{documentId:doc.id,approvalId:approval!.id}]),'Approved CSV downloaded.')}><Download/>Download CSV</Button><Button variant="secondary" disabled={action.busy||!approval} onClick={()=>void action.run(()=>exportBankStatements('xlsx',[{documentId:doc.id,approvalId:approval!.id}]),'Approved Excel file downloaded.')}>Download Excel</Button></div>{approval&&<details className="bank-history-values"><summary>View this approval’s saved values</summary><pre>{JSON.stringify(approval.values,null,2)}</pre></details>}</>:<p>No approved revision yet. Check the transactions, save corrections and approve the result first.</p>}<h2 className="bank-history-title">Correction history</h2><p className="small muted">Original extracted values and source evidence remain attached to this run.</p><ul className="bank-history">{run.corrections.map(item=><li key={item.id}><History size={17}/><div><strong>Correction saved</strong><p>{dateTime(item.createdAt)}</p><details className="bank-history-values"><summary>View saved values</summary><pre>{JSON.stringify(item.values,null,2)}</pre></details></div></li>)}</ul><p className="small muted">Extraction created {dateTime(run.createdAt)} · Regional setting: {run.bankContext?.locale||'Not recorded'}</p></>}
  </div>
    {tab==='Transactions'&&<footer className="bank-review-footer">{warnings.length>0&&<label className="bank-check-label"><input name="bank-warnings-acknowledged" type="checkbox" checked={acknowledged===ackKey} disabled={blocked||dirty} onChange={event=>setAcknowledged(event.target.checked?ackKey:'')}/>I have checked the {warnings.length} warning{warnings.length===1?'':'s'} against the original and accept the result.</label>}<p className="small muted">{dirty?'Unsaved changes. Save to refresh validation.':errors.length?'Correct the errors before approving.':'Review every transaction against the original before approving.'}</p><div className="actions"><Button variant="secondary" disabled={blocked||!dirty} onClick={()=>void action.run(async()=>{const saved=await post<{run:BankRun}>(`/api/runs/${run.id}/corrections`,{values,expectedRevision:baseline.revision});accept(saved.run);},'Corrections saved and checked.')} >Save corrections</Button><Button disabled={blocked||dirty||errors.length>0||warnings.length>0&&acknowledged!==ackKey||!run.bankReviewToken} onClick={()=>void action.run(async()=>{const result=await post<{run:BankRun;approval:{id:string}}>(`/api/runs/${run.id}/approve`,{expectedRevision:baseline.revision,bankReviewToken:run.bankReviewToken,acknowledgeBankWarnings:warnings.length>0&&acknowledged===ackKey});accept(result.run);setChosenApproval(result.approval.id);setTab('Approvals & history');},'Approved revision saved. Choose a download format.')}><CheckCircle2/>Approve statement</Button></div></footer>}
    <Modal title={row?`Transaction ${account!.transactions.findIndex(item=>item.id===row.id)+1}`:'Transaction'} description="Compare the source before changing a value. Amounts stay exact; leave an unknown value blank." open={Boolean(row)} onCloseAutoFocus={event=>{event.preventDefault();if(focusSourceOnClose.current){focusSourceOnClose.current=false;setTimeout(()=>document.querySelector<HTMLElement>('.bank-source-panel')?.focus({preventScroll:true}),0);}else if(returnFocus.current?.isConnected)returnFocus.current.focus({preventScroll:true});}} onOpenChange={open=>{if(!open)setEditingRow(null);}}>{row&&<><p className="small muted">{row.origin==='user'?'User-added transaction · no extraction evidence':'Extracted transaction · original evidence is preserved'}</p><fieldset disabled={blocked} className="bank-transaction-form"><legend className="sr-only">Transaction values</legend>{transactionFields.map(([key,label])=><Field key={key} label={label} hint={moneyFields.has(key)?moneyHint:undefined}>{key==='description'?<textarea name={`bank-transaction-${key}`} aria-label={label} rows={2} maxLength={4000} value={row[key]||''} onChange={event=>updateRow(row.id,{[key]:event.target.value||null})}/>:<input name={`bank-transaction-${key}`} aria-label={label} type="text" maxLength={4000} inputMode={moneyFields.has(key)?'decimal':undefined} placeholder={key==='date'?'YYYY-MM-DD':key==='currency'?'EUR, USD…':'Not found'} value={row[key]||''} onChange={event=>updateRow(row.id,{[key]:event.target.value||null})}/>}</Field>)}<label className="bank-check-label"><input name="bank-transaction-excluded" type="checkbox" checked={row.excluded} onChange={event=>updateRow(row.id,{excluded:event.target.checked})}/>Exclude this transaction from export</label>{row.excluded&&<Field label="Reason for excluding this transaction"><input name="bank-transaction-exclusion-reason" maxLength={4000} value={row.exclusion_reason||''} onChange={event=>updateRow(row.id,{exclusion_reason:event.target.value||null})} placeholder="For example, a repeated statement header"/></Field>}</fieldset>{activeRowIssue(row.id).map((issue,index)=><p key={index} className="bank-error-text">{issue.message}</p>)}<div className="actions"><Button type="button" variant="secondary" onClick={()=>{focusSourceOnClose.current=true;setSourceId(row.id);setEditingRow(null);}}>View original evidence</Button><Button type="button" onClick={()=>setEditingRow(null)}>Done</Button></div><p className="small muted">Changes remain a draft until you save corrections.</p></>}</Modal>
  </section>;
}

function SourcePanel({source,rawValues,onSource,onClose}:{source:BankSource|undefined;rawValues:unknown;onSource:(value:Evidence)=>void;onClose:()=>void}){
  const panel=useRef<HTMLElement>(null);
  useEffect(()=>{panel.current?.focus({preventScroll:true});panel.current?.scrollIntoView({block:'nearest'});},[]);
  const raw=source?rawSourceAt(rawValues,source.rawPath):undefined;
  const quotes=source?Object.entries(source.evidence).flatMap(([field,items])=>items.map(item=>({field,item}))):[];
  return <section ref={panel} tabIndex={-1} className="bank-source-panel" aria-label="Original extracted evidence"><div className="bank-section-heading"><h3>Original extracted evidence</h3><Button variant="ghost" onClick={onClose}>Close</Button></div>{source?<><p className="small muted">This evidence is linked to the original extraction ID, even after rows are moved or corrected.</p>{raw!==undefined&&<details open><summary>Original values</summary><pre>{JSON.stringify(raw,null,2)}</pre></details>}{quotes.length?<ul>{quotes.map(({field,item},index)=><li key={`${field}:${index}`}><button type="button" className="evidence-link" onClick={()=>onSource(item)}>Page {item.page}: {item.text}</button>{item.source==='model-visual'&&<span className="small muted">AI-read quote. Check it against the original.</span>}</li>)}</ul>:<p>No source quote was recorded for this item. Check the original manually.</p>}</>:<p>This is a user-added item. No extracted source or page evidence is claimed.</p>}</section>;
}
