import {fetchOriginalFile,workspaceId} from './api';
import {pdfSha256} from './pdf-split';
import {canonicalTemplateDefinition,type TemplateDefinition,type TemplateMutationResult} from '../../shared/template-definitions';
import {pdfGeometryVersion,pdfGeometrySchema,pdfRegionRuleSchema,type PdfGeometry} from '../../shared/pdf-regions';
import type {ExtractionResult} from '../../shared/types';
import type {TemplateCandidate,TemplateSelection} from '../../shared/template-selection';

export type NativeTemplateScope={userId:string;workspaceId:string;parserId:string};
export type NativeTemplateSource={documentId:string;sha256:string;mimeType:'application/pdf';pageCount:number;size:number;name:string};
export type NativeTemplateGeometry={source:NativeTemplateSource;schemaId:string;geometry:PdfGeometry};
export type NativeTemplatePreview={source:NativeTemplateSource;schemaId:string;definitionDigest:string;selection:TemplateSelection;candidates:TemplateCandidate[];availableSourceText:boolean;evaluatedWhileDisabled:boolean;result?:ExtractionResult};
export type PendingTemplateMutation=NativeTemplateScope&{version:1;requestId:string;operation:'create'|'update'|'delete';templateId:string|null;baseSchemaId:string|null;baseRevision:number|null;definitionDigest:string|null};
export class NativeTemplateError extends Error{constructor(message:string,public status:number){super(message);}}
const uuid=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i,sha=/^[a-f0-9]{64}$/;
const key=(scope:NativeTemplateScope)=>`folio.native-template-mutation.v1:${scope.userId}:${scope.workspaceId}:${scope.parserId}`;
const base=(scope:NativeTemplateScope)=>`/api/parsers/${scope.parserId}`;
export function readTemplateMutation(scope:NativeTemplateScope):PendingTemplateMutation|null{
 try{const value=JSON.parse(localStorage.getItem(key(scope))||'null');if(!value||value.version!==1||value.userId!==scope.userId||value.workspaceId!==scope.workspaceId||value.parserId!==scope.parserId||!uuid.test(value.requestId)||!['create','update','delete'].includes(value.operation)||value.templateId!==null&&!uuid.test(value.templateId)||value.baseSchemaId!==null&&!uuid.test(value.baseSchemaId)||value.baseRevision!==null&&(!Number.isSafeInteger(value.baseRevision)||value.baseRevision<1)||value.definitionDigest!==null&&!sha.test(value.definitionDigest)||value.operation==='create'&&(value.templateId!==null||value.baseRevision!==null)||value.operation!=='create'&&(!value.templateId||value.baseRevision===null)||value.operation!=='delete'&&(!value.baseSchemaId||!value.definitionDigest)||value.operation==='delete'&&(value.definitionDigest!==null||value.baseSchemaId!==null))return null;
  return{version:1,userId:scope.userId,workspaceId:scope.workspaceId,parserId:scope.parserId,requestId:value.requestId,operation:value.operation,templateId:value.templateId,baseSchemaId:value.baseSchemaId,baseRevision:value.baseRevision,definitionDigest:value.definitionDigest};
 }catch{return null;}
}
export function saveTemplateMutation(value:PendingTemplateMutation){
 const record:PendingTemplateMutation={version:1,userId:value.userId,workspaceId:value.workspaceId,parserId:value.parserId,requestId:value.requestId,operation:value.operation,templateId:value.templateId,baseSchemaId:value.baseSchemaId,baseRevision:value.baseRevision,definitionDigest:value.definitionDigest};
 const saved=readTemplateMutation(value);if(saved&&JSON.stringify(saved)!==JSON.stringify(record))throw new Error('A different template save is still unresolved. Check its result before starting another save.');
 try{localStorage.setItem(key(value),JSON.stringify(record));}catch{throw new Error('Save recovery information could not be stored. Enable browser storage before saving this template.');}
}
export function clearTemplateMutation(value:PendingTemplateMutation){const saved=readTemplateMutation(value);if(saved&&saved.requestId!==value.requestId)throw new Error('A newer template save is pending. Reopen it before continuing.');localStorage.removeItem(key(value));}
function current(scope:NativeTemplateScope,isCurrent:()=>boolean){let selected='';try{selected=workspaceId();}catch{/* Explicit request scope and actor lookup remain authoritative. */}if(!isCurrent()||selected&&selected!==scope.workspaceId)throw new Error('The source, account or workspace changed. Reopen the template editor to continue.');}
export async function nativeTemplateRequest<T>(scope:NativeTemplateScope,path:string,isCurrent:()=>boolean,signal:AbortSignal,options:RequestInit={}):Promise<T>{
 current(scope,isCurrent);const headers=new Headers(options.headers);headers.set('X-Workspace-Id',scope.workspaceId);if(options.body)headers.set('Content-Type','application/json');let response:Response;
 try{response=await fetch(path,{...options,headers,signal,credentials:'same-origin',cache:'no-store',redirect:'error',referrerPolicy:'no-referrer'});}catch(error){if(signal.aborted)throw error;throw new NativeTemplateError('The template request could not be confirmed. Check your connection and retry the saved request.',0);}
 current(scope,isCurrent);const value=await response.json().catch(()=>null);current(scope,isCurrent);if(!response.ok)throw new NativeTemplateError(response.status===401||response.status===403?'Your access changed. Reopen the template editor before continuing.':response.status===404?'The document, template or saved request is unavailable. Check its current state.':response.status===409?'The saved template or parser fields changed. Keep your draft and load the current version before saving again.':response.status===415?'Choose a PDF with searchable native text. Image-only documents and TIFFs cannot use native PDF regions.':response.status===413?'This PDF exceeds the supported region-preview limits. Choose a smaller sample.':response.status===429||response.status===503?'The preview service is busy. Try this request again shortly.':'The template could not be checked or saved. Check its fields, anchors and page regions.',response.status);return value as T;
}
export async function assertTemplateActor(scope:NativeTemplateScope,isCurrent:()=>boolean,signal:AbortSignal,write=true){const result=await nativeTemplateRequest<{user:{id:string};workspace:{id:string;role:string}}>(scope,'/api/auth/me',isCurrent,signal);if(result?.user?.id!==scope.userId||result?.workspace?.id!==scope.workspaceId||write&&!['owner','admin','editor'].includes(result.workspace.role))throw new Error('Your account or permissions changed. Reopen the template editor before continuing.');}
function checkSource(value:NativeTemplateGeometry|NativeTemplatePreview,source:Pick<NativeTemplateSource,'documentId'|'sha256'>,schemaId:string){if(value?.source?.documentId!==source.documentId||value.source.sha256!==source.sha256||value.source.mimeType!=='application/pdf'||value.schemaId!==schemaId||!Number.isSafeInteger(value.source.pageCount)||value.source.pageCount<1||value.source.pageCount>30||!Number.isSafeInteger(value.source.size)||value.source.size<1||value.source.size>10*1024*1024)throw new Error('The template preview does not match this document and saved fields. Reload the source before continuing.');}
export async function loadNativeTemplateSource(scope:NativeTemplateScope,source:Pick<NativeTemplateSource,'documentId'|'sha256'>,schemaId:string,isCurrent:()=>boolean,signal:AbortSignal){
 await assertTemplateActor(scope,isCurrent,signal,false);const result=await nativeTemplateRequest<NativeTemplateGeometry>(scope,`${base(scope)}/templates/geometry`,isCurrent,signal,{method:'POST',body:JSON.stringify({documentId:source.documentId,sourceSha256:source.sha256,baseSchemaId:schemaId})});checkSource(result,source,schemaId);
 if(!pdfGeometrySchema.safeParse(result.geometry).success||result.geometry?.version!==pdfGeometryVersion||result.geometry.sourceSha256!==source.sha256||result.geometry.pageCount!==result.source.pageCount||result.geometry.pages.length!==result.source.pageCount)throw new Error('The PDF geometry could not be verified. Reload the source.');
 let response:Response;try{response=await fetchOriginalFile(source.documentId,signal);}catch(error){if(signal.aborted)throw error;throw new Error('The original PDF could not be loaded. Check your connection and retry the sample.');}current(scope,isCurrent);if(!response.ok)throw new Error('The original PDF is unavailable. Choose a retained sample document.');const data=await response.arrayBuffer();current(scope,isCurrent);if(data.byteLength!==result.source.size||await pdfSha256(data)!==source.sha256)throw new Error('The original PDF does not match the region preview. Reload the source.');current(scope,isCurrent);await assertTemplateActor(scope,isCurrent,signal,false);return{...result,bytes:new Uint8Array(data)};
}
export function normalizedTemplateDefinition(definition:TemplateDefinition):TemplateDefinition{return JSON.parse(canonicalTemplateDefinition({...definition,name:definition.name.trim(),...(definition.kind==='native-pdf-region-v1'?{rules:definition.rules.map(rule=>pdfRegionRuleSchema.parse(rule))}:{})} as TemplateDefinition));}
export const nativeDefinitionDigest=(definition:TemplateDefinition)=>pdfSha256(new TextEncoder().encode(canonicalTemplateDefinition(normalizedTemplateDefinition(definition))).buffer);
export async function previewNativeTemplate(scope:NativeTemplateScope,source:NativeTemplateSource,schemaId:string,definition:TemplateDefinition,isCurrent:()=>boolean,signal:AbortSignal){await assertTemplateActor(scope,isCurrent,signal,false);const digest=await nativeDefinitionDigest(definition);current(scope,isCurrent);const value=await nativeTemplateRequest<NativeTemplatePreview>(scope,`${base(scope)}/templates/preview`,isCurrent,signal,{method:'POST',body:JSON.stringify({documentId:source.documentId,sourceSha256:source.sha256,baseSchemaId:schemaId,definition:normalizedTemplateDefinition(definition)})});checkSource(value,source,schemaId);if(value.definitionDigest!==digest)throw new Error('This draft changed while its preview was running. Check the current draft again.');return value;}
export async function confirmTemplateMutation(value:PendingTemplateMutation,result:TemplateMutationResult){
 const mutation=result?.mutation;if(!mutation||mutation.requestId!==value.requestId||!['accepted','closed'].includes(mutation.state)||typeof mutation.replayed!=='boolean'||typeof mutation.deleted!=='boolean')throw new Error('This response does not match the saved template request. Check it again.');
 if(mutation.currentRevision!==null&&(!Number.isSafeInteger(mutation.currentRevision)||mutation.currentRevision<1))throw new Error('The current template revision could not be verified.');
 if(mutation.state==='closed'){if(result.template!==null||mutation.operation!==null||mutation.templateId!==null||mutation.acceptedRevision!==null||mutation.currentRevision!==null||mutation.deleted)throw new Error('The closed template request could not be verified.');return result;}
 if(mutation.operation!==value.operation||value.templateId&&mutation.templateId!==value.templateId||!mutation.templateId||!uuid.test(mutation.templateId)||!Number.isSafeInteger(mutation.acceptedRevision)||mutation.acceptedRevision!<1)throw new Error('The saved template result could not be verified.');
 if(value.operation!=='delete'){if(!result.template||result.template.id!==mutation.templateId||result.template.revision!==mutation.acceptedRevision||await nativeDefinitionDigest(result.template)!==value.definitionDigest)throw new Error('The saved definition does not match this request. Check it again.');}else if(result.template!==null)throw new Error('The deleted template result could not be verified.');return result;
}
export async function findTemplateMutation(value:PendingTemplateMutation,isCurrent:()=>boolean,signal:AbortSignal){await assertTemplateActor(value,isCurrent,signal);try{const result=await nativeTemplateRequest<TemplateMutationResult>(value,`${base(value)}/template-mutations/requests/${value.requestId}`,isCurrent,signal);const confirmed=await confirmTemplateMutation(value,result);current(value,isCurrent);return confirmed;}catch(error){if(error instanceof NativeTemplateError&&error.status===404)return null;throw error;}}
export async function submitTemplateMutation(value:PendingTemplateMutation,definition:TemplateDefinition|null,isCurrent:()=>boolean,signal:AbortSignal){
 current(value,isCurrent);saveTemplateMutation(value);if(value.operation!=='delete'&&(!definition||await nativeDefinitionDigest(definition)!==value.definitionDigest))throw new Error('This draft does not match the saved request. Check or close that request before saving another draft.');current(value,isCurrent);const existing=await findTemplateMutation(value,isCurrent,signal);if(existing)return existing;await assertTemplateActor(value,isCurrent,signal);
 const path=value.operation==='create'?`${base(value)}/templates`:`/api/templates/${value.templateId}`;const body=value.operation==='delete'?{requestId:value.requestId,baseRevision:value.baseRevision}:{...normalizedTemplateDefinition(definition!),requestId:value.requestId,baseSchemaId:value.baseSchemaId,...(value.operation==='update'?{baseRevision:value.baseRevision}:{})};
 const result=await nativeTemplateRequest<TemplateMutationResult>(value,path,isCurrent,signal,{method:value.operation==='create'?'POST':value.operation==='update'?'PATCH':'DELETE',body:JSON.stringify(body)});const confirmed=await confirmTemplateMutation(value,result);current(value,isCurrent);return confirmed;
}
export async function closeTemplateMutation(value:PendingTemplateMutation,isCurrent:()=>boolean,signal:AbortSignal){await assertTemplateActor(value,isCurrent,signal);const result=await nativeTemplateRequest<TemplateMutationResult>(value,`${base(value)}/template-mutations/requests/${value.requestId}/close`,isCurrent,signal,{method:'POST',body:'{}'});const confirmed=await confirmTemplateMutation(value,result);current(value,isCurrent);return confirmed;}
