import {useLayoutEffect,useRef,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {useQueryClient} from '@tanstack/react-query';
import {Archive,Download,Trash2} from 'lucide-react';
import {Button,Modal,Notice} from '../../components/ui';
import {api,downloadFile} from '../../lib/api';
import type {ArchiveImportLineage} from '../../../shared/archive-import';
import './archive-import.css';
export default function ArchiveLineage({archive,documentId,parserId,canEdit}:{archive:ArchiveImportLineage;documentId:string;parserId:string;canEdit:boolean}){
  const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),running=useRef(false),mounted=useRef(true),navigate=useNavigate(),client=useQueryClient();
  useLayoutEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
  async function remove(){if(running.current||!canEdit)return;running.current=true;setBusy(true);setError('');try{await api(`/api/archive-imports/${archive.id}`,{method:'DELETE'});if(!mounted.current)return;void client.invalidateQueries();navigate(`/app/parsers/${parserId}`);}catch(cause){if(mounted.current)setError(cause instanceof Error?cause.message:'The import could not be deleted.');}finally{if(mounted.current){running.current=false;setBusy(false);}}}
  return <aside className="archive-import-lineage" aria-label="Original ZIP import"><div><strong><Archive size={15} aria-hidden="true"/> From {archive.sourceName||'an original ZIP'} · {archive.path}</strong><p className="small">Archive entry {archive.index} · {archive.childCount} imported documents · {archive.retainedDocuments} retained. Page numbers belong to this document.</p><p className="small">{archive.sourceAvailable?'The full original ZIP still contains all excluded, unsupported and metadata files, plus files from deleted documents. It remains while any imported document is retained.':'The full original ZIP is no longer available.'}</p></div><div className="actions">{archive.sourceAvailable&&<Button type="button" variant="ghost" onClick={()=>void downloadFile(`/api/documents/${documentId}/archive-original`,archive.sourceName||'original-archive.zip').catch(cause=>{if(mounted.current)setError(cause instanceof Error?cause.message:'The original ZIP could not be downloaded.');})}><Download/>Download original ZIP</Button>}{canEdit&&<Button type="button" variant="ghost" onClick={()=>{setError('');setOpen(true);}}><Trash2/>Delete whole import</Button>}</div>{!open&&<Notice error={error}/>}<Modal title="Delete this ZIP import?" description={`This deletes all ${archive.retainedDocuments} retained documents in this import, their results and saved exports. Their files and the full original ZIP are queued for deletion. This cannot be undone.`} open={open} onOpenChange={value=>{if(!running.current)setOpen(value);}}><Notice error={error}/><div className="actions"><Button type="button" variant="danger" disabled={busy} onClick={()=>void remove()}>{busy?'Deleting…':'Delete whole import'}</Button><Button type="button" variant="ghost" disabled={busy} onClick={()=>setOpen(false)}>Keep import</Button></div></Modal></aside>;
}
