import {useId} from 'react';
import {ArrowDown,ArrowUp,Plus,Trash2} from 'lucide-react';
import {Button} from '../../components/ui';
export type ExportColumn={source:string;label:string};
type Props={columns:ExportColumn[];onChange:(columns:ExportColumn[])=>void;suggestions:ExportColumn[];disabled:boolean};
export default function ColumnMappingEditor({columns,onChange,suggestions,disabled}:Props){
  const listId=useId();
  function update(index:number,patch:Partial<ExportColumn>){onChange(columns.map((column,i)=>i===index?{...column,...patch}:column));}
  function move(index:number,direction:number){const next=[...columns];[next[index],next[index+direction]]=[next[index+direction],next[index]];onChange(next);}
  return <fieldset className="export-column-editor" disabled={disabled}><legend>Export columns</legend><p className="small muted">Choose a source field and the heading to use in your spreadsheet. Rows export in this order.</p><datalist id={listId}>{suggestions.map(column=><option value={column.source} key={column.source}>{column.label}</option>)}</datalist><div className="export-column-rows">{columns.map((column,index)=><div className="export-column-row" key={index}><label>Source field<input required maxLength={120} list={listId} value={column.source} placeholder="supplier" aria-label={`Column ${index+1} source field`} onChange={event=>{const source=event.target.value;update(index,{source,...(!column.label?{label:suggestions.find(item=>item.source===source)?.label||''}:{})});}}/></label><label>Column heading<input required maxLength={120} value={column.label} placeholder="Supplier" aria-label={`Column ${index+1} heading`} onChange={event=>update(index,{label:event.target.value})}/></label><div className="export-column-actions"><button type="button" className="icon-button" disabled={disabled||index===0} aria-label={`Move column ${index+1} up`} onClick={()=>move(index,-1)}><ArrowUp size={15}/></button><button type="button" className="icon-button" disabled={disabled||index===columns.length-1} aria-label={`Move column ${index+1} down`} onClick={()=>move(index,1)}><ArrowDown size={15}/></button><button type="button" className="icon-button" disabled={disabled||columns.length===1} aria-label={`Remove column ${index+1}`} onClick={()=>onChange(columns.filter((_,i)=>i!==index))}><Trash2 size={15}/></button></div></div>)}</div><Button type="button" variant="ghost" disabled={disabled||columns.length>=100} onClick={()=>onChange([...columns,{source:'',label:''}])}><Plus size={16}/>Add column</Button><p className="small muted">Nested fields use dots, for example <code>customer.name</code>. Use <code>$item.description</code> with a repeated table. Metadata sources include <code>$filename</code> and <code>$documentId</code>.</p></fieldset>;
}
