import {useLayoutEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {useQueryClient} from '@tanstack/react-query';
import {ChevronLeft,ChevronRight,Scissors} from 'lucide-react';
import {Button,Field,Modal,Notice,Tabs} from '../../components/ui';
import {useSession} from '../../lib/session';
import {clearPendingPdfSplit,findPdfSplitReceipt,pdfSha256,readPendingPdfSplit,savePendingPdfSplit,saveMatchingPendingPdfSplit,uploadPdfSplit,prepareTiffSplitPreview,isTiffSplitSource,type TiffSplitPreviewBinding,type PendingPdfSplit} from '../../lib/pdf-split';
import {canonicalPdfSplitSpec,planPdfSplit,parsePdfRanges,pdfSplitLimits,findPdfMarkerRanges,type PdfSplitSpec,type PdfSplitReceipt,type StoredPdfSplitRejected} from '../../../shared/pdf-split';
import type {SourceFormat} from '../../../shared/source-formats';
import PdfCanvas from './PdfCanvas';
import TiffSplitPreview from './TiffSplitPreview';
import UndoPdfSplit from './UndoPdfSplit';
import SplitSuggestionPanel from './SplitSuggestionPanel';
import {getSplitSuggestion,readSplitSuggestionSource,createSuggestedSplit} from '../../lib/split-suggestions';
import type {SplitSuggestion} from '../../../shared/split-suggestions';
import {readStoredPdfSplit,saveStoredPdfSplit,clearStoredPdfSplit,readStoredPdfSource,findStoredPdfSplit,submitStoredPdfSplit,type StoredPendingPdfSplit,type StoredPdfSource} from '../../lib/stored-pdf-split';

export type SplitParser={id:string;name:string;archived:boolean;fieldSetupState?:string;allowedFormats?:SourceFormat[]|null};
const pageRange=(start:number,end:number)=>start===end?String(start):`${start}–${end}`;
const describe=(options:PdfSplitSpec)=>options.mode==='every'?`Every ${options.pagesPerDocument} page${options.pagesPerDocument===1?'':'s'}`:`${options.mode==='marker'?`Text marker “${options.marker}” · `:''}${options.ranges.map(range=>pageRange(range.start,range.end)).join(', ')}`;

export default function SplitPdf({parser,source,disabled=false,onComplete}:{parser:SplitParser;source?:StoredPdfSource;disabled?:boolean;onComplete?:()=>void}){
  const session=useSession(),workspace=session.data?.workspace.id||'';
  const [open,setOpen]=useState(false),[busy,setBusy]=useState(false);const running=useRef(false);
  const pending=source?readStoredPdfSplit({userId:session.data?.user.id||'',workspaceId:workspace,parserId:parser.id},source.id):readPendingPdfSplit(workspace,parser.id,session.data?.user.id);
  const sourceKind=source?.mimeType==='image/tiff'?'TIFF':'PDF',accepted=parser.allowedFormats;
  const eligible=!parser.archived&&parser.fieldSetupState==='ready'&&(accepted==null||(source?accepted.includes(sourceKind==='TIFF'?'tiff':'pdf'):accepted.includes('pdf')||accepted.includes('tiff')));
  if(!workspace||!session.data||session.data.workspace.role==='viewer')return null;
  const unavailable=parser.archived?'Restore this parser before starting a new split.':parser.fieldSetupState!=='ready'?'Finish parser field setup before splitting a document.':!eligible?`Enable ${source?sourceKind:'PDF or TIFF'} in accepted formats before splitting.`:'';
  return <div className={`pdf-split-entry${source?' pdf-stored-split-entry':''}`}><Button type="button" variant="secondary" disabled={disabled||busy||!eligible&&!pending} onClick={()=>setOpen(true)}><Scissors/>{pending?`Resume ${pending.sourceMimeType==='image/tiff'?'TIFF':'PDF'} split`:source?`Split this ${sourceKind}`:'Split a PDF or TIFF'}</Button>{unavailable&&<p className="small muted">{unavailable} <Link className="link" to={`/app/parsers/${parser.id}?tab=${parser.fieldSetupState!=='ready'?'setup':'settings'}`}>Open parser {parser.fieldSetupState!=='ready'?'setup':'settings'}</Link></p>}<Modal title={source?`Split this ${sourceKind}`:'Split a PDF or TIFF'} description={source?`Create new documents from ${source.name}. This source and its existing review history stay unchanged.`:`Create separate documents in ${parser.name} from selected pages of one PDF or TIFF.`} open={open} onOpenChange={value=>{if(!running.current)setOpen(value);}}><SplitPdfFlow key={`${session.data.user.id}:${workspace}:${parser.id}:${session.data.workspace.role}:${source?.id||'upload'}:${source?.sha256||''}:${source?.mimeType||'application/pdf'}`} parser={parser} source={source} userId={session.data.user.id} workspace={workspace} eligible={eligible} onBusy={value=>{running.current=value;setBusy(value);}} onClose={()=>setOpen(false)} onComplete={onComplete}/></Modal></div>;
}

function SplitPdfFlow({parser,source,userId,workspace,eligible,onBusy,onClose,onComplete}:{parser:SplitParser;source?:StoredPdfSource;userId:string;workspace:string;eligible:boolean;onBusy:(value:boolean)=>void;onClose:()=>void;onComplete?:()=>void}){
  const client=useQueryClient(),fileInput=useRef<HTMLInputElement>(null),errorView=useRef<HTMLDivElement>(null),operation=useRef(new AbortController()),running=useRef(false),selectionGeneration=useRef(0),mounted=useRef(true);
  const scope={userId,workspaceId:workspace,parserId:parser.id};
  const [pending,setPending]=useState<PendingPdfSplit|StoredPendingPdfSplit|null>(()=>source?readStoredPdfSplit(scope,source.id):readPendingPdfSplit(workspace,parser.id,userId));
  const [sourceMimeType,setSourceMimeType]=useState<'application/pdf'|'image/tiff'>(source?.mimeType||pending?.sourceMimeType||'application/pdf'),[previewBinding,setPreviewBinding]=useState<TiffSplitPreviewBinding|null>(null);const previewRequest=useRef<string>('');
  const isTiff=sourceMimeType==='image/tiff',kind=isTiff?'TIFF':'PDF',canSubmit=eligible&&(parser.allowedFormats==null||parser.allowedFormats.includes(isTiff?'tiff':'pdf'));
  const [file,setFile]=useState<File|null>(null),[bytes,setBytes]=useState<Uint8Array|null>(null),[sha256,setSha256]=useState(''),[pageCount,setPageCount]=useState(0),[page,setPage]=useState(1);
  const [renderedPage,setRenderedPage]=useState<number|null>(null);
  const [mode,setMode]=useState<'every'|'ranges'|'marker'>('every'),[every,setEvery]=useState('1'),[ranges,setRanges]=useState(''),[marker,setMarker]=useState(''),[nativePages,setNativePages]=useState<string[]|null>(null),[textError,setTextError]=useState(''),[tab,setTab]=useState('Ranges');
  const [busy,setBusy]=useState(false),[reading,setReading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[receipt,setReceipt]=useState<PdfSplitReceipt|null>(null),[rejected,setRejected]=useState<StoredPdfSplitRejected|null>(null),[confirmNew,setConfirmNew]=useState(false);
  const [appliedSuggestion,setAppliedSuggestion]=useState<SplitSuggestion|null>(null),[suggestionSource,setSuggestionSource]=useState<SplitSuggestion|null>(null),[manualChanged,setManualChanged]=useState(false),[selectionIntent,setSelectionIntent]=useState(false),[aiClosed,setAiClosed]=useState(false),[aiExpired,setAiExpired]=useState(false);
  const previewGeneration=selectionGeneration.current;
  const markerMode=(pending?.options.mode||mode)==='marker';
  const activeMarker=pending?.options.mode==='marker'?pending.options.marker:marker;
  let options:PdfSplitSpec|undefined,plan:ReturnType<typeof planPdfSplit>|undefined,markerPlan:ReturnType<typeof findPdfMarkerRanges>|undefined,planError='';
  try{
    if(isTiff&&markerMode)throw new Error('TIFF splitting supports a page count or custom page ranges. Text markers apply only to PDFs.');
    if(markerMode&&nativePages){
      if(!activeMarker.trim())throw new Error('Enter a text marker to find document boundaries.');
      markerPlan=findPdfMarkerRanges(activeMarker,nativePages);
      if(pending?.options.mode==='marker'&&JSON.stringify(markerPlan.ranges)!==JSON.stringify(pending.options.ranges))throw new Error('The detected boundaries do not match this saved request. Check its result before starting a new split.');
    }
    options=pending?.options||(mode==='every'?{mode:'every',pagesPerDocument:Number(every)}:mode==='ranges'?{mode:'ranges',ranges:parsePdfRanges(ranges)}:markerPlan?{mode:'marker',marker:markerPlan.marker,ranges:markerPlan.ranges}:undefined);
    if(pageCount&&options&&(!markerMode||markerPlan))plan=planPdfSplit(options,pageCount);
  }catch(cause){planError=cause instanceof Error?cause.message:'Check the selected page ranges.';}
  if(markerMode&&textError)planError=textError;
  const omitted:number[]=[];if(plan)for(let i=1;i<=pageCount;i++)if(!plan.ranges.some(range=>i>=range.start&&i<=range.end))omitted.push(i);
  const frozen=Boolean(pending),ready=Boolean((file||source)&&sha256&&plan&&!planError&&!reading&&renderedPage===page&&(!appliedSuggestion||!aiExpired&&!appliedSuggestion.creationClosed)&&!aiClosed);
  function changeMode(next:'every'|'ranges'|'marker'){if(next!=='ranges')setAppliedSuggestion(null);setManualChanged(true);setMode(next);}
  function adjustRanges(){if(markerPlan)setRanges(markerPlan.ranges.map(range=>range.start===range.end?String(range.start):`${range.start}-${range.end}`).join(', '));setMode('ranges');setManualChanged(true);setTab('Ranges');}
  function markBusy(value:boolean){running.current=value;setBusy(value);onBusy(value);}
  function persist(value:PendingPdfSplit|StoredPendingPdfSplit){if(source)saveStoredPdfSplit(value as StoredPendingPdfSplit);else savePendingPdfSplit(value);setPending(value);}
  const findReceipt=(value:PendingPdfSplit|StoredPendingPdfSplit)=>source?findStoredPdfSplit(value as StoredPendingPdfSplit,()=>mounted.current,operation.current.signal):findPdfSplitReceipt(value,()=>mounted.current);
  async function loadSource(){
    if(!source||!mounted.current)return;const generation=selectionGeneration.current;setReading(true);setError('');
    try{const data=await readStoredPdfSource(scope,source,()=>mounted.current&&generation===selectionGeneration.current,operation.current.signal);if(!mounted.current||generation!==selectionGeneration.current)return;if(pending&&(pending.sha256!==source.sha256||(pending.sourceMimeType||'application/pdf')!==(source.mimeType||'application/pdf')))throw new Error('This source does not match the saved split. Check its result before continuing.');setBytes(data);setSha256(source.sha256);}
    catch(cause){if(mounted.current&&generation===selectionGeneration.current){setReading(false);setError(cause instanceof Error?cause.message:'The source document could not be loaded.');}}
  }
  function restoreSuggestion(value:SplitSuggestion,data:Awaited<ReturnType<typeof readSplitSuggestionSource>>,preserveSelection=false){
    if(!mounted.current||pending&&!pending.suggestionId||value.sourceDocumentId!==(source?.id||null)||source&&(value.sourceSha256!==source.sha256||value.sourceMimeType!==(source.mimeType||'application/pdf')))return;
    if(!preserveSelection){selectionGeneration.current++;operation.current.abort();operation.current=new AbortController();}setAppliedSuggestion(null);setSuggestionSource(value);setSourceMimeType(value.sourceMimeType);setFile(data.file);setBytes(data.bytes);setSha256(value.sourceSha256);setPageCount(0);setPage(1);setRenderedPage(null);setNativePages(null);setReading(true);setError('');setPreviewBinding({...scope,requestId:value.requestId,sha256:value.sourceSha256,suggestionId:value.id});
  }
  async function loadPendingSuggestion(value:PendingPdfSplit|StoredPendingPdfSplit){
    if(!value.suggestionId)return;const generation=selectionGeneration.current,active=()=>mounted.current&&generation===selectionGeneration.current;
    const job=await getSplitSuggestion(scope,value.suggestionId,active,operation.current.signal,{sha256:value.sha256,mimeType:value.sourceMimeType||'application/pdf',sourceDocumentId:source?.id||null});if(!active())return;
    if(job.confirmedRequestId&&(job.confirmedRequestId!==value.requestId||job.confirmedOptions&&canonicalPdfSplitSpec(job.confirmedOptions)!==canonicalPdfSplitSpec(value.options)))throw new Error('This AI suggestion was used by another saved split. Check its existing result before continuing.');
    if(job.creationClosed){setAiClosed(true);setNotice('The server confirmed this AI source can no longer create a split. You can explicitly start a new manual split.');return true;}
    if(!bytes){const data=await readSplitSuggestionSource(scope,job,active,operation.current.signal);if(active())restoreSuggestion(job,data,true);}
  }
  async function recoverSuggestedResult(value:SplitSuggestion){
    if(pending||running.current||!value.confirmedRequestId||!value.confirmedOptions||value.sourceDocumentId!==(source?.id||null)||sha256&&value.sourceSha256!==sha256)return;
    try{const saved:PendingPdfSplit|StoredPendingPdfSplit={version:1,...scope,requestId:value.confirmedRequestId,sha256:value.sourceSha256,sourceMimeType:value.sourceMimeType,options:value.confirmedOptions,suggestionId:value.id,...(source?{sourceDocumentId:source.id,savedAt:Date.now()}:{})};persist(saved);setSourceMimeType(value.sourceMimeType);await check(saved);}catch(cause){if(mounted.current)setError(cause instanceof Error?cause.message:'The existing split result could not be checked.');}
  }
  function applySuggestion(value:SplitSuggestion){
    if(value.pageCount!==pageCount){setError('The AI page count does not match this preview. Reopen the source before applying ranges.');return;}
    if(pending||value.sourceSha256!==sha256||value.sourceMimeType!==sourceMimeType||value.sourceDocumentId!==(source?.id||null)||value.state!=='ready'||value.confirmedRequestId||value.creationClosed||Date.parse(value.expiresAt)<=Date.now()||!value.ranges)return;
    setAppliedSuggestion(value);setAiExpired(false);setRanges(value.ranges.map(range=>range.start===range.end?String(range.start):`${range.start}-${range.end}`).join(', '));setMode('ranges');setManualChanged(true);setTab('Ranges');
  }
  useLayoutEffect(()=>{setAiExpired(false);if(!appliedSuggestion)return;const remaining=Date.parse(appliedSuggestion.expiresAt)-Date.now();if(remaining<=0){setAiExpired(true);return;}const timer=setTimeout(()=>setAiExpired(true),Math.min(remaining+50,2147483647));return()=>clearTimeout(timer);},[appliedSuggestion?.id,appliedSuggestion?.expiresAt]);
  function received(value:PdfSplitReceipt|StoredPdfSplitRejected){if(!mounted.current)return;if('rejected' in value){setRejected(value);setReceipt(null);}else{setReceipt(value);setRejected(null);}setNotice('');setError('');void client.invalidateQueries();onComplete?.();}
  async function check(value=pending){
    if(!value||running.current)return false;const generation=selectionGeneration.current;markBusy(true);setError('');setNotice('Checking split result…');
    try{const result=await findReceipt(value);if(!mounted.current||generation!==selectionGeneration.current)return false;if(result){received(result);return true;}if(value.suggestionId){const closed=await loadPendingSuggestion(value);if(closed)return false;if(!mounted.current||generation!==selectionGeneration.current)return false;}setNotice(source?'No completed split receipt was found yet. Retry this saved request to check or finish the same batch.':'No completed split receipt was found yet. Reselect the same file if needed, then retry this request.');return false;}
    catch(cause){
      if(value.suggestionId&&mounted.current&&generation===selectionGeneration.current){try{if(await loadPendingSuggestion(value))return false;}catch{/* Only an authoritative matching closed job resolves this binding. */}}
      if(mounted.current&&generation===selectionGeneration.current){setNotice('');setError(cause instanceof Error?cause.message:'The split result could not be checked.');}
    }
    finally{if(mounted.current&&generation===selectionGeneration.current)markBusy(false);}
  }
  useLayoutEffect(()=>{mounted.current=true;operation.current=new AbortController();let active=true;void(async()=>{const found=pending?await check(pending):false;if(active&&source&&!found&&!pending?.suggestionId)await loadSource();})();return()=>{active=false;mounted.current=false;operation.current.abort();selectionGeneration.current++;running.current=false;onBusy(false);};},[]);
  useLayoutEffect(()=>{if(error)errorView.current?.scrollIntoView({block:'nearest'});},[error]);
  async function preparePreview(next:File,digest:string,generation=selectionGeneration.current){
    setReading(true);setError('');
    try{const binding=await prepareTiffSplitPreview({...scope,requestId:previewRequest.current,sha256:digest,...(pending?{options:pending.options}:{})},next,()=>mounted.current&&generation===selectionGeneration.current,operation.current.signal);if(mounted.current&&generation===selectionGeneration.current){if(pending&&binding.uploadId)persist({...pending,uploadId:binding.uploadId});setPreviewBinding(binding);}}
    catch(cause){if(mounted.current&&generation===selectionGeneration.current){setReading(false);setError(cause instanceof Error?cause.message:'The TIFF could not be prepared for preview.');}}
  }
  async function chooseFile(next:File|undefined){
    if(!next||running.current)return;setSelectionIntent(true);const generation=++selectionGeneration.current;operation.current.abort();operation.current=new AbortController();previewRequest.current=pending?.requestId||crypto.randomUUID();setPreviewBinding(null);setSuggestionSource(null);setAppliedSuggestion(null);setManualChanged(false);setAiExpired(false);
    setError('');setNotice('');setFile(null);setBytes(null);setSha256('');setPageCount(0);setPage(1);setRenderedPage(null);setNativePages(null);setTextError('');setReading(true);
    try{
      if(next.size<1||next.size>pdfSplitLimits.maxBytes)throw new Error('Choose a PDF or TIFF with data, up to 10 MB.');
      const contents=await next.arrayBuffer(),digest=await pdfSha256(contents);
      if(!mounted.current||generation!==selectionGeneration.current)return;
      const mimeType=isTiffSplitSource(contents)?'image/tiff':'application/pdf';
      if(pending&&(digest!==pending.sha256||mimeType!==(pending.sourceMimeType||'application/pdf')))throw new Error('This is a different file. Reselect the original file to retry this request, or explicitly start a new split.');
      setSourceMimeType(mimeType);if(parser.allowedFormats&&!parser.allowedFormats.includes(mimeType==='image/tiff'?'tiff':'pdf'))throw new Error(`This parser does not accept ${mimeType==='image/tiff'?'TIFF':'PDF'} files. Enable this format in parser settings before previewing.`);if(mimeType==='image/tiff'&&mode==='marker'&&!pending)setMode('every');setFile(next);setSha256(digest);setBytes(new Uint8Array(contents));if(pending?.suggestionId){const job=await getSplitSuggestion(scope,pending.suggestionId,()=>mounted.current&&generation===selectionGeneration.current,operation.current.signal,{sha256:digest,mimeType,sourceDocumentId:source?.id||null});if(mounted.current&&generation===selectionGeneration.current){setSuggestionSource(job);setPreviewBinding({...scope,requestId:job.requestId,sha256:digest,suggestionId:job.id});}}else if(mimeType==='image/tiff')await preparePreview(next,digest,generation);
    }catch(cause){if(generation===selectionGeneration.current){setReading(false);setError(cause instanceof Error?cause.message:'The file could not be read.');}}
  }
  async function submit(){
    if(running.current||!ready||!options||!canSubmit||!source&&!file)return;
    markBusy(true);setError('');setNotice(source?`Checking the stored ${kind} and creating this split…`:`Uploading and checking the ${kind}…`);
    let request=pending;
    try{
      if(!request){const created:PendingPdfSplit|StoredPendingPdfSplit={version:1,workspaceId:workspace,parserId:parser.id,requestId:!appliedSuggestion&&!source&&isTiff&&previewBinding&&!previewBinding.suggestionId?previewBinding.requestId:crypto.randomUUID(),sha256,options,...(appliedSuggestion?{suggestionId:appliedSuggestion.id,userId,sourceMimeType}:{}),...(isTiff?{sourceMimeType:'image/tiff' as const,...(!source?{userId}:{})}:{}),...(!appliedSuggestion&&!source&&isTiff&&previewBinding?.uploadId&&!previewBinding.suggestionId?{uploadId:previewBinding.uploadId}:{}),...(source?{userId,sourceDocumentId:source.id,savedAt:Date.now()}:{})};persist(created);request=created;}
      const result=request.suggestionId?await createSuggestedSplit({...request,userId,suggestionId:request.suggestionId,...(source?{sourceDocumentId:source.id}:{})},()=>mounted.current,operation.current.signal):source?await submitStoredPdfSplit(request as StoredPendingPdfSplit,()=>mounted.current,operation.current.signal):await uploadPdfSplit(request,file!,value=>{if(mounted.current)persist(value);else saveMatchingPendingPdfSplit(value);},()=>mounted.current);if(mounted.current)received(result);
    }catch(cause){
      if(!mounted.current)return;setNotice('');const message=cause instanceof TypeError?'The split could not be confirmed. Check your connection and try again.':cause instanceof Error?cause.message:'The split could not be confirmed.';
      if(request){try{const result=await findReceipt(request);if(result){received(result);return;}}catch{/* Preserve the original actionable error; the same request remains recoverable. */}}
      if(!mounted.current)return;setError(`${message}${request?' Your saved request is retained. Check its result before starting a new split.':source?' No split was started.':' No upload was started.'}`);
    }finally{if(mounted.current)markBusy(false);}
  }
  function startNew(){
    try{if(source){if(!receipt&&!rejected&&!aiClosed||!pending)return;clearStoredPdfSplit(scope,source.id,pending.requestId);}else clearPendingPdfSplit(workspace,parser.id,userId);selectionGeneration.current++;setReading(false);setRenderedPage(null);setPending(null);setReceipt(null);setRejected(null);setFile(null);setBytes(null);setSha256('');setPageCount(0);setPage(1);setSourceMimeType(source?.mimeType||'application/pdf');setPreviewBinding(null);previewRequest.current='';setMode('every');setEvery('1');setRanges('');setMarker('');setNativePages(null);setTextError('');setConfirmNew(false);setAppliedSuggestion(null);setSuggestionSource(null);setAiClosed(false);setAiExpired(false);setManualChanged(false);setSelectionIntent(true);setError('');setNotice('');if(fileInput.current)fileInput.current.value='';if(source)void loadSource();}
    catch(cause){setError(source&&cause instanceof Error?cause.message:'The saved request could not be cleared. Enable browser session storage before starting another split.');}
  }
  return <div className="pdf-split-dialog" aria-busy={busy}>
    <div ref={errorView}><Notice error={error} message={notice}/></div>
    {receipt?<section className="pdf-split-receipt" aria-label={`${kind} split result`}>{receipt.split.undoneAt&&<Notice message="This split was undone. Its created documents were removed; the source and page-credit usage are unchanged."/>}<h3>{receipt.split.childCount} document{receipt.split.childCount===1?'':'s'} received · {receipt.split.selectedPages} page{receipt.split.selectedPages===1?'':'s'}</h3><p>{receipt.split.undoneAt?'This is a historical split result.':receipt.replayed?'This is the existing split result. Replaying it uses no additional page credits.':'The selected pages were received. Processing continues in the background.'} Review and approve each document before exporting.</p><ol>{receipt.documents.map(document=><li key={document.id}>{document.available?<Link className="link" to={`/app/documents/${document.id}`}>{document.name||`Document ${document.index}`}</Link>:<span>Document {document.index} · Deleted</span>}<span className="small muted">{source?`Source ${kind} pages`:'Original pages'} {pageRange(document.originalPageStart,document.originalPageEnd)} · {document.pageCount} page{document.pageCount===1?'':'s'}</span></li>)}</ol>{source&&<><p className="small">The source {kind}, its earlier results and original-only exports are preserved. Undo removes only this new batch and exports containing its children; used page credits stay unchanged.</p><UndoPdfSplit receipt={receipt} onChanged={received}/></>}<p className="small muted">{source?(receipt.split.sourceAvailable?'This batch retains a complete source copy, including omitted pages.':'This batch no longer retains a separate source copy.'):(receipt.split.sourceAvailable?`The full original ${kind} remains available from a retained document, including omitted pages.`:`The full original ${kind} is no longer available.`)}</p>{source&&receipt.split.sourceDocumentAvailable&&receipt.split.sourceDocumentId&&<Link className="link" to={`/app/documents/${receipt.split.sourceDocumentId}`}>Open source document</Link>}</section>:rejected?<section className="pdf-split-receipt" aria-label={`${kind} split not created`}><h3>Split not created</h3><p>{rejected.rejected.message}</p><p className="small">The server confirmed that this saved request was rejected. The source is preserved. After addressing the reason, you can explicitly start a new split.</p></section>:<>
      {pending&&<div className="pdf-split-recovery"><h3>Resume this split</h3><p className="small">Saved selection: {describe(pending.options)}. Retry keeps the same request and does not create a second batch.</p><Button type="button" variant="secondary" disabled={busy} onClick={()=>void check()}>Check split result</Button></div>}
      {source?<div className="pdf-stored-source"><p className="small pdf-split-filename"><strong>Source {kind}:</strong> {source.name} · {source.pageCount} pages</p><p className="small muted">Page numbers below refer to this document. Its original, review history and earlier original-only exports stay unchanged.</p>{!bytes&&<Button type="button" variant="secondary" disabled={busy||reading} onClick={()=>void loadSource()}>{reading?`Loading source ${kind}…`:`Retry loading source ${kind}`}</Button>}</div>:<Field label={pending?`Reselect the same ${kind}`:'PDF or TIFF to split'} hint={`One file, up to 10 MB and ${pdfSplitLimits.maxPages} pages. PDF preview stays on this device. TIFF files are uploaded to generate page previews; no documents or page charges are created until you submit.`}><input ref={fileInput} type="file" accept=".pdf,.tif,.tiff,application/pdf,image/tiff" disabled={busy} onChange={event=>void chooseFile(event.target.files?.[0])}/></Field>}
      {!pending&&<SplitSuggestionPanel scope={scope} documentId={source?.id||null} sha256={sha256} mimeType={sourceMimeType} file={file} allowAutoRestore={!selectionIntent} disabled={busy||!canSubmit} manualChanged={manualChanged||mode==='ranges'&&Boolean(ranges.trim())||mode==='marker'&&Boolean(marker.trim())||mode==='every'&&every!=='1'} appliedId={appliedSuggestion?.id} onApply={applySuggestion} onRestore={restoreSuggestion} onRecoverAccepted={value=>void recoverSuggestedResult(value)} onJob={value=>{if(value.sourceSha256===sha256&&value.sourceMimeType===sourceMimeType){if(value.pageCount&&pageCount&&value.pageCount!==pageCount){setError('The AI page count does not match this source preview. Reopen the source before applying ranges.');return;}if(suggestionSource?.id===value.id)setSuggestionSource(value);if(appliedSuggestion?.id===value.id)setAppliedSuggestion(value);}}}/>}
      {appliedSuggestion&&!pending&&<div className="split-suggestion-applied"><p className="small">AI ranges applied. Your custom edits stay linked to this suggestion. Review the source before creating documents.</p>{(aiExpired||appliedSuggestion.creationClosed)&&<Notice error="This AI suggestion is no longer available for creation. Start a new suggestion or explicitly use a new manual split."/>}<Button type="button" variant="ghost" disabled={busy} onClick={()=>{setAppliedSuggestion(null);setAiExpired(false);setSuggestionSource(null);if(previewBinding?.suggestionId){setPreviewBinding(null);previewRequest.current=crypto.randomUUID();if(isTiff&&file)void preparePreview(file,sha256);}}}>Use these as manual ranges instead</Button></div>}
      {file&&<p className="small pdf-split-filename">{file.name}{pageCount?` · ${pageCount} pages`:''}</p>}{isTiff&&!source&&file&&!previewBinding&&!suggestionSource&&<Button variant="secondary" disabled={reading||busy} onClick={()=>void preparePreview(file,sha256)}>{reading?'Preparing TIFF preview…':'Retry preparing TIFF preview'}</Button>}{!pending&&!source&&file&&isTiff&&previewBinding?.suggestionId&&<Button type="button" variant="secondary" disabled={busy||reading} onClick={()=>{setSuggestionSource(null);setPreviewBinding(null);previewRequest.current=crypto.randomUUID();void preparePreview(file,sha256);}}>Use file for manual preview</Button>}{isTiff&&<p className="small muted">TIFF supports fixed groups and custom page ranges. New documents remain TIFF files; JPEG images are only page previews.</p>}
      <div className="pdf-split-mobile-tabs"><Tabs items={['Ranges','Preview']} value={tab} onChange={setTab} label={`${kind} split view`}/></div>
      <div className={`pdf-split-columns mobile-${tab.toLowerCase()}`}><section className="pdf-split-controls" aria-label="Split settings">
        {!pending&&<fieldset className="pdf-split-modes" disabled={busy}><legend>Split by</legend><label><input type="radio" name="pdf-split-mode" value="every" checked={mode==='every'} onChange={()=>changeMode('every')}/>Every N pages</label><label><input type="radio" name="pdf-split-mode" value="ranges" checked={mode==='ranges'} onChange={adjustRanges}/>Custom page ranges</label>{!isTiff&&<label><input type="radio" name="pdf-split-mode" value="marker" checked={mode==='marker'} onChange={()=>changeMode('marker')}/>Text marker</label>}</fieldset>}
        {!pending&&(mode==='every'?<Field label="Pages per document" hint="The final document may contain fewer pages."><input type="number" min={1} max={pdfSplitLimits.maxPages} step={1} value={every} disabled={busy} onChange={event=>{setEvery(event.target.value);setManualChanged(true);}}/></Field>:mode==='ranges'?<Field label="Page ranges" hint="For example: 1-2, 5, 7-9. Each range creates one document. Keep ranges in order, without overlaps."><input value={ranges} placeholder="1-2, 5, 7-9" disabled={busy} maxLength={400} onChange={event=>{setRanges(event.target.value);setManualChanged(true);}}/></Field>:<Field label="Text marker" hint="Exact, case-sensitive text (1–200 characters). Spaces and line breaks count as one space."><input value={marker} disabled={busy} maxLength={200} autoComplete="off" spellCheck={false} placeholder="Invoice number" onChange={event=>{setMarker(event.target.value);setManualChanged(true);}}/></Field>)}
        {markerMode&&!isTiff&&<div className="pdf-split-marker-info"><p className="small">Each matching page starts a document. Pages before the first match stay together.</p><p className="small muted">Uses searchable PDF text. Pages containing only images are retained; use custom ranges for boundaries found only in an image.</p>{(file||source&&bytes)&&!nativePages&&!textError&&<p className="small" role="status">Reading searchable text on this device…</p>}{markerPlan&&<p className="small pdf-split-marker-matches" role="status"><strong>Marker found on pages {markerPlan.matchedPages.join(', ')}.</strong>{markerPlan.textlessPages.length>0&&<span> No searchable text on pages {markerPlan.textlessPages.join(', ')}. These pages stay in the ranges below; inspect them before creating documents.</span>}</p>}{nativePages&&!markerPlan&&nativePages.some(text=>!text.trim())&&nativePages.some(text=>text.trim())&&<p className="small">Pages without searchable text: {nativePages.flatMap((text,index)=>text.trim()?[]:[index+1]).join(', ')}. Check custom ranges if a boundary falls on one of these pages.</p>}</div>}
        {planError&&<Notice error={planError}/>}
        {!pending&&markerPlan&&<Button type="button" variant="secondary" disabled={busy} onClick={adjustRanges}>Adjust page ranges</Button>}
        {plan&&<><div className="pdf-split-quota" role="status"><strong>{plan.ranges.length} document{plan.ranges.length===1?'':'s'} · {plan.selectedPages} of {pageCount} pages selected</strong><p>{source?'Uses an additional ':'Uses '}{plan.selectedPages} page credit{plan.selectedPages===1?'':'s'}. {source?'This is a new operation; earlier source-page usage is not refunded.':`The full ${kind} is not queued separately.`} The server checks the actual pages before accepting the split.</p>{omitted.length>0&&<p><strong>Omitted pages: {omitted.join(', ')}.</strong> These pages will not become documents or use page credits.</p>}</div><ol className="pdf-split-parts">{plan.ranges.map((range,index)=><li key={index}><button type="button" disabled={busy} onClick={()=>{setPage(range.start);setTab('Preview');}}><strong>Document {index+1}</strong><span>{source?`Source ${kind} pages`:'Original pages'} {pageRange(range.start,range.end)} · {range.end-range.start+1} page{range.end===range.start?'':'s'}</span></button></li>)}</ol></>}
      </section><section className="pdf-split-preview" aria-label={`${kind} preview`}><div className="pdf-split-preview-toolbar"><Button type="button" variant="ghost" aria-label={`Previous ${kind} page`} disabled={!pageCount||page<=1} onClick={()=>setPage(page-1)}><ChevronLeft/></Button><span>Page {pageCount?page:0} of {pageCount}</span><Button type="button" variant="ghost" aria-label={`Next ${kind} page`} disabled={!pageCount||page>=pageCount} onClick={()=>setPage(page+1)}><ChevronRight/></Button></div>{isTiff?(bytes&&(source||previewBinding||suggestionSource)?<TiffSplitPreview key={`${sha256}:${source?.id||'upload'}`} binding={source?{...scope,requestId:source.id,sha256}:suggestionSource?{...scope,requestId:suggestionSource.requestId,sha256,suggestionId:suggestionSource.id}:previewBinding!} file={file||undefined} documentId={source?.id} expectedPages={source?.pageCount||suggestionSource?.pageCount||undefined} page={page} onReady={count=>{if(previewGeneration===selectionGeneration.current){setPageCount(count);setError('');}}} onRendered={rendered=>{if(previewGeneration===selectionGeneration.current){setReading(false);setRenderedPage(rendered);}}} onError={message=>{if(previewGeneration===selectionGeneration.current){setReading(false);setRenderedPage(null);setPageCount(0);setError(message);}}}/>:<p className="small muted">Preparing TIFF page preview…</p>):bytes?<PdfCanvas key={sha256} bytes={bytes} page={page} label={`PDF preview, original page ${page}`} readNativeText={markerMode} onNativeText={pages=>{if(previewGeneration!==selectionGeneration.current)return;setNativePages(pages);setTextError('');}} onNativeTextError={message=>{if(previewGeneration!==selectionGeneration.current)return;setNativePages(null);setTextError(message);}} onReady={count=>{if(previewGeneration!==selectionGeneration.current)return;if((source||suggestionSource?.pageCount)&&count!==(source?.pageCount||suggestionSource?.pageCount)){setError('The source page count could not be verified. Reopen the document.');setPageCount(0);setReading(false);}else setPageCount(count);}} onRendered={rendered=>{if(previewGeneration!==selectionGeneration.current)return;setReading(false);setRenderedPage(rendered);}} onError={message=>{if(previewGeneration!==selectionGeneration.current)return;setReading(false);setRenderedPage(null);setPageCount(0);setNativePages(null);setError(message);}}/>:<p className="small muted">{source?`Loading the stored ${kind} for preview.`:'Choose a PDF or TIFF to inspect its pages.'}</p>}</section></div>
      <p className="small pdf-split-retention">{source?`The source stays in this workspace. Each new batch also retains the complete ${kind}, including omitted pages. Undo removes only that batch and exports containing its created documents; it does not remove the source, sibling splits or nested batches, or refund used page credits.`:`The full original ${kind} is retained, including omitted pages and pages from deleted documents, while any document in this batch remains. To remove the full source, delete the whole batch from document review.`}</p>
      <div className="actions pdf-split-submit"><Button type="button" disabled={busy||!ready||!canSubmit} onClick={()=>void submit()}>{busy?'Checking split…':frozen?'Retry same split':plan?`Create ${plan.ranges.length} document${plan.ranges.length===1?'':'s'} from ${plan.selectedPages} pages`:'Create split documents'}</Button><Button type="button" variant="ghost" disabled={busy} onClick={onClose}>{pending?'Close for now':'Cancel'}</Button></div>
      {!canSubmit&&<p className="small muted">This parser cannot accept a new split right now. Existing results can still be checked. Restore the parser, complete field setup, and allow {kind} before retrying an incomplete upload. <Link className="link" to={`/app/parsers/${parser.id}?tab=settings`}>Open parser settings</Link></p>}
    </>}
    {(pending||receipt)&&(!source&&!pending?.suggestionId||receipt||rejected||aiClosed)&&<div className="pdf-split-new">{confirmNew?<><p>{receipt||rejected||aiClosed?`A new split is a separate ${source?'operation':'upload'} and uses new page credits.`:'The earlier request may still finish. Starting a new split can create another batch and use additional page credits. Check the result first.'}</p><div className="actions"><Button type="button" variant="secondary" disabled={busy||!eligible} onClick={startNew}>Start new split anyway</Button><Button type="button" variant="ghost" disabled={busy} onClick={()=>setConfirmNew(false)}>Keep this request</Button></div></>:<div className="actions"><Button type="button" variant="ghost" disabled={busy||!eligible} onClick={()=>setConfirmNew(true)}>Start a new split</Button>{(receipt||rejected)&&<Button type="button" variant="secondary" onClick={onClose}>Done</Button>}</div>}</div>}
  </div>;
}
