import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import Fastify,{type FastifyInstance} from 'fastify';
import cookie from '@fastify/cookie';
import multipart from '@fastify/multipart';
import {randomUUID} from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import {ZodError} from 'zod';
import {registerCore} from '../server/core/index.js';
import {adminPool,appPool,withWorkspace,closeDatabase} from '../server/core/db.js';
import {addDocument} from '../server/core/intake.js';
import {processOneCoreJob,setExtractionProvider} from '../server/core/worker.js';
import {extractRules,normalizeValue} from '../server/core/extraction.js';
import {validateValues} from '../server/core/schema.js';
import {config} from '../server/core/config.js';
import {presets} from '../shared/presets.js';
import type {Actor} from '../shared/types.js';
let app:FastifyInstance;const userIds:string[]=[],workspaceIds:string[]=[];
const suffix=randomUUID().slice(0,8);let account:any,other:any,parser:any,document:any,run:any;
function headers(a=account){return {cookie:a.cookie,origin:config.origin};}
async function request(method:any,url:string,payload?:unknown,a=account){const response=await app.inject({method,url,payload:payload as any,headers:a?headers(a):{origin:config.origin}});return {status:response.statusCode,body:response.headers['content-type']?.includes('application/json')?response.json():response.body,response};}
async function signup(name:string){const response=await app.inject({method:'POST',url:'/api/auth/register',payload:{name,email:`${name}-${suffix}@example.test`,password:'correct horse battery',workspaceName:`Test ${name}`},headers:{origin:config.origin}});assert.equal(response.statusCode,201,response.body);const result=response.json();userIds.push(result.user.id);workspaceIds.push(result.workspace.id);return {...result,cookie:response.cookies.map(c=>`${c.name}=${c.value}`).join('; '),actor:{userId:result.user.id,workspaceId:result.workspace.id,role:'owner',authType:'session'} as Actor};}
before(async()=>{app=Fastify({logger:false});await app.register(cookie);await app.register(multipart);app.setErrorHandler((error:any,_req,reply)=>{reply.code(error instanceof ZodError?400:error.statusCode||500).send({error:error.message});});await registerCore(app);await app.ready();account=await signup('primary');other=await signup('secondary');
 // These lifecycle cases deliberately share multiple parsers; signup entitlements are covered separately.
 await adminPool.query("update workspaces set plan=jsonb_set(plan,'{maxParsers}','10'::jsonb) where id=$1",[account.workspace.id]);
});
after(async()=>{await app?.close();for(const id of workspaceIds){await adminPool.query('delete from workspaces where id=$1',[id]);await fs.rm(path.join(config.storageDir,id),{recursive:true,force:true});}for(const id of userIds)await adminPool.query('delete from users where id=$1',[id]);await closeDatabase();});
test('local authentication creates persistent workspace and HTTP-only session',async()=>{assert.equal(account.workspace.role,'owner');const me=await request('GET','/api/auth/me');assert.equal(me.body.user.email,account.user.email);const raw=(await adminPool.query('select password_hash from users where id=$1',[account.user.id])).rows[0].password_hash;assert.ok(!raw.includes('correct horse'));assert.ok(raw.includes(':'));const wrong=await request('POST','/api/auth/login',{email:account.user.email,password:'incorrect password'});assert.equal(wrong.status,401);});
test('parser and versioned schema persist; rules capture native evidence and identifiers',async()=>{const created=await request('POST','/api/parsers',{name:'Invoice QA',useCase:'invoice'});assert.equal(created.status,201,JSON.stringify(created.body));parser=created.body.parser;const result=await addDocument(account.actor,parser.id,Buffer.from(presets.invoice.sample),'invoice.txt');document=result.document;assert.equal(document.status,'queued');for(let i=0;i<8;i++){await processOneCoreJob();const detail=await request('GET',`/api/documents/${document.id}`);if(detail.body.runs.length){run=detail.body.runs[0];break;}}assert.ok(run,'processing persisted an extraction run');assert.equal(run.effectiveValues.invoice_number,'INV-00127');assert.equal(run.effectiveValues.total,553.5);assert.equal(run.effectiveValues.line_items.length,2);assert.equal(run.rawValues.total,'553.50');assert.equal(run.evidence.invoice_number[0].page,1);assert.equal(run.schemaVersion,1);assert.equal(run.issues.length,0);const copy=await request('GET',`/api/documents/${document.id}/original`);assert.equal(copy.status,200);assert.ok(copy.response.headers['content-security-policy']);});
test('duplicate intake and idempotency do not meter twice',async()=>{const duplicate=await addDocument(account.actor,parser.id,Buffer.from(presets.invoice.sample),'renamed.txt','text/plain','fixture-duplicate');assert.equal(duplicate.duplicate,true);assert.equal(duplicate.document.id,document.id);const count=(await adminPool.query('select count(*)::int count from usage_ledger where document_id=$1',[document.id])).rows[0].count;assert.equal(count,1);});
test('tenant isolation is enforced through routes and database RLS',async()=>{assert.equal((await request('GET',`/api/documents/${document.id}`,undefined,other)).status,404);assert.equal((await request('POST',`/api/documents/${document.id}/reprocess`,{},other)).status,404);const raw=await withWorkspace(other.workspace.id,c=>c.query('select id from documents where id=$1',[document.id]));assert.equal(raw.rowCount,0);const withoutContext=await appPool.query('select id from documents');assert.equal(withoutContext.rowCount,0);await assert.rejects(appPool.query('select * from users'),/permission denied/);});
test('correction and approval create immutable events and reject stale revisions',async()=>{const changed={...run.effectiveValues,supplier:'Juniper Studio Ltd'};const correction=await request('POST',`/api/runs/${run.id}/corrections`,{values:changed,expectedRevision:run.effectiveRevision});assert.equal(correction.status,200,JSON.stringify(correction.body));assert.equal(correction.body.run.normalizedValues.supplier,'Juniper Studio');assert.equal(correction.body.run.effectiveValues.supplier,'Juniper Studio Ltd');const stale=await request('POST',`/api/runs/${run.id}/approve`,{expectedRevision:run.effectiveRevision});assert.equal(stale.status,409);run=correction.body.run;const approve=await request('POST',`/api/runs/${run.id}/approve`,{expectedRevision:run.effectiveRevision});assert.equal(approve.status,200,JSON.stringify(approve.body));const detail=await request('GET',`/api/documents/${document.id}`);assert.equal(detail.body.document.status,'processed');assert.equal(detail.body.document.approvedRunId,run.id);});
test('schema and settings changes do not alter pinned runs; reprocess preserves approval',async()=>{const schema={fields:[...presets.invoice.fields,{key:'reference',label:'Reference',type:'string',required:false}]};const changed=await request('POST',`/api/parsers/${parser.id}/schema`,schema);assert.equal(changed.status,200,JSON.stringify(changed.body));assert.equal(changed.body.schema.version,2);const queued=await request('POST',`/api/documents/${document.id}/reprocess`,{});assert.equal(queued.status,200);await processOneCoreJob();const detail=await request('GET',`/api/documents/${document.id}`);assert.equal(detail.body.runs.length,2);assert.equal(detail.body.runs[0].schemaVersion,2);assert.equal(detail.body.runs[1].schemaVersion,1);assert.equal(detail.body.document.approvedRunId,run.id);assert.equal(detail.body.runs[1].approvals[0].values.supplier,'Juniper Studio Ltd');});
test('role restrictions, invitation acceptance and scoped revocable API keys',async()=>{const invitation=await request('POST','/api/workspace/members',{email:other.user.email,role:'viewer'});assert.equal(invitation.status,200);const accepted=await request('POST','/api/workspace/invitations/accept',{token:invitation.body.token},other);assert.equal(accepted.status,200);const selected=await request('POST',`/api/workspaces/${account.workspace.id}/select`,{},other);assert.equal(selected.status,200);const forbidden=await request('POST','/api/parsers',{name:'Blocked',useCase:'custom'},other);assert.equal(forbidden.status,403);assert.equal((await request('GET','/api/parsers',undefined,other)).status,200);const made=await request('POST','/api/workspace/api-keys',{name:'Read test',scopes:['documents:read']});assert.equal(made.status,200);const bearer={authorization:`Bearer ${made.body.token}`};assert.equal((await app.inject({method:'GET',url:'/api/documents',headers:bearer})).statusCode,200);assert.equal((await app.inject({method:'POST',url:`/api/documents/${document.id}/reprocess`,headers:bearer,payload:{}})).statusCode,403);await request('DELETE',`/api/workspace/api-keys/${made.body.apiKey.id}`);assert.equal((await app.inject({method:'GET',url:'/api/documents',headers:bearer})).statusCode,401);});
test('invalid uploads, scan without provider, and missing values fail honestly',async()=>{await assert.rejects(addDocument(account.actor,parser.id,Buffer.from('not PDF'),'broken.pdf'),/valid PDF/);await assert.rejects(addDocument(account.actor,parser.id,Buffer.alloc(0),'empty.txt'),/empty/);await assert.rejects(addDocument(account.actor,parser.id,Buffer.from('some content'),'unknown.exe'),/Supported formats/);const sharp=(await import('sharp')).default;const image=await sharp({create:{width:100,height:100,channels:3,background:'#ffffff'}}).png().toBuffer();const result=await addDocument(account.actor,parser.id,image,'scan.png');await processOneCoreJob();const detail=await request('GET',`/api/documents/${result.document.id}`);assert.equal(detail.body.document.status,'failed');assert.match(detail.body.document.error,/OCR\/AI/);assert.equal(detail.body.runs.length,0);const missing=extractRules([{page:1,text:'Invoice number: 0000042'}],{fields:presets.invoice.fields},'en-IE');assert.equal(missing.normalizedValues.invoice_number,'0000042');assert.equal(missing.normalizedValues.total,null);assert.ok(missing.issues.some(i=>i.field==='total'&&i.code==='required'));});
test('worker lease recovery and retry reuse one usage reservation',async()=>{const content=presets.receipt.sample+'\nReference: restart-'+suffix;const p=(await request('POST','/api/parsers',{name:'Restart QA',useCase:'receipt'})).body.parser;const result=await addDocument(account.actor,p.id,Buffer.from(content),'restart.txt');await adminPool.query("update jobs set state='processing',attempts=1,lease_owner='terminated-test-worker',lease_until=now()-interval '1 second' where id=$1",[result.jobId]);await adminPool.query("update documents set status='processing' where id=$1",[result.document.id]);await processOneCoreJob();const detail=await request('GET',`/api/documents/${result.document.id}`);assert.equal(detail.body.document.status,'needs_review');assert.equal(detail.body.jobs[0].attempts,2);assert.equal(detail.body.runs.length,1);assert.equal((await adminPool.query('select count(*)::int n from usage_ledger where document_id=$1',[result.document.id])).rows[0].n,1);});
test('saved template matching is explicit and rule anchors work',()=>{const schema={fields:[{key:'reference',label:'Reference',type:'string' as const,required:true}]};const pages=[{page:1,text:'ACORN CONTRACT\nContract ID: 000123'}];const matched=extractRules(pages,schema,'en-IE',[{enabled:true,match_text:'ACORN CONTRACT',rules:[{field:'reference',anchor:'Contract ID'}]}]);assert.equal(matched.normalizedValues.reference,'000123');const unmatched=extractRules(pages,schema,'en-IE',[{enabled:true,match_text:'DIFFERENT CONTRACT',rules:[{field:'reference',anchor:'Contract ID'}]}]);assert.equal(unmatched.normalizedValues.reference,null);assert.ok(unmatched.issues.some(i=>i.code==='no_template'));});
test('normalization handles EU decimals, dates, booleans and invalid dates',()=>{assert.equal(normalizeValue('€ 1.234,50',{key:'total',label:'Total',type:'currency'},'de-DE'),1234.5);assert.equal(normalizeValue('06/09/2026',{key:'date',label:'Date',type:'date'},'en-IE'),'2026-09-06');assert.equal(normalizeValue('06/09/2026',{key:'date',label:'Date',type:'date'},'en-US'),'2026-06-09');assert.equal(normalizeValue('yes',{key:'paid',label:'Paid',type:'boolean'},'en-IE'),true);assert.ok(validateValues({date:'2026-99-99'},{fields:[{key:'date',label:'Date',type:'date'}]}).some(i=>i.code==='date'));});
test('mutations reject cross-origin browser requests',async()=>{const reply=await app.inject({method:'POST',url:'/api/parsers',headers:{cookie:account.cookie,origin:'https://unrelated.example'},payload:{name:'No',useCase:'custom'}});assert.equal(reply.statusCode,403);});
test('deletion removes original and tenant-derived runs',async()=>{const before=await request('GET',`/api/documents/${document.id}`);const storage=path.join(config.storageDir,before.body.document.storageKey);assert.equal((await request('DELETE',`/api/documents/${document.id}`)).status,200);await assert.rejects(fs.access(storage));assert.equal((await request('GET',`/api/documents/${document.id}`)).status,404);assert.equal((await adminPool.query('select id from extraction_runs where document_id=$1',[document.id])).rowCount,0);});

test('atomic quota reservation prevents concurrent overage',async()=>{const prior=(await adminPool.query('select plan from workspaces where id=$1',[account.workspace.id])).rows[0].plan;const used=Number((await adminPool.query("select coalesce(sum(pages),0) n from usage_ledger where workspace_id=$1 and created_at>=date_trunc('month',now())",[account.workspace.id])).rows[0].n);try{await adminPool.query('update workspaces set plan=$2 where id=$1',[account.workspace.id,JSON.stringify({...prior,monthlyPages:used+1})]);const p=(await request('POST','/api/parsers',{name:'Quota QA',useCase:'receipt'})).body.parser;const result=await Promise.allSettled([addDocument(account.actor,p.id,Buffer.from(presets.receipt.sample+'\nA'),'quota-a.txt'),addDocument(account.actor,p.id,Buffer.from(presets.receipt.sample+'\nB'),'quota-b.txt')]);assert.equal(result.filter(r=>r.status==='fulfilled').length,1);assert.equal(result.filter(r=>r.status==='rejected'&&(r.reason as any).statusCode===429).length,1);await processOneCoreJob();}finally{await adminPool.query('update workspaces set plan=$2 where id=$1',[account.workspace.id,JSON.stringify(prior)]);}});
test('automatic transient retries stop at the configured maximum and meter once',async()=>{const p=(await request('POST','/api/parsers',{name:'Failure QA',useCase:'receipt',mode:'ai'})).body.parser;const result=await addDocument(account.actor,p.id,Buffer.from(presets.receipt.sample+'\nTransient'),'transient.txt');setExtractionProvider({configured:()=>true,extract:async()=>{throw new Error('Controlled transient dependency failure');}});try{for(let i=0;i<3;i++){await adminPool.query('update jobs set available_at=now() where id=$1',[result.jobId]);await processOneCoreJob();}const detail=await request('GET',`/api/documents/${result.document.id}`);assert.equal(detail.body.document.status,'failed');assert.equal(detail.body.jobs[0].attempts,3);assert.match(detail.body.document.error,/Controlled transient/);assert.equal((await adminPool.query('select count(*)::int n from usage_ledger where document_id=$1',[result.document.id])).rows[0].n,1);}finally{setExtractionProvider(undefined);}});
test('workspace concurrency limit holds across simultaneous worker claims',async()=>{const old=(await adminPool.query('select plan from workspaces where id=$1',[account.workspace.id])).rows[0].plan;await adminPool.query('update workspaces set plan=$2 where id=$1',[account.workspace.id,JSON.stringify({...old,maxConcurrent:1})]);const p=(await request('POST','/api/parsers',{name:'Concurrency QA',useCase:'receipt',mode:'ai'})).body.parser;const first=await addDocument(account.actor,p.id,Buffer.from(presets.receipt.sample+'\nOne'),'one.txt');const second=await addDocument(account.actor,p.id,Buffer.from(presets.receipt.sample+'\nTwo'),'two.txt');let entered!:()=>void,release!:()=>void;const started=new Promise<void>(r=>{entered=r;}),barrier=new Promise<void>(r=>{release=r;});setExtractionProvider({configured:()=>true,extract:async input=>{entered();await barrier;return {...extractRules(input.pages,input.schema,input.locale),engine:'controlled-test-adapter'};}});try{const running=processOneCoreJob();await started;await processOneCoreJob();assert.equal((await adminPool.query("select count(*)::int n from jobs where workspace_id=$1 and state='processing'",[account.workspace.id])).rows[0].n,1);assert.equal((await adminPool.query('select state from jobs where id=$1',[second.jobId])).rows[0].state,'queued');release();await running;await processOneCoreJob();assert.equal((await adminPool.query("select count(*)::int n from extraction_runs where document_id=any($1::uuid[])",[[first.document.id,second.document.id]])).rows[0].n,2);}finally{release();setExtractionProvider(undefined);await adminPool.query('update workspaces set plan=$2 where id=$1',[account.workspace.id,JSON.stringify(old)]);}});
test('file byte and PDF page limits are enforced before persistence',async()=>{await assert.rejects(addDocument(account.actor,parser.id,Buffer.alloc(config.maxBytes+1,65),'too-large.txt'),/10 MB/);const {PDFDocument}=await import('pdf-lib');const pdf=await PDFDocument.create();for(let i=0;i<31;i++)pdf.addPage();await assert.rejects(addDocument(account.actor,parser.id,Buffer.from(await pdf.save()),'too-many-pages.pdf'),/30 pages/);});
test('owner membership cannot be removed or downgraded',async()=>{assert.equal((await request('DELETE',`/api/workspace/members/${account.user.id}`)).status,403);assert.equal((await request('PATCH',`/api/workspace/members/${account.user.id}`,{role:'viewer'})).status,400);});

test('parser restoration respects active quota without blocking ordinary edits or losing configuration',async()=>{
 const owner=await signup('parser-restore');
 await adminPool.query("update workspaces set plan=jsonb_set(plan,'{maxParsers}','1'::jsonb) where id=$1",[owner.workspace.id]);
 const created=await request('POST','/api/parsers',{name:'Original parser',useCase:'receipt',mode:'ai',instructions:'Keep written identifiers.',locale:'de-DE',timezone:'Europe/Berlin'},owner);
 assert.equal(created.status,201,JSON.stringify(created.body));
 const original=created.body.parser;
 assert.equal((await request('PATCH',`/api/parsers/${original.id}`,{archived:true},owner)).status,200);
 const replacement=await request('POST','/api/parsers',{name:'Replacement parser',useCase:'invoice'},owner);
 assert.equal(replacement.status,201,JSON.stringify(replacement.body));
 const auditsBefore=(await adminPool.query('select count(*)::int count from audit_events where workspace_id=$1',[owner.workspace.id])).rows[0].count;
 const rejected=await request('PATCH',`/api/parsers/${original.id}`,{archived:false,name:'Must not persist'},owner);
 assert.equal(rejected.status,429,JSON.stringify(rejected.body));
 assert.match(rejected.body.error,/parser limit/);
 const stillArchived=(await request('GET',`/api/parsers/${original.id}`,undefined,owner)).body.parser;
 assert.equal(stillArchived.archived,true);
 assert.equal(stillArchived.name,'Original parser');
 assert.equal((await adminPool.query('select count(*)::int count from audit_events where workspace_id=$1',[owner.workspace.id])).rows[0].count,auditsBefore);
 const edit=await request('PATCH',`/api/parsers/${replacement.body.parser.id}`,{name:'Edited at capacity',archived:false},owner);
 assert.equal(edit.status,200,JSON.stringify(edit.body));
 assert.equal(edit.body.parser.name,'Edited at capacity');
 const archivedEdit=await request('PATCH',`/api/parsers/${original.id}`,{name:'Preserved original'},owner);
 assert.equal(archivedEdit.status,200,JSON.stringify(archivedEdit.body));
 assert.equal(archivedEdit.body.parser.archived,true);
 assert.equal((await request('PATCH',`/api/parsers/${replacement.body.parser.id}`,{archived:true},owner)).status,200);
 const restored=await request('PATCH',`/api/parsers/${original.id}`,{archived:false},owner);
 assert.equal(restored.status,200,JSON.stringify(restored.body));
 assert.deepEqual({name:restored.body.parser.name,mode:restored.body.parser.mode,instructions:restored.body.parser.instructions,locale:restored.body.parser.locale,timezone:restored.body.parser.timezone,activeSchemaId:restored.body.parser.activeSchemaId},
  {name:'Preserved original',mode:'ai',instructions:'Keep written identifiers.',locale:'de-DE',timezone:'Europe/Berlin',activeSchemaId:original.activeSchemaId});
 assert.equal((await request('POST','/api/parsers',{name:'No remaining capacity'},owner)).status,429);
 const parsers=(await request('GET','/api/parsers',undefined,owner)).body.parsers;
 assert.equal(parsers.filter((p:any)=>!p.archived).length,1);
 assert.equal(parsers.length,2);
});

test('concurrent parser restores and creation share one remaining active slot',async()=>{
 const owner=await signup('parser-race');
 await adminPool.query("update workspaces set plan=jsonb_set(plan,'{maxParsers}','1'::jsonb) where id=$1",[owner.workspace.id]);
 const archivedIds:string[]=[];
 for(const name of ['Archived A','Archived B']){
  const created=await request('POST','/api/parsers',{name},owner);
  assert.equal(created.status,201,JSON.stringify(created.body));
  archivedIds.push(created.body.parser.id);
  assert.equal((await request('PATCH',`/api/parsers/${created.body.parser.id}`,{archived:true},owner)).status,200);
 }
 for(let round=0;round<3;round++){
  const responses=await Promise.all([
   request('PATCH',`/api/parsers/${archivedIds[0]}`,{archived:false},owner),
   request('PATCH',`/api/parsers/${archivedIds[1]}`,{archived:false},owner),
   request('POST','/api/parsers',{name:`Concurrent new ${round}`},owner),
  ]);
  assert.equal(responses.filter(r=>r.status===200||r.status===201).length,1,JSON.stringify(responses.map(r=>({status:r.status,body:r.body}))));
  assert.equal(responses.filter(r=>r.status===429).length,2);
  const active=(await request('GET','/api/parsers',undefined,owner)).body.parsers.filter((p:any)=>!p.archived);
  assert.equal(active.length,1);
  assert.equal((await request('PATCH',`/api/parsers/${active[0].id}`,{archived:true},owner)).status,200);
 }
});
