import test from 'node:test';
import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import RunSelection from '../src/features/documents/RunSelection.js';
import {SourceQuotes} from '../src/features/documents/ExtractionSources.js';
import type {Evidence} from '../shared/types.js';
import assert from 'node:assert/strict';
import {readTemplateMutation,saveTemplateMutation,clearTemplateMutation,confirmTemplateMutation,submitTemplateMutation,findTemplateMutation,closeTemplateMutation,loadNativeTemplateSource,previewNativeTemplate,nativeDefinitionDigest,normalizedTemplateDefinition,type PendingTemplateMutation} from '../src/lib/native-template.js';
import type {TemplateDefinition,TemplateMutationResult} from '../shared/template-definitions.js';
import {pdfSha256} from '../src/lib/pdf-split.js';
import {pdfGeometryVersion} from '../shared/pdf-regions.js';

class MemoryStorage implements Storage{
 values=new Map<string,string>();get length(){return this.values.size;}key(index:number){return [...this.values.keys()][index]??null;}
 getItem(key:string){return this.values.get(key)??null;}setItem(key:string,value:string){this.values.set(key,value);}removeItem(key:string){this.values.delete(key);}clear(){this.values.clear();}
}
function environment(){const local=new MemoryStorage(),session=new MemoryStorage(),previous={local:Object.getOwnPropertyDescriptor(globalThis,'localStorage'),session:Object.getOwnPropertyDescriptor(globalThis,'sessionStorage'),fetch:globalThis.fetch};Object.defineProperty(globalThis,'localStorage',{configurable:true,value:local});Object.defineProperty(globalThis,'sessionStorage',{configurable:true,value:session});return{local,session,restore(){for(const[name,descriptor]of[['localStorage',previous.local],['sessionStorage',previous.session]]as const){if(descriptor)Object.defineProperty(globalThis,name,descriptor);else Reflect.deleteProperty(globalThis,name);}globalThis.fetch=previous.fetch;}};}
const ids=Array.from({length:8},(_,i)=>`${String(i+1).repeat(8)}-${String(i+1).repeat(4)}-4${String(i+1).repeat(3)}-8${String(i+1).repeat(3)}-${String(i+1).repeat(12)}`);
const scope={userId:ids[0],workspaceId:ids[1],parserId:ids[2]},actor={user:{id:scope.userId},workspace:{id:scope.workspaceId,role:'owner'}};
const definition:TemplateDefinition={kind:'native-pdf-region-v1',name:'  Invoice region  ',matchText:'Invoice',enabled:true,rules:[{field:'total',anchor:'  Invoice\n total  ',page:1,reference:{width:600,height:800,rotation:0},offset:{x:0.1,y:0,width:0.2,height:0.04}}]};
async function pending():Promise<PendingTemplateMutation>{return{version:1,...scope,requestId:ids[3],operation:'create',templateId:null,baseSchemaId:ids[4],baseRevision:null,definitionDigest:await nativeDefinitionDigest(definition)};}
function accepted(value:PendingTemplateMutation,changes:Partial<TemplateMutationResult['mutation']>={}):TemplateMutationResult{return{mutation:{requestId:value.requestId,state:'accepted',operation:value.operation,templateId:value.templateId||ids[5],acceptedRevision:value.baseRevision?value.baseRevision+1:1,currentRevision:value.baseRevision?value.baseRevision+1:1,deleted:false,replayed:true,...changes},template:value.operation==='delete'?null:{...normalizedTemplateDefinition(definition),id:value.templateId||ids[5],revision:value.baseRevision?value.baseRevision+1:1}};}
const closed=(value:PendingTemplateMutation):TemplateMutationResult=>({mutation:{requestId:value.requestId,state:'closed',operation:null,templateId:null,acceptedRevision:null,currentRevision:null,deleted:false,replayed:true},template:null});
const signal=()=>new AbortController().signal;
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}});

test('native save recovery persists only exact identity and prevents another pending write or clear',async()=>{const env=environment();try{const value=await pending();saveTemplateMutation({...value,anchor:'private source',filename:'private.pdf',bytes:'private',url:'private'} as PendingTemplateMutation);saveTemplateMutation({...value,anchor:'also excluded'} as PendingTemplateMutation);assert.deepEqual(readTemplateMutation(value),value);const stored=env.local.getItem(env.local.key(0)!)!;assert.ok(!stored.includes('private'));assert.deepEqual(Object.keys(JSON.parse(stored)).sort(),Object.keys(value).sort());assert.equal(readTemplateMutation({...scope,userId:ids[7]}),null);assert.throws(()=>saveTemplateMutation({...value,requestId:ids[6]}),/different template save/);assert.throws(()=>clearTemplateMutation({...value,requestId:ids[6]}),/newer template save/);clearTemplateMutation(value);assert.equal(env.local.length,0);env.local.setItem=()=>{throw new Error('disabled');};assert.throws(()=>saveTemplateMutation(value),/recovery information could not be stored/);}finally{env.restore();}});

test('accepted native definitions normalize anchor whitespace and ignore JSONB property order and snapshot extras',async()=>{const value=await pending(),result=accepted(value);const reversed=JSON.parse(JSON.stringify(result.template),(_key,input)=>input&&typeof input==='object'&&!Array.isArray(input)?Object.fromEntries(Object.entries(input).reverse()):input);result.template={...reversed,createdAt:'2026-09-20T00:00:00Z'};assert.equal((await confirmTemplateMutation(value,result)).mutation.templateId,ids[5]);assert.equal(result.template!.name,'Invoice region');assert.equal(result.template!.rules[0].anchor,'Invoice total');for(const patch of[{requestId:ids[6]},{operation:'update' as const},{currentRevision:0}])await assert.rejects(confirmTemplateMutation(value,{...result,mutation:{...result.mutation,...patch}}),/could not be verified|does not match/);await assert.rejects(confirmTemplateMutation(value,{...result,template:{...result.template!,name:'changed'}}),/definition does not match/);assert.equal((await confirmTemplateMutation(value,{...result,mutation:{...result.mutation,currentRevision:4}})).mutation.currentRevision,4);});

test('unknown receipt retains the nonce, repeat submits the same binding, and accepted replay avoids another mutation',async()=>{const env=environment();try{const value=await pending(),writes:any[]=[];let found=false;globalThis.fetch=async(input,init)=>{const path=String(input);assert.equal(new Headers(init?.headers).get('X-Workspace-Id'),scope.workspaceId);if(path==='/api/auth/me')return json(actor);if(path.includes('/requests/'))return found?json(accepted(value)):json({},404);writes.push(JSON.parse(String(init?.body)));return json(accepted(value),201);};assert.equal(await findTemplateMutation(value,()=>true,signal()),null);await submitTemplateMutation(value,definition,()=>true,signal());assert.equal(writes.length,1);assert.equal(writes[0].requestId,value.requestId);assert.equal(writes[0].name,'Invoice region');assert.equal(writes[0].rules[0].anchor,'Invoice total');assert.deepEqual(readTemplateMutation(value),value);found=true;await submitTemplateMutation(value,definition,()=>true,signal());assert.equal(writes.length,1);}finally{env.restore();}});

test('close recovers a save that already won, or verifies a permanent closed tombstone before allowing a new save',async()=>{const env=environment();try{const value=await pending();saveTemplateMutation(value);let result=accepted(value);globalThis.fetch=async(input,init)=>String(input)==='/api/auth/me'?json(actor):(assert.equal(init?.method,'POST'),json(result));assert.equal((await closeTemplateMutation(value,()=>true,signal())).mutation.state,'accepted');result=closed(value);assert.equal((await closeTemplateMutation(value,()=>true,signal())).mutation.state,'closed');assert.deepEqual(readTemplateMutation(value),value);await assert.rejects(confirmTemplateMutation(value,{...result,mutation:{...result.mutation,requestId:ids[6]}}),/does not match/);await assert.rejects(confirmTemplateMutation(value,{...result,mutation:{...result.mutation,templateId:ids[5]}}),/closed template request/);}finally{env.restore();}});

test('account, workspace, role and late view changes stop native saves before mutation',async()=>{const env=environment();try{const value=await pending();let writes=0;for(const invalid of[{...actor,user:{id:ids[7]}},{...actor,workspace:{...actor.workspace,role:'viewer'}}]){globalThis.fetch=async(_input,init)=>{if(init?.method==='POST')writes++;return json(invalid);};await assert.rejects(submitTemplateMutation(value,definition,()=>true,signal()),/account or permissions changed/);}env.session.setItem('folio.workspace',ids[7]);await assert.rejects(submitTemplateMutation(value,definition,()=>true,signal()),/workspace changed/);env.session.clear();let current=true;globalThis.fetch=async()=>{current=false;return json(actor);};await assert.rejects(submitTemplateMutation(value,definition,()=>current,signal()),/workspace changed/);assert.equal(writes,0);}finally{env.restore();}});

test('version conflicts and unconfirmed network results preserve the saved nonce and never expose raw transport details',async()=>{const env=environment();try{const value=await pending();let status=409;globalThis.fetch=async(input,init)=>{if(String(input)==='/api/auth/me')return json(actor);if(!init?.method)return json({},404);if(status===0)throw new Error('secret transport diagnostic');return json({message:'internal SQL detail'},status);};await assert.rejects(submitTemplateMutation(value,definition,()=>true,signal()),/saved template or parser fields changed/);assert.deepEqual(readTemplateMutation(value),value);status=0;await assert.rejects(submitTemplateMutation(value,definition,()=>true,signal()),error=>error instanceof Error&&error.message.includes('could not be confirmed')&&!error.message.includes('secret'));assert.deepEqual(readTemplateMutation(value),value);}finally{env.restore();}});

test('native geometry and original bytes must agree with source SHA, schema, page count and size',async()=>{const env=environment();try{const bytes=new TextEncoder().encode('%PDF controlled source'),sha256=await pdfSha256(bytes.buffer),source={documentId:ids[6],sha256,mimeType:'application/pdf' as const,pageCount:1,size:bytes.byteLength,name:'source.pdf'},geometry={version:pdfGeometryVersion,sourceSha256:sha256,pageCount:1,pages:[{page:1,width:600,height:800,rotation:0,reason:null,items:[{id:1,text:'Invoice total',rect:{x:0.1,y:0.1,width:0.2,height:0.04},separator:''}]}]};let change:any={},original=bytes;globalThis.fetch=async(input)=>{const path=String(input);if(path==='/api/auth/me')return json(actor);if(path.endsWith('/geometry'))return json({source,schemaId:ids[4],geometry,...change});if(path.endsWith('/original-url'))return json({url:`/api/documents/${ids[6]}/original`,external:false});return new Response(original,{headers:{'Content-Type':'application/octet-stream'}});};assert.deepEqual((await loadNativeTemplateSource(scope,{documentId:ids[6],sha256},ids[4],()=>true,signal())).bytes,bytes);for(const mutation of[{schemaId:ids[7]},{source:{...source,sha256:'f'.repeat(64)}},{source:{...source,size:bytes.byteLength+1}},{geometry:{...geometry,sourceSha256:'f'.repeat(64)}}]){change=mutation;await assert.rejects(loadNativeTemplateSource(scope,{documentId:ids[6],sha256},ids[4],()=>true,signal()),/does not match|could not be verified/);}change={};original=new TextEncoder().encode('%PDF changed source!!!');await assert.rejects(loadNativeTemplateSource(scope,{documentId:ids[6],sha256},ids[4],()=>true,signal()),/does not match/);}finally{env.restore();}});

test('draft preview uses a normalized definition and rejects a late mismatched draft or source response',async()=>{const env=environment();try{const source={documentId:ids[6],sha256:'a'.repeat(64),mimeType:'application/pdf' as const,pageCount:1,size:123,name:'source.pdf'},digest=await nativeDefinitionDigest(definition);let responseDigest=digest;globalThis.fetch=async(input,init)=>{if(String(input)==='/api/auth/me')return json(actor);const body=JSON.parse(String(init?.body));assert.equal(body.definition.name,'Invoice region');assert.equal(body.definition.rules[0].anchor,'Invoice total');return json({source,schemaId:ids[4],definitionDigest:responseDigest,selection:{outcome:'template'},candidates:[],availableSourceText:true,evaluatedWhileDisabled:!body.definition.enabled});};assert.equal((await previewNativeTemplate(scope,source,ids[4],definition,()=>true,signal())).definitionDigest,digest);responseDigest=await nativeDefinitionDigest({...definition,enabled:false});assert.equal((await previewNativeTemplate(scope,source,ids[4],{...definition,enabled:false},()=>true,signal())).evaluatedWhileDisabled,true);responseDigest='b'.repeat(64);await assert.rejects(previewNativeTemplate(scope,source,ids[4],definition,()=>true,signal()),/draft changed/);}finally{env.restore();}});


test('historical native evidence retains region navigation and its pinned definition after current template deletion',async()=>{
 const evidence:Evidence={page:2,text:'0',source:'matched-region',region:{version:pdfGeometryVersion,sourceSha256:'a'.repeat(64),rect:{x:0.2,y:0.3,width:0.1,height:0.05},anchor:{text:'Total',capturedText:'Total due',rect:{x:0.1,y:0.3,width:0.05,height:0.05},itemIds:[1]},itemIds:[2]}};
 let selected:Evidence|undefined;const quotes=SourceQuotes({items:[evidence],onPage:(page,value)=>{assert.equal(page,2);selected=value;}});quotes.props.children[0].props.onClick();assert.equal(selected,evidence);assert.match(renderToStaticMarkup(quotes),/Native region source/);
 const digest=await nativeDefinitionDigest(definition),html=renderToStaticMarkup(createElement(RunSelection,{selection:{outcome:'template',policy:'complete-regions-v1',template:{id:ids[5],name:'Pinned native',kind:'native-pdf-region-v1',revision:3,fieldCount:1,tieCount:1,geometryVersion:pdfGeometryVersion}} as any,templateSnapshot:{version:'folio-template-snapshot-v1',definitionDigest:digest,geometryVersion:pdfGeometryVersion,template:{...normalizedTemplateDefinition(definition),id:ids[5],revision:3}}}));
 assert.match(html,/Native PDF region template/);assert.match(html,/exact definition pinned to this run/);assert.ok(html.includes(digest));assert.match(html,/Invoice total/);assert.match(html,/&quot;offset&quot;/);assert.match(html,/Revision 3/);
});
