import test from 'node:test';
import assert from 'node:assert/strict';
import {readSavedSplitSuggestion,saveSplitSuggestion,clearSplitSuggestion,confirmSplitSuggestion,requestSplitSuggestion,findSplitSuggestion,readSplitSuggestionSource,createSuggestedSplit,type SavedSplitSuggestion} from '../src/lib/split-suggestions.js';
import {pdfSha256,savePendingPdfSplit,readPendingPdfSplit,confirmPdfSplitReceipt,uploadPdfSplit} from '../src/lib/pdf-split.js';
import {saveStoredPdfSplit,readStoredPdfSplit,findStoredPdfSplit} from '../src/lib/stored-pdf-split.js';
import type {SplitSuggestion} from '../shared/split-suggestions.js';

class MemoryStorage implements Storage{values=new Map<string,string>();get length(){return this.values.size;}key(i:number){return [...this.values.keys()][i]??null;}getItem(k:string){return this.values.get(k)??null;}setItem(k:string,v:string){this.values.set(k,v);}removeItem(k:string){this.values.delete(k);}clear(){this.values.clear();}}
const scope={userId:'11111111-1111-4111-8111-111111111111',workspaceId:'22222222-2222-4222-8222-222222222222',parserId:'33333333-3333-4333-8333-333333333333'},id='44444444-4444-4444-8444-444444444444',requestId='55555555-5555-4555-8555-555555555555',createId='66666666-6666-4666-8666-666666666666',documentId='77777777-7777-4777-8777-777777777777';
const base:SavedSplitSuggestion={version:1,...scope,sourceDocumentId:null,requestId,sha256:'a'.repeat(64),mimeType:'application/pdf'};
const actor={user:{id:scope.userId},workspace:{id:scope.workspaceId,role:'owner'}};
const now=new Date().toISOString();
const job:SplitSuggestion={id,requestId,parserId:scope.parserId,sourceDocumentId:null,sourceName:'Synthetic source.pdf',sourceSha256:base.sha256,sourceMimeType:'application/pdf',pageCount:3,state:'ready',attempts:1,maxAttempts:3,createdAt:now,updatedAt:now,expiresAt:new Date(Date.now()+3600000).toISOString(),startPages:[1,3],ranges:[{start:1,end:2},{start:3,end:3}],error:null,model:'controlled',promptVersion:'controlled-v1',tokenUsage:{input_tokens:1},costUsd:0,acceptedSplitId:null,confirmedRequestId:null,confirmedOptions:null,creationClosed:false};
const options={mode:'ranges' as const,ranges:[{start:2,end:3}]},pending={version:1 as const,...scope,requestId:createId,sha256:base.sha256,options,suggestionId:id};
const receipt={split:{id:'88888888-8888-4888-8888-888888888888',requestId:createId,parserId:scope.parserId,sourceName:'Synthetic source.pdf',sourcePageCount:3,selectedPages:2,childCount:1,sourceAvailable:true,createdAt:now,aiSuggestion:{suggestionId:id,requestId,sourceSha256:base.sha256,sourcePageCount:3,model:'controlled',promptVersion:'controlled-v1',startPages:[1,3],confirmedRanges:options.ranges,tokenUsage:{},costUsd:0}},documents:[{id:'99999999-9999-4999-8999-999999999999',jobId:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',index:1,name:'child.pdf',pageCount:2,originalPageStart:2,originalPageEnd:3,available:true}],replayed:false};
function environment(){const local=new MemoryStorage(),session=new MemoryStorage(),old={local:Object.getOwnPropertyDescriptor(globalThis,'localStorage'),session:Object.getOwnPropertyDescriptor(globalThis,'sessionStorage'),fetch:globalThis.fetch};Object.defineProperty(globalThis,'localStorage',{configurable:true,value:local});Object.defineProperty(globalThis,'sessionStorage',{configurable:true,value:session});return{local,session,restore(){for(const[name,descriptor]of [['localStorage',old.local],['sessionStorage',old.session]]as const){if(descriptor)Object.defineProperty(globalThis,name,descriptor);else Reflect.deleteProperty(globalThis,name);}globalThis.fetch=old.fetch;}};}
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{'content-type':'application/json'}}),signal=()=>new AbortController().signal;

test('suggestion recovery stores only minimal source identity and preserves another unresolved request',()=>{const env=environment();try{
 saveSplitSuggestion({...base,bytes:'secret',sourceName:'secret',modelText:'secret',url:'secret',token:'secret'}as SavedSplitSuggestion);assert.deepEqual(readSavedSplitSuggestion(scope,null),base);assert.ok(![...env.local.values.values()].join('').includes('secret'));
 assert.equal(readSavedSplitSuggestion({...scope,userId:id},null),null);assert.equal(readSavedSplitSuggestion(scope,documentId),null);assert.throws(()=>saveSplitSuggestion({...base,requestId:createId}),/Another saved/);saveSplitSuggestion({...base,suggestionId:id});assert.equal(readSavedSplitSuggestion(scope,null)?.suggestionId,id);saveSplitSuggestion(base);assert.equal(readSavedSplitSuggestion(scope,null)?.suggestionId,id);assert.throws(()=>saveSplitSuggestion({...base,suggestionId:createId}),/Another saved/);assert.throws(()=>clearSplitSuggestion({...base,requestId:createId}),/newer AI/);clearSplitSuggestion(base);assert.equal(env.local.length,0);
 }finally{env.restore();}});

test('storage failure refuses before any AI request or provider source transfer',async()=>{const env=environment();try{env.local.setItem=()=>{throw new Error('disabled');};let calls=0;globalThis.fetch=async()=>{calls++;throw new Error('unexpected');};await assert.rejects(requestSplitSuggestion(base,null,()=>true,signal()),/Recovery information could not be saved/);assert.equal(calls,0);}finally{env.restore();}});

test('only matching source, requester binding, MIME and full-coverage model ranges are accepted',()=>{
 assert.equal(confirmSplitSuggestion(scope,job,base),job);assert.deepEqual(confirmSplitSuggestion(scope,{...job,ranges:job.ranges!.map(({start,end})=>({end,start}))},base).ranges,job.ranges);for(const change of[{sourceSha256:'b'.repeat(64)},{sourceMimeType:'image/tiff'},{sourceDocumentId:documentId},{requestId:createId},{id:createId},{ranges:[{start:2,end:3}]},{startPages:[1,1]},{pageCount:31},{creationClosed:undefined},{acceptedSplitId:createId}])assert.throws(()=>confirmSplitSuggestion(scope,{...job,...change}as SplitSuggestion,{...base,suggestionId:id}),/does not match/);
});

test('unknown lookup remains unknown; queued replay cannot automatically enqueue another request',async()=>{const env=environment();try{let posts=0;globalThis.fetch=async(input,init)=>{if(init?.method==='POST')posts++;return String(input)==='/api/auth/me'?json(actor):json({suggestion:{...job,state:'queued',startPages:null,ranges:null}});};assert.equal((await requestSplitSuggestion(base,null,()=>true,signal())).state,'queued');assert.equal(posts,0);globalThis.fetch=async(input)=>String(input)==='/api/auth/me'?json(actor):json({message:'not found'},404);assert.equal(await findSplitSuggestion(base,()=>true,signal()),null);}finally{env.restore();}});

test('explicit multipart request binds immutable file hash and never creates documents',async()=>{const env=environment();try{
 const file=new File(['%PDF synthetic'],'private.pdf',{type:'application/pdf'}),value={...base,sha256:await pdfSha256(await file.arrayBuffer())};let writes=0;
 globalThis.fetch=async(input,init)=>{const path=String(input);if(path==='/api/auth/me')return json(actor);if(path.includes('/requests/'))return json({},404);if(path==='/api/uploads/config')return json({strategy:'multipart',maxBytes:10*1024*1024});assert.equal(path,`/api/parsers/${scope.parserId}/split-suggestions`);assert.equal(init?.method,'POST');writes++;assert.ok(init.body instanceof FormData);assert.equal(init.body.get('requestId'),requestId);assert.equal(init.body.get('sourceSha256'),value.sha256);assert.equal(readSavedSplitSuggestion(scope,null)?.requestId,requestId);return json({suggestion:{...job,sourceSha256:value.sha256,state:'queued',startPages:null,ranges:null}},202);};
 assert.equal((await requestSplitSuggestion(value,file,()=>true,signal())).state,'queued');assert.equal(writes,1);assert.equal(readSavedSplitSuggestion(scope,null)?.suggestionId,id);
 }finally{env.restore();}});

test('signed suggestion retries interrupted staging with its original UUID and finalizes without page reservation',async()=>{const env=environment();try{
 const file=new File(['%PDF synthetic'],'private.pdf',{type:'application/pdf'}),value={...base,sha256:await pdfSha256(await file.arrayBuffer())};let reserved=false,puts=0,finalizes=0;const requests:string[]=[];
 globalThis.fetch=async(input,init)=>{const path=String(input);requests.push(`${init?.method||'GET'} ${path}`);if(path==='/api/auth/me')return json(actor);if(path.includes('/requests/'))return reserved?json({suggestion:{...job,sourceSha256:value.sha256,state:'uploading',pageCount:null,startPages:null,ranges:null}}):json({},404);if(path==='/api/uploads/config')return json({strategy:'signed',maxBytes:10*1024*1024});
  if(path.endsWith('/split-suggestions')){reserved=true;const body=JSON.parse(String(init?.body));assert.equal(body.requestId,requestId);assert.equal(body.sourceSha256,value.sha256);assert.ok(!('options'in body));return json({suggestion:{...job,sourceSha256:value.sha256,state:'uploading',pageCount:null,startPages:null,ranges:null},upload:{url:'https://controlled.supabase.co/object',method:'PUT',headers:{'Content-Type':'application/octet-stream','x-upsert':'false'},expiresAt:job.expiresAt}},202);}
  if(init?.method==='PUT'){puts++;assert.equal(init.credentials,'omit');assert.equal(init.referrerPolicy,'no-referrer');if(puts===1)throw new TypeError('simulated interruption');return new Response(null,{status:409});}
  if(path.endsWith('/finalize')){finalizes++;return json({suggestion:{...job,sourceSha256:value.sha256,state:'queued',startPages:null,ranges:null}},202);}throw new Error('Unexpected request');
 };
 await assert.rejects(requestSplitSuggestion(value,file,()=>true,signal()),/source transfer could not be confirmed/);assert.equal(readSavedSplitSuggestion(scope,null)?.suggestionId,id);assert.equal((await requestSplitSuggestion(value,file,()=>true,signal())).state,'queued');assert.equal(puts,2);assert.equal(finalizes,1);assert.ok(!requests.some(p=>p.startsWith('POST ')&&p.includes('/uploads')||p.endsWith('/create')));
 }finally{env.restore();}});

test('account or late source replacement stops reservation and signed PUT continuation',async()=>{const env=environment();try{
 const file=new File(['%PDF source'],'source.pdf'),value={...base,sha256:await pdfSha256(await file.arrayBuffer())};let writes=0,current=true;
 globalThis.fetch=async(input,init)=>{if(init?.method==='POST'||init?.method==='PUT')writes++;if(String(input)==='/api/auth/me')return json({...actor,user:{id}});return json({});};await assert.rejects(requestSplitSuggestion(value,file,()=>true,signal()),/account or permissions/);assert.equal(writes,0);
 globalThis.fetch=async(input,init)=>{if(init?.method==='POST'||init?.method==='PUT')writes++;if(String(input)==='/api/auth/me')return json(actor);if(String(input).includes('/requests/'))return json({},404);current=false;return json({strategy:'signed',maxBytes:10*1024*1024});};await assert.rejects(requestSplitSuggestion(value,file,()=>current,signal()),/source changed/);assert.equal(writes,0);
 }finally{env.restore();}});

test('private source restoration verifies bytes and MIME before creating an in-memory file',async()=>{const env=environment();try{
 const bytes=new TextEncoder().encode('%PDF fixture'),digest=await pdfSha256(bytes.buffer),value={...job,sourceSha256:digest};globalThis.fetch=async(input)=>String(input)==='/api/auth/me'?json(actor):new Response(bytes,{headers:{'content-type':'application/pdf','X-Folio-Source-Sha256':digest}});const restored=await readSplitSuggestionSource(scope,value,()=>true,signal());assert.equal(restored.file.type,'application/pdf');assert.deepEqual(restored.bytes,bytes);assert.equal(env.local.length,0);
 for(const change of[{sourceSha256:base.sha256},{sourceMimeType:'image/tiff' as const}])await assert.rejects(readSplitSuggestionSource(scope,{...value,...change},()=>true,signal()),/could not be verified/);
 }finally{env.restore();}});

test('AI provenance remains frozen with edited ranges and cannot fall through manual submission',async()=>{const env=environment();try{
 savePendingPdfSplit({...pending,sourceName:'never store',modelText:'never store'}as typeof pending);assert.deepEqual(readPendingPdfSplit(scope.workspaceId,scope.parserId,scope.userId),pending);assert.ok(![...env.session.values.values()].join('').includes('never store'));
 assert.equal(confirmPdfSplitReceipt(pending,receipt).split.id,receipt.split.id);assert.equal(confirmPdfSplitReceipt(pending,{...receipt,split:{...receipt.split,aiSuggestion:{...receipt.split.aiSuggestion,confirmedRanges:options.ranges.map(({start,end})=>({end,start}))}}}).split.id,receipt.split.id);for(const change of[{aiSuggestion:undefined},{aiSuggestion:{...receipt.split.aiSuggestion,suggestionId:requestId}},{aiSuggestion:{...receipt.split.aiSuggestion,sourceSha256:'b'.repeat(64)}},{aiSuggestion:{...receipt.split.aiSuggestion,confirmedRanges:job.ranges}}])assert.throws(()=>confirmPdfSplitReceipt(pending,{...receipt,split:{...receipt.split,...change}}as any),/could not be confirmed/);
 await assert.rejects(uploadPdfSplit(pending,new File(['x'],'x.pdf'),()=>{},()=>true),/saved AI suggestion/);
 let calls=0;globalThis.fetch=async(input,init)=>{if(String(input)==='/api/auth/me')return json(actor);calls++;assert.equal(String(input),`/api/parsers/${scope.parserId}/split-suggestions/${id}/create`);assert.deepEqual(JSON.parse(String(init?.body)),{requestId:createId,options});assert.equal(readPendingPdfSplit(scope.workspaceId,scope.parserId,scope.userId)?.suggestionId,id);return json(receipt,202);};assert.equal((await createSuggestedSplit(pending,()=>true,signal())).split.id,receipt.split.id);assert.equal(calls,1);
 }finally{env.restore();}});

test('stored AI rejection must carry matching suggestion provenance before permitting a new operation',async()=>{const env=environment();try{
 const value={...pending,sourceDocumentId:documentId,savedAt:Date.now()};saveStoredPdfSplit(value);assert.equal(readStoredPdfSplit(scope,documentId)?.suggestionId,id);assert.throws(()=>saveStoredPdfSplit({...value,suggestionId:undefined}),/Another saved/);
 const rejected={id:receipt.split.id,requestId:createId,parserId:scope.parserId,sourceDocumentId:documentId,sourceSha256:base.sha256,options,code:'pdf_split_validation_failed',reason:'unsupported_pdf',message:'The source cannot be split.',aiSuggestion:receipt.split.aiSuggestion};globalThis.fetch=async(input)=>String(input)==='/api/auth/me'?json(actor):json({rejected});assert.ok('rejected'in(await findStoredPdfSplit(value,()=>true))!);
 globalThis.fetch=async(input)=>String(input)==='/api/auth/me'?json(actor):json({rejected:{...rejected,aiSuggestion:undefined}});await assert.rejects(findStoredPdfSplit(value,()=>true),/does not match/);assert.equal(readStoredPdfSplit(scope,documentId)?.requestId,createId);
 }finally{env.restore();}});
