import {useState} from 'react';
import {Link,useNavigate,useSearchParams} from 'react-router-dom';
import {ArrowRight,FileText,Table2,Check} from 'lucide-react';
import {post,useAction} from '../../lib/api';
import {useSession} from '../../lib/session';
import {Button,Field,Notice} from '../../components/ui';
export default function Auth({signUp=false}:{signUp?:boolean}){
  const [name,setName]=useState(''),[workspaceName,setWorkspaceName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState('');
  const action=useAction(),session=useSession(),navigate=useNavigate();const [params]=useSearchParams();
  const requestedNext=params.get('next')||'';
  const next=(requestedNext==='/app'||requestedNext.startsWith('/app/')||requestedNext.startsWith('/app?'))&&!requestedNext.includes('\\')?requestedNext:'';
  const otherAuthRoute=(signUp?'/sign-in':'/sign-up')+(params.size?`?${params.toString()}`:'');
  return <div className="auth-page"><header><Link to="/" className="wordmark">Folio</Link><Link className="link" to={otherAuthRoute}>{signUp?'Already have an account? Sign in':'Create an account'}</Link></header><main className="auth-main"><div className="auth-story"><h1>A little less paperwork.<br/><span>A lot more possibility.</span></h1><p>Your documents, fields and workflows together in one workspace.</p><div className="auth-flow"><FileText/><span/><Table2/><span/><Check/></div><p className="script-note">Let’s make room for better work.</p><p className="small">Local development workspace. Accounts and documents are saved on this installation.</p></div><section className="auth-form"><h2>{signUp?'Start your workspace':'Welcome back.'}</h2><p>{signUp?'Create an account and extract your first document.':'Sign in to pick up where you left off.'}</p><form onSubmit={e=>{e.preventDefault();void action.run(async()=>{const result=await post(signUp?'/api/auth/register':'/api/auth/login',signUp?{name,workspaceName,email,password}:{email,password});sessionStorage.setItem('folio.workspace',result.workspace.id);await session.refresh();navigate(next||(signUp?`/app/parsers/new${params.get('sample')?'?sample=invoice':''}`:'/app'),{replace:true});},'');}}><Notice error={action.error}/>{signUp&&<><Field label="Your name"><input required autoComplete="name" value={name} onChange={e=>setName(e.target.value)} maxLength={100}/></Field><Field label="Workspace name"><input required value={workspaceName} onChange={e=>setWorkspaceName(e.target.value)} placeholder="Your company or team" maxLength={100}/></Field></>}<Field label="Email address"><input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="Password" hint={signUp?'Use at least 10 characters.':undefined}><input required type="password" autoComplete={signUp?'new-password':'current-password'} minLength={10} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/></Field><Button disabled={action.busy} type="submit">{action.busy?'Please wait…':signUp?'Create workspace':'Sign in'}<ArrowRight/></Button></form><p className="small auth-footer">{signUp?'Private local accounts. Email verification and recovery are not enabled for this installation.':'Use the account created on this installation. Remote Parseur accounts are separate.'}</p></section></main></div>;
}
