import type {FastifyInstance} from 'fastify';
import {z} from 'zod';
import {randomUUID} from 'node:crypto';
import {adminPool,transaction,badRequest,camel} from './db.js';
import {hashPassword,verifyPassword,createSession,requireActor,hashToken,requireSession} from './auth.js';
import {config,defaultPlan} from './config.js';
import {acceptsPreviewInvite} from './preview.js';
const credentials=z.object({email:z.string().email().max(254).transform(v=>v.trim().toLowerCase()),password:z.string().min(10).max(128)});
const attempts=new Map<string,{count:number,until:number}>();
function limit(ip:string){const now=Date.now();for(const [key,v]of attempts)if(v.until<now)attempts.delete(key);const item=attempts.get(ip)||{count:0,until:now+15*60000};item.count++;attempts.set(ip,item);if(item.count>30)badRequest('Too many authentication attempts. Try again in 15 minutes.',429);}
function authOrigin(origin:string|undefined){if(origin&&origin!==config.origin)badRequest('Request origin is not allowed',403);}
export async function sessionResponse(userId:string,workspaceId:string){const user=(await adminPool.query('select id,email,name,created_at from users where id=$1',[userId])).rows[0];const workspaces=(await adminPool.query('select w.*,m.role from memberships m join workspaces w on w.id=m.workspace_id where m.user_id=$1 order by w.created_at',[userId])).rows.map(camel);return {user:camel(user),workspace:workspaces.find(w=>w.id===workspaceId),workspaces};}
export async function registerAuth(app:FastifyInstance){
app.post('/api/auth/register',async(req,reply)=>{authOrigin(req.headers.origin);limit(req.ip);const body=credentials.extend({name:z.string().trim().min(1).max(100),workspaceName:z.string().trim().min(1).max(100),inviteCode:z.string().max(256).optional()}).parse(req.body);if(!acceptsPreviewInvite(body.inviteCode))badRequest('An invite code is required for this test preview.',403);const passwordHash=await hashPassword(body.password);const ids=await transaction(adminPool,async c=>{if((await c.query('select 1 from users where email=$1',[body.email])).rowCount)badRequest('This email is already registered',409);const {rows:[u]}=await c.query('insert into users(email,name,password_hash) values($1,$2,$3) returning id',[body.email,body.name,passwordHash]);const {rows:[w]}=await c.query('insert into workspaces(name,slug,plan) values($1,$2,$3) returning id',[body.workspaceName,`${body.workspaceName.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${randomUUID().slice(0,8)}`,JSON.stringify(defaultPlan)]);await c.query('insert into memberships(workspace_id,user_id,role) values($1,$2,$3)',[w.id,u.id,'owner']);return {userId:u.id,workspaceId:w.id};});await createSession(reply,ids.userId,ids.workspaceId);reply.code(201);return sessionResponse(ids.userId,ids.workspaceId);});
app.post('/api/auth/login',async(req,reply)=>{authOrigin(req.headers.origin);limit(req.ip);const body=credentials.parse(req.body);const user=(await adminPool.query('select * from users where email=$1',[body.email])).rows[0];const encoded=user?.password_hash||'da53db997e44c565658e207d0b21eaa77:'+ '0'.repeat(128);if(!await verifyPassword(body.password,encoded)||!user)badRequest('Email or password is incorrect',401);const member=(await adminPool.query('select workspace_id from memberships where user_id=$1 order by created_at limit 1',[user.id])).rows[0];if(!member)badRequest('No active workspace membership',403);await createSession(reply,user.id,member.workspace_id);return sessionResponse(user.id,member.workspace_id);});
app.get('/api/auth/me',async req=>{const actor=await requireActor(req);requireSession(actor);return sessionResponse(actor.userId,actor.workspaceId);});
app.post('/api/auth/logout',async(req,reply)=>{const actor=await requireActor(req);requireSession(actor);await adminPool.query('delete from sessions where token_hash=$1',[hashToken(req.cookies.folio_session!)]);reply.clearCookie('folio_session',{path:'/'});return {ok:true};});
app.get('/api/workspaces',async req=>{const a=await requireActor(req);requireSession(a);return {workspaces:(await sessionResponse(a.userId,a.workspaceId)).workspaces};});
app.post('/api/workspaces',async req=>{const a=await requireActor(req);requireSession(a);const body=z.object({name:z.string().trim().min(1).max(100)}).parse(req.body);const w=await transaction(adminPool,async c=>{const {rows:[w]}=await c.query('insert into workspaces(name,slug,plan) values($1,$2,$3) returning *',[body.name,randomUUID(),JSON.stringify(defaultPlan)]);await c.query('insert into memberships(workspace_id,user_id,role) values($1,$2,$3)',[w.id,a.userId,'owner']);return w;});return {workspace:{...camel(w),role:'owner'}};});
app.post('/api/workspaces/:id/select',async req=>{const a=await requireActor(req);requireSession(a);const id=z.object({id:z.string().uuid()}).parse(req.params).id;if(!(await adminPool.query('select 1 from memberships where workspace_id=$1 and user_id=$2',[id,a.userId])).rowCount)badRequest('Workspace access denied',403);await adminPool.query('update sessions set workspace_id=$1 where token_hash=$2',[id,hashToken(req.cookies.folio_session!)]);return sessionResponse(a.userId,id);});
app.post('/api/auth/password',async req=>{const a=await requireActor(req);requireSession(a);const body=z.object({currentPassword:z.string().max(128),newPassword:z.string().min(10).max(128)}).parse(req.body);const user=(await adminPool.query('select password_hash from users where id=$1',[a.userId])).rows[0];if(!await verifyPassword(body.currentPassword,user.password_hash))badRequest('Current password is incorrect',400);const hash=await hashPassword(body.newPassword);await transaction(adminPool,async c=>{await c.query('update users set password_hash=$1 where id=$2',[hash,a.userId]);await c.query('delete from sessions where user_id=$1 and token_hash<>$2',[a.userId,hashToken(req.cookies.folio_session!)]);});return {ok:true};});
}
