import '@fastify/multipart';
import type {FastifyInstance,FastifyRequest} from 'fastify';
import {z} from 'zod';
import {randomUUID} from 'node:crypto';
import {requireActor,editors} from './auth.js';
import {withWorkspace,camel,badRequest,notFound,audit} from './db.js';
import {addDocument} from './intake.js';
import {privateStorage,readStoredObject,validateStorageKey,safeDownloadName} from './storage.js';
import {registerUploadRoutes} from './upload-routes.js';
import {presets} from '../../shared/presets.js';
import {config} from './config.js';
import {resolveRun,publicRun} from './runs.js';
import {documentLifecycle} from './document-events.js';
import {validateValues} from './schema.js';
import {purgeDocument,deleteStoredFile} from './retention.js';
import type {Actor} from '../../shared/types.js';
const idFrom=(p:unknown)=>z.object({id:z.string().uuid()}).parse(p).id;
const listQuery=z.object({page:z.coerce.number().int().min(1).max(100000).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20),search:z.string().max(150).default(''),status:z.enum(['received','queued','processing','needs_review','processed','exporting','exported','failed']).optional(),parserId:z.string().uuid().optional()});
export async function reprocessDocument(a:Actor,id:string){return withWorkspace(a.workspaceId,async c=>{await c.query('select pg_advisory_xact_lock(hashtextextended($1,0))',[a.workspaceId]);const {rows:[doc]}=await c.query('select d.*,p.active_schema_id,p.mode,p.instructions,p.locale,p.timezone from documents d join parsers p on p.id=d.parser_id where d.id=$1 and d.workspace_id=$2 for update of d',[id,a.workspaceId]);if(!doc)notFound();if((await c.query("select 1 from jobs where document_id=$1 and state in('queued','processing')",[id])).rowCount)badRequest('This document is already queued or processing',409);const {rows:[w]}=await c.query('select plan from workspaces where id=$1',[a.workspaceId]);const {rows:[usage]}=await c.query("select coalesce(sum(pages),0)::integer used from usage_ledger where workspace_id=$1 and created_at>=date_trunc('month',now())",[a.workspaceId]);if(usage.used+doc.page_count>w.plan.monthlyPages)badRequest('Monthly page quota reached',429);const templates=(await c.query('select * from templates where parser_id=$1 order by created_at,id',[doc.parser_id])).rows;const {rows:[job]}=await c.query('insert into jobs(workspace_id,document_id,schema_version_id,config) values($1,$2,$3,$4) returning *',[a.workspaceId,id,doc.active_schema_id,JSON.stringify({mode:doc.mode,instructions:doc.instructions,locale:doc.locale,timezone:doc.timezone,templates})]);await c.query("update documents set status='queued',error=null,updated_at=now() where id=$1",[id]);await c.query('insert into usage_ledger(workspace_id,document_id,event,pages,idempotency_key) values($1,$2,$3,$4,$5)',[a.workspaceId,id,'reprocess',doc.page_count,`reprocess:${job.id}`]);await audit(c,a.workspaceId,a.userId,'document.reprocessed',id,{jobId:job.id});return {job:camel(job)};});}
export async function deleteDocument(a:Actor,id:string){const doc=await withWorkspace(a.workspaceId,async c=>{const doc=await purgeDocument(c,a.workspaceId,id);if(!doc)notFound();await audit(c,a.workspaceId,a.userId,'document.deleted',id);return doc;});const storageDeletion=await deleteStoredFile(a.workspaceId,doc.storage_key);return {ok:true,storageDeletion};}
export async function registerDocuments(app:FastifyInstance){
await registerUploadRoutes(app);
const list=async(req:FastifyRequest)=>{const a=await requireActor(req,{scope:'documents:read'});const q=listQuery.parse(req.query);const scoped=(req.params as any)?.id;if(scoped)q.parserId=z.string().uuid().parse(scoped);return withWorkspace(a.workspaceId,async c=>{const where='workspace_id=$1 and ($2::uuid is null or parser_id=$2) and ($3::text is null or status=$3) and name ilike $4';const vals=[a.workspaceId,q.parserId||null,q.status||null,`%${q.search.replace(/[\\%_]/g,'\\$&')}%`];const {rows:[count]}=await c.query(`select count(*)::integer total from documents where ${where}`,vals);const {rows}=await c.query(`select d.*,p.name parser_name from documents d join parsers p on p.id=d.parser_id where d.workspace_id=$1 and ($2::uuid is null or d.parser_id=$2) and ($3::text is null or d.status=$3) and d.name ilike $4 order by d.created_at desc,d.id limit $5 offset $6`,[...vals,q.pageSize,(q.page-1)*q.pageSize]);return {documents:rows.map(camel),total:count.total,page:q.page,pageSize:q.pageSize};});};
app.get('/api/documents',list);app.get('/api/parsers/:id/documents',list);
app.post('/api/parsers/:id/documents',async(req,reply)=>{const a=await requireActor(req,{roles:editors,scope:'documents:write'}),id=idFrom(req.params);const files=[];for await(const part of req.parts({limits:{fileSize:config.maxBytes,files:20,fields:10,parts:30}})){if(part.type!=='file')continue;const buffer=await part.toBuffer();if(part.file.truncated)badRequest('File exceeds 10 MB limit',413);files.push({buffer,filename:part.filename,mimeType:part.mimetype});}if(!files.length)badRequest('Select at least one file');const results=[];const key=typeof req.headers['idempotency-key']==='string'?req.headers['idempotency-key']:undefined;for(const [i,file] of files.entries()){try{results.push(await addDocument(a,id,file.buffer,file.filename,file.mimeType,key?`${key}:${i}`:undefined));}catch(e){if(files.length===1)throw e;results.push({name:file.filename,error:e instanceof Error?e.message:'Upload failed'});}}reply.code(202);return results.length===1?{...results[0],results}: {results};});
app.post('/api/parsers/:id/sample',async(req,reply)=>{const a=await requireActor(req,{roles:editors,scope:'documents:write'}),id=idFrom(req.params);const parser=await withWorkspace(a.workspaceId,async c=>(await c.query('select use_case from parsers where id=$1 and workspace_id=$2',[id,a.workspaceId])).rows[0]);if(!parser)notFound();const p=presets[parser.use_case]||presets.custom;reply.code(202);return addDocument(a,id,Buffer.from(p.sample),`synthetic-${parser.use_case}-sample.txt`,'text/plain');});
app.get('/api/documents/:id',async req=>{const a=await requireActor(req,{scope:'documents:read'}),id=idFrom(req.params);return withWorkspace(a.workspaceId,async c=>{const doc=(await c.query('select * from documents where id=$1 and workspace_id=$2',[id,a.workspaceId])).rows[0];if(!doc)notFound();const parser=(await c.query('select * from parsers where id=$1',[doc.parser_id])).rows[0];const ids=(await c.query('select id from extraction_runs where document_id=$1 order by created_at desc,id desc',[id])).rows;const runs=[];for(const r of ids)runs.push(publicRun(await resolveRun(c,r.id)));const jobs=(await c.query('select id,state,attempts,max_attempts,error,available_at,created_at,updated_at from jobs where document_id=$1 order by created_at desc',[id])).rows.map(camel);return {document:camel(doc),parser:camel(parser),runs,jobs,lifecycle:await documentLifecycle(c,a.workspaceId,id)};});});
app.get('/api/documents/:id/original',async(req,reply)=>{const a=await requireActor(req,{scope:'documents:read'}),id=idFrom(req.params);const doc=await withWorkspace(a.workspaceId,async c=>(await c.query('select * from documents where id=$1 and workspace_id=$2',[id,a.workspaceId])).rows[0]);if(!doc)notFound();validateStorageKey(doc.storage_key,a.workspaceId);const storage=privateStorage();if(storage.signDownload){reply.header('Cache-Control','private, no-store').header('Referrer-Policy','no-referrer');return reply.redirect(await storage.signDownload(doc.storage_key,doc.name));}const bytes=await readStoredObject(doc.storage_key).catch(()=>notFound('Original file is unavailable'));const inline=['application/pdf','image/png','image/jpeg','text/plain'].includes(doc.mime_type);reply.header('Content-Type',inline?`${doc.mime_type}${doc.mime_type==='text/plain'?'; charset=utf-8':''}`:'application/octet-stream').header('Content-Disposition',`${inline?'inline':'attachment'}; filename*=UTF-8''${encodeURIComponent(doc.name)}`).header('Cache-Control','private, no-store').header('X-Content-Type-Options','nosniff').header('Content-Security-Policy',"sandbox; default-src 'none'");return reply.send(bytes);});
app.get('/api/documents/:id/original-url',async req=>{const a=await requireActor(req,{scope:'documents:read'}),id=idFrom(req.params);const doc=await withWorkspace(a.workspaceId,async c=>(await c.query('select storage_key,name from documents where id=$1 and workspace_id=$2',[id,a.workspaceId])).rows[0]);if(!doc)notFound();validateStorageKey(doc.storage_key,a.workspaceId);const storage=privateStorage();return storage.signDownload?{url:await storage.signDownload(doc.storage_key,doc.name),external:true}:{url:`/api/documents/${id}/original`,external:false};});
app.post('/api/documents/:id/reprocess',async req=>{const a=await requireActor(req,{roles:editors,scope:'documents:write'});return reprocessDocument(a,idFrom(req.params));});
app.delete('/api/documents/:id',async req=>{const a=await requireActor(req,{roles:editors,scope:'documents:write'});return deleteDocument(a,idFrom(req.params));});
app.post('/api/documents/bulk',async req=>{const a=await requireActor(req,{roles:editors,scope:'documents:write'});const b=z.object({ids:z.array(z.string().uuid()).min(1).max(100),action:z.enum(['delete','reprocess'])}).parse(req.body);const results=[];for(const id of [...new Set(b.ids)]){try{results.push({id,...await(b.action==='delete'?deleteDocument(a,id):reprocessDocument(a,id))});}catch(e){results.push({id,error:e instanceof Error?e.message:'Action failed'});}}return {results};});
app.get('/api/jobs/:id',async req=>{const a=await requireActor(req,{scope:'documents:read'});return withWorkspace(a.workspaceId,async c=>{const job=(await c.query('select id,document_id,state,attempts,max_attempts,error,available_at,created_at,updated_at from jobs where id=$1',[idFrom(req.params)])).rows[0];if(!job)notFound();return {job:camel(job)};});});
app.get('/api/runs/:id',async req=>{const a=await requireActor(req,{scope:'results:read'});return withWorkspace(a.workspaceId,async c=>({run:publicRun(await resolveRun(c,idFrom(req.params)))}));});
app.post('/api/runs/:id/corrections',async req=>{const a=await requireActor(req,{roles:editors,scope:'documents:write'}),id=idFrom(req.params);const b=z.object({values:z.record(z.string(),z.unknown()),expectedRevision:z.string().max(100).optional()}).parse(req.body);return withWorkspace(a.workspaceId,async c=>{await c.query('select d.id from documents d join extraction_runs r on r.document_id=d.id where r.id=$1 for update of d',[id]);await c.query('select id from extraction_runs where id=$1 for update',[id]);const run=await resolveRun(c,id);if(b.expectedRevision&&b.expectedRevision!==run.effectiveRevision)badRequest('This result changed. Reload before saving your correction.',409);const allowed=new Set(run.schema.fields.map((f:any)=>f.key));if(Object.keys(b.values).some(k=>!allowed.has(k)))badRequest('Corrections contain a field outside this schema');const {rows:[correction]}=await c.query('insert into corrections(workspace_id,run_id,user_id,values) values($1,$2,$3,$4) returning *',[a.workspaceId,id,a.userId,JSON.stringify(b.values)]);await c.query("update documents set status=case when latest_run_id=$2 then 'needs_review' else status end,approved_run_id=case when approved_run_id=$2 then null else approved_run_id end,updated_at=now() where id=$1",[run.document_id,id]);await audit(c,a.workspaceId,a.userId,'run.corrected',id,{correctionId:correction.id});return {correction:camel(correction),run:publicRun(await resolveRun(c,id)),issues:validateValues(b.values,run.schema)};});});
app.post('/api/runs/:id/approve',async req=>{const a=await requireActor(req,{roles:editors,scope:'documents:write'}),id=idFrom(req.params);const b=z.object({expectedRevision:z.string().max(100).optional()}).parse(req.body||{});return withWorkspace(a.workspaceId,async c=>{await c.query('select d.id from documents d join extraction_runs r on r.document_id=d.id where r.id=$1 for update of d',[id]);await c.query('select id from extraction_runs where id=$1 for update',[id]);const run=await resolveRun(c,id);if(b.expectedRevision&&b.expectedRevision!==run.effectiveRevision)badRequest('This result changed. Reload before approving.',409);const issues=validateValues(run.effectiveValues,run.schema);if(issues.length)badRequest(`Resolve validation issues before approval: ${issues.map(i=>i.message).join(' ')}`,422);const {rows:[approval]}=await c.query('insert into approvals(workspace_id,run_id,correction_id,user_id,values) values($1,$2,$3,$4,$5) returning *',[a.workspaceId,id,run.corrections[0]?.id||null,a.userId,JSON.stringify(run.effectiveValues)]);await c.query("update documents set approved_run_id=$2,status=case when latest_run_id=$2 then 'processed' else status end,updated_at=now() where id=$1",[run.document_id,id]);await audit(c,a.workspaceId,a.userId,'run.approved',id,{approvalId:approval.id});return {approval:camel(approval),run:publicRun(await resolveRun(c,id))};});});
}
