import {z} from 'zod';
import {isCanonicalTimestamp,normalizeTimestamp,validTimezone} from './timestamps.js';
import {supportedSourceLocales,fieldSourceLocale,normalizationPolicy,legacyNormalizationPolicy,type NormalizationPolicy} from '../../shared/source-formats.js';
import type {SchemaField,ParserSchema,ValidationIssue} from '../../shared/types.js';
function valueRecord(value:unknown):value is Record<string,unknown>{
 if(value===null||typeof value!=='object'||Array.isArray(value))return false;
 const prototype=Object.getPrototypeOf(value);return prototype===Object.prototype||prototype===null;
}
/** Invalid drafts may be saved, but undeclared fields are never silently approved or exported. */
export function validateValueKeys(values:Record<string,unknown>,schema:ParserSchema):ValidationIssue[]{
 const issues:ValidationIssue[]=[];
 const walk=(value:unknown,fields:SchemaField[],prefix='')=>{
  if(!valueRecord(value))return;
  const allowed=new Set(fields.map(field=>field.key));
  for(const key of Object.keys(value))if(!allowed.has(key))issues.push({field:prefix+key,code:'unknown_field',message:'The result contains a field outside this schema.'});
  for(const field of fields){
   if(!Object.hasOwn(value,field.key))continue;
   const child=value[field.key],key=prefix+field.key;
   if(field.type==='object')walk(child,field.fields||[],`${key}.`);
   if(field.type==='array'&&Array.isArray(child))child.forEach((row,index)=>walk(row,field.fields||[],`${key}[${index}].`));
  }
 };
 walk(values,schema.fields);return issues;
}
export const fieldSchema:z.ZodType<SchemaField>=z.lazy(()=>z.object({key:z.string().regex(/^[a-zA-Z][a-zA-Z0-9_]{0,63}$/),label:z.string().min(1).max(120),type:z.enum(['string','number','currency','date','timestamp','boolean','multiline','array','object']),timezone:z.string().max(80).refine(validTimezone,'Invalid timezone').optional(),sourceLocale:z.enum(supportedSourceLocales).optional(),required:z.boolean().optional(),instructions:z.string().max(2000).optional(),default:z.unknown().optional(),transform:z.enum(['trim','uppercase','lowercase']).optional(),anchor:z.string().max(200).optional(),enum:z.array(z.string().max(500)).min(1).max(100).optional(),fields:z.array(fieldSchema).max(30).optional()}).superRefine((field,ctx)=>{if(field.sourceLocale!==undefined&&!['date','timestamp','number','currency'].includes(field.type))ctx.addIssue({code:'custom',path:['sourceLocale'],message:'Source format applies to date, timestamp, number and currency fields only.'});}));
export const parserSchema=z.object({fields:z.array(fieldSchema).min(1).max(60)}).superRefine((s,ctx)=>{const check=(fields:SchemaField[],depth:number)=>{if(depth>4)ctx.addIssue({code:'custom',message:'Schema nesting is limited to four levels'});const keys=new Set<string>();for(const f of fields){if(keys.has(f.key))ctx.addIssue({code:'custom',message:`Duplicate field key: ${f.key}`});keys.add(f.key);if(f.timezone!==undefined&&f.type!=='timestamp')ctx.addIssue({code:'custom',message:`${f.key}: timezone applies to timestamp fields only`});if(f.enum&&!['string','multiline'].includes(f.type))ctx.addIssue({code:'custom',message:`${f.key}: allowed choices apply to text fields only`});if(['array','object'].includes(f.type)&&!f.fields?.length)ctx.addIssue({code:'custom',message:`${f.key} requires child fields`});if(f.fields&&depth<6)check(f.fields,depth+1);}};check(s.fields,1);});
export function validateValues(values:Record<string,unknown>,schema:ParserSchema,settings:{locale?:string;timezone?:string|null;version?:NormalizationPolicy}={}):ValidationIssue[]{const issues:ValidationIssue[]=validateValueKeys(values,schema);const walk=(object:Record<string,unknown>,fields:SchemaField[],prefix='')=>{for(const f of fields){const key=prefix+f.key,v=Object.hasOwn(object,f.key)?object[f.key]:undefined;if(v===null||v===undefined||v===''||Array.isArray(v)&&v.length===0){if(f.required)issues.push({field:key,code:'required',message:`${f.label} is required.`});continue;}if((f.type==='number'||f.type==='currency')&&(typeof v!=='number'||!Number.isFinite(v)))issues.push({field:key,code:'number',message:settings.version===legacyNormalizationPolicy?`${f.label} must be a finite number.`:`${f.label} must be a finite number in the saved source format${fieldSourceLocale(f,settings.locale,settings.version??normalizationPolicy)?` (${fieldSourceLocale(f,settings.locale,settings.version??normalizationPolicy)})`:''}. Review punctuation or enter a numeric correction.`});if(f.enum&&typeof v==='string'&&!f.enum.includes(v))issues.push({field:key,code:'allowed_choice',message:`${f.label} must be one of: ${f.enum.join(', ')}.`});if(f.type==='boolean'&&typeof v!=='boolean')issues.push({field:key,code:'boolean',message:`${f.label} must be true or false.`});if(['string','multiline','date'].includes(f.type)&&typeof v!=='string')issues.push({field:key,code:'text',message:`${f.label} must be text.`});if(f.type==='date'&&(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||settings.version===normalizationPolicy&&v.startsWith('0000-')||(!Number.isFinite(new Date(v).getTime())||new Date(v).toISOString().slice(0,10)!==v)))issues.push({field:key,code:'date',message:`${f.label} must be a valid ISO date (YYYY-MM-DD).`});if(f.type==='timestamp'&&!isCanonicalTimestamp(v)){const checked=normalizeTimestamp(v,{...settings,locale:fieldSourceLocale(f,settings.locale,settings.version??normalizationPolicy),timezone:f.timezone??settings.timezone});issues.push({field:key,code:checked.issue?.code??'timestamp_not_normalized',message:`${f.label}: ${checked.issue?.message??'Save this value as a UTC timestamp before approval.'}`});}if(f.type==='array'){if(!Array.isArray(v))issues.push({field:key,code:'array',message:`${f.label} must be a table.`});else v.forEach((row,i)=>{if(!valueRecord(row))issues.push({field:`${key}[${i}]`,code:'object',message:'A table row must be an object.'});else walk(row as Record<string,unknown>,f.fields||[],`${key}[${i}].`);});}if(f.type==='object'){if(!valueRecord(v))issues.push({field:key,code:'object',message:`${f.label} must be an object.`});else walk(v as Record<string,unknown>,f.fields||[],`${key}.`);}}};walk(values,schema.fields);
const items=values.line_items;if(Array.isArray(items)&&typeof values.subtotal==='number'){const amounts=items.map(r=>(r as any)?.amount);if(amounts.every(v=>typeof v==='number')&&Math.abs(amounts.reduce((a,b)=>a+b,0)-values.subtotal)>0.011)issues.push({field:'subtotal',code:'line_total',message:'Line-item amounts do not reconcile with the subtotal.'});}if(typeof values.total==='number'&&typeof values.subtotal==='number'&&typeof values.tax==='number'&&Math.abs(values.subtotal+values.tax-values.total)>0.011)issues.push({field:'total',code:'total',message:'Subtotal plus tax does not reconcile with total.'});return issues;}
