import type {FastifyInstance} from 'fastify';
import {z} from 'zod';
import {withWorkspace,adminPool,transaction,camel,badRequest,notFound,audit} from './db.js';
import {requireActor,requireSession,admins,newToken,hashToken} from './auth.js';
import {config} from './config.js';
const idFrom=(p:unknown)=>z.object({id:z.string().uuid()}).parse(p).id;
const scopes=['documents:read','documents:write','results:read','parsers:read','parsers:write','integrations:write','exports:read'] as const;
export async function registerWorkspace(app:FastifyInstance){
app.get('/api/workspace/usage',async req=>{const a=await requireActor(req,{scope:'documents:read'});return withWorkspace(a.workspaceId,async c=>{const workspace=(await c.query('select * from workspaces where id=$1',[a.workspaceId])).rows[0];const usage=(await c.query("select coalesce(sum(pages),0)::integer pages,count(*)::integer events from usage_ledger where workspace_id=$1 and created_at>=date_trunc('month',now())",[a.workspaceId])).rows[0];const counts=(await c.query("select count(*)::integer documents,count(*) filter(where status='needs_review')::integer needs_review,count(*) filter(where status in('processed','exported'))::integer processed,count(*) filter(where status='failed')::integer failed from documents where workspace_id=$1",[a.workspaceId])).rows[0];const cost=(await c.query("select coalesce(sum(cost_usd),0) cost_usd from extraction_runs where workspace_id=$1 and created_at>=date_trunc('month',now())",[a.workspaceId])).rows[0];const ledger=(await c.query('select * from usage_ledger where workspace_id=$1 order by created_at desc limit 50',[a.workspaceId])).rows.map(camel);return {plan:workspace.plan,usage:{...camel(usage),...camel(counts),costUsd:Number(cost.cost_usd)},ledger,billingRule:'Each accepted page or spreadsheet sheet counts once on upload. Manual reprocessing counts again. Automatic worker retries and detected duplicates do not count again. DOCX/text/email count as one document page.'};});});
app.get('/api/workspace/settings',async req=>{const a=await requireActor(req);requireSession(a);const w=(await adminPool.query('select * from workspaces where id=$1',[a.workspaceId])).rows[0];return {workspace:camel(w),role:a.role,limits:{maxBytes:config.maxBytes,maxPages:config.maxPages},authentication:{provider:'local-scrypt',emailVerification:false,passwordResetEmail:false}};});
app.patch('/api/workspace/settings',async req=>{const a=await requireActor(req,{roles:admins});requireSession(a);const b=z.object({name:z.string().trim().min(1).max(100).optional(),retentionDays:z.number().int().min(1).max(3650).optional(),notifications:z.boolean().optional()}).parse(req.body);const w=await transaction(adminPool,async c=>{const old=(await c.query('select * from workspaces where id=$1 for update',[a.workspaceId])).rows[0];const settings={...old.settings,...(b.retentionDays===undefined?{}:{retentionDays:b.retentionDays}),...(b.notifications===undefined?{}:{notifications:b.notifications})};return (await c.query('update workspaces set name=$2,settings=$3 where id=$1 returning *',[a.workspaceId,b.name||old.name,JSON.stringify(settings)])).rows[0];});await withWorkspace(a.workspaceId,c=>audit(c,a.workspaceId,a.userId,'workspace.settings_updated',a.workspaceId,b));return {workspace:camel(w)};});
app.get('/api/workspace/members',async req=>{const a=await requireActor(req);requireSession(a);const members=(await adminPool.query('select u.id,u.name,u.email,m.role,m.created_at from memberships m join users u on u.id=m.user_id where m.workspace_id=$1 order by m.created_at',[a.workspaceId])).rows.map(camel);const invitations=admins.includes(a.role)?await withWorkspace(a.workspaceId,async c=>(await c.query('select id,email,role,expires_at,accepted_at,created_at from invitations where workspace_id=$1 order by created_at desc',[a.workspaceId])).rows.map(camel)):[];return {members,invitations};});
app.post('/api/workspace/members',async req=>{const a=await requireActor(req,{roles:admins});requireSession(a);const b=z.object({email:z.string().email().transform(s=>s.toLowerCase().trim()),role:z.enum(['admin','editor','viewer'])}).parse(req.body);if(a.role==='admin'&&b.role==='admin')badRequest('Only the workspace owner can appoint an admin',403);const token=newToken();return withWorkspace(a.workspaceId,async c=>{const {rows:[inv]}=await c.query("insert into invitations(workspace_id,email,role,token_hash,expires_at) values($1,$2,$3,$4,now()+interval '7 days') returning id,email,role,expires_at",[a.workspaceId,b.email,b.role,hashToken(token)]);await audit(c,a.workspaceId,a.userId,'member.invited',inv.id,{role:b.role});return {invitation:camel(inv),inviteUrl:`${config.origin}/app/invite?token=${token}`,token,delivery:'manual',message:'Copy the invitation link. Email delivery is not configured.'};});});
app.post('/api/workspace/invitations/accept',async req=>{const a=await requireActor(req);requireSession(a);const b=z.object({token:z.string().min(20).max(200)}).parse(req.body);return transaction(adminPool,async c=>{const invite=(await c.query('select * from invitations where token_hash=$1 and expires_at>now() and accepted_at is null for update',[hashToken(b.token)])).rows[0];if(!invite)badRequest('This invitation is invalid, expired or already used');const user=(await c.query('select email from users where id=$1',[a.userId])).rows[0];if(user.email!==invite.email)badRequest('Sign in with the email address this invitation was sent to',403);const existing=(await c.query('select role from memberships where workspace_id=$1 and user_id=$2 for update',[invite.workspace_id,a.userId])).rows[0];if(!existing)await c.query('insert into memberships(workspace_id,user_id,role) values($1,$2,$3)',[invite.workspace_id,a.userId,invite.role]);await c.query('update invitations set accepted_at=now() where id=$1',[invite.id]);const role=existing?.role||invite.role;await audit(c,invite.workspace_id,a.userId,'member.invitation_accepted',invite.id,{memberId:a.userId,role,membershipCreated:!existing});return {workspaceId:invite.workspace_id,role};});});
app.patch('/api/workspace/members/:id',async req=>{const a=await requireActor(req,{roles:admins});requireSession(a);const id=idFrom(req.params);const b=z.object({role:z.enum(['admin','editor','viewer'])}).parse(req.body);if(a.role!=='owner')badRequest('Only the workspace owner can change roles',403);return transaction(adminPool,async c=>{const current=(await c.query('select role from memberships where workspace_id=$1 and user_id=$2 for update',[a.workspaceId,id])).rows[0];if(!current)notFound();if(current.role==='owner')badRequest('The workspace owner role cannot be changed here');if(current.role!==b.role){await c.query('update memberships set role=$3 where workspace_id=$1 and user_id=$2',[a.workspaceId,id,b.role]);await audit(c,a.workspaceId,a.userId,'member.role_changed',id,{previousRole:current.role,role:b.role});}return {ok:true};});});
app.delete('/api/workspace/members/:id',async req=>{const a=await requireActor(req,{roles:admins});requireSession(a);const id=idFrom(req.params);await transaction(adminPool,async c=>{const member=(await c.query('select role from memberships where workspace_id=$1 and user_id=$2 for update',[a.workspaceId,id])).rows[0];if(!member)notFound();if(member.role==='owner'||member.role==='admin'&&a.role!=='owner')badRequest('This member cannot be removed by your role',403);await c.query('delete from memberships where workspace_id=$1 and user_id=$2',[a.workspaceId,id]);await c.query('update api_keys set revoked_at=now() where workspace_id=$1 and user_id=$2',[a.workspaceId,id]);await c.query('delete from sessions where workspace_id=$1 and user_id=$2',[a.workspaceId,id]);await audit(c,a.workspaceId,a.userId,'member.removed',id,{role:member.role});});return {ok:true};});
app.delete('/api/workspace/invitations/:id',async req=>{const a=await requireActor(req,{roles:admins});requireSession(a);return withWorkspace(a.workspaceId,async c=>{const invitation=(await c.query('delete from invitations where id=$1 returning id,role,accepted_at',[idFrom(req.params)])).rows[0];if(!invitation)notFound();await audit(c,a.workspaceId,a.userId,invitation.accepted_at?'member.invitation_deleted':'member.invitation_revoked',invitation.id,{role:invitation.role});return {ok:true};});});
app.get('/api/workspace/api-keys',async req=>{const a=await requireActor(req,{roles:admins});requireSession(a);return withWorkspace(a.workspaceId,async c=>({apiKeys:(await c.query('select id,name,prefix,scopes,created_at,last_used_at,revoked_at from api_keys where workspace_id=$1 order by created_at desc',[a.workspaceId])).rows.map(camel),scopes}));});
app.post('/api/workspace/api-keys',async req=>{const a=await requireActor(req,{roles:admins});requireSession(a);const b=z.object({name:z.string().trim().min(1).max(100),scopes:z.array(z.enum(scopes)).min(1)}).parse(req.body);const token=`fl_${newToken()}`;return withWorkspace(a.workspaceId,async c=>{const {rows:[key]}=await c.query('insert into api_keys(workspace_id,user_id,name,prefix,token_hash,scopes) values($1,$2,$3,$4,$5,$6) returning id,name,prefix,scopes,created_at',[a.workspaceId,a.userId,b.name,token.slice(0,10),hashToken(token),JSON.stringify([...new Set(b.scopes)])]);await audit(c,a.workspaceId,a.userId,'api_key.created',key.id,{scopes:b.scopes});return {apiKey:camel(key),token,message:'Copy this key now. It will not be displayed again.'};});});
app.delete('/api/workspace/api-keys/:id',async req=>{const a=await requireActor(req,{roles:admins});requireSession(a);return withWorkspace(a.workspaceId,async c=>{const id=idFrom(req.params);if(!(await c.query('update api_keys set revoked_at=now() where id=$1 returning id',[id])).rowCount)notFound();await audit(c,a.workspaceId,a.userId,'api_key.revoked',id);return {ok:true};});});
app.get('/api/workspace/storage-deletions',async req=>{const a=await requireActor(req,{roles:admins});requireSession(a);return withWorkspace(a.workspaceId,async c=>({deletions:(await c.query('select id,status,attempts,last_error,available_at,created_at from file_deletions where workspace_id=$1 order by created_at desc',[a.workspaceId])).rows.map(camel)}));});
app.post('/api/workspace/storage-deletions/:id/retry',async req=>{const a=await requireActor(req,{roles:admins});requireSession(a);return withWorkspace(a.workspaceId,async c=>{if(!(await c.query("update file_deletions set status='pending',attempts=0,available_at=now(),last_error=null where id=$1 returning id",[idFrom(req.params)])).rowCount)notFound();return {ok:true};});});
app.get('/api/workspace/audit',async req=>{const a=await requireActor(req,{roles:admins});requireSession(a);return withWorkspace(a.workspaceId,async c=>({events:(await c.query('select * from audit_events where workspace_id=$1 order by created_at desc limit 100',[a.workspaceId])).rows.map(camel)}));});
}
