import {useEffect,useRef,useState} from 'react';
import {NavLink,Outlet,Link,Navigate,useLocation,useNavigate} from 'react-router-dom';
import {FileText,Layers3,Puzzle,ChartNoAxesColumn,Settings,HelpCircle,LogOut,Menu,X,Plus} from 'lucide-react';
import {useSession} from '../lib/session';
import {Button,Loading,Modal,Field,Notice} from './ui';
import {post,useAction} from '../lib/api';
import ProcessingNotifications from './ProcessingNotifications';
const links=[['/app','Documents',FileText],['/app/parsers','Parsers',Layers3],['/app/integrations','Integrations',Puzzle],['/app/usage','Usage',ChartNoAxesColumn],['/app/settings','Settings',Settings]] as const;
export default function AppShell(){
  const session=useSession(),location=useLocation(),navigate=useNavigate();
  const [menu,setMenu]=useState(false),[mobile,setMobile]=useState(()=>window.matchMedia('(max-width:1000px)').matches),[newWorkspace,setNewWorkspace]=useState(false),[name,setName]=useState('');
  const menuTrigger=useRef<HTMLButtonElement>(null),menuClose=useRef<HTMLButtonElement>(null),sidebar=useRef<HTMLElement>(null);const action=useAction();
  useEffect(()=>{const query=window.matchMedia('(max-width:1000px)');const change=()=>{setMobile(query.matches);if(!query.matches)setMenu(false);};const resize=()=>{change();setMenu(false);};query.addEventListener('change',change);window.addEventListener('resize',resize);change();return()=>{query.removeEventListener('change',change);window.removeEventListener('resize',resize);};},[]);
  useEffect(()=>{if(!menu||!mobile)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';menuClose.current?.focus();return()=>{document.body.style.overflow=previous;menuTrigger.current?.focus();};},[menu,mobile]);
  if(session.loading)return <Loading/>;if(!session.data)return <Navigate to={`/sign-in?next=${encodeURIComponent(location.pathname+location.search)}`} replace/>;
  const {user,workspace,workspaces}=session.data;const current=links.filter(([path])=>location.pathname.startsWith(path)).at(-1)?.[1]||'Documents';
  async function switchWorkspace(id:string){await action.run(async()=>{await session.select(id);setMenu(false);navigate('/app');},'');}
  return <div className="app-shell"><a className="skip-link" href="#main">Skip to content</a><aside id="workspace-navigation" ref={sidebar} className={`sidebar ${menu?'open':''}`} role={mobile&&menu?'dialog':undefined} aria-modal={mobile&&menu?true:undefined} aria-label="Workspace navigation" onKeyDown={event=>{
    if(!menu||!mobile)return;
    if(event.key==='Escape'){event.preventDefault();setMenu(false);return;}
    if(event.key!=='Tab')return;
    const focusable=Array.from(sidebar.current?.querySelectorAll<HTMLElement>('a[href],button:not(:disabled),select:not(:disabled),input:not(:disabled),[tabindex="0"]')||[]).filter(element=>element.offsetParent!==null);
    const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}
  }}><div className="sidebar-brand"><Link to="/" className="wordmark" onClick={()=>setMenu(false)}>Folio</Link><button type="button" ref={menuClose} className="icon-button mobile-only" aria-label="Close navigation" onClick={()=>setMenu(false)}><X size={20}/></button></div><label className="sr-only" htmlFor="workspace-switch">Workspace</label><select id="workspace-switch" className="workspace-switch" value={workspace.id} disabled={action.busy} onChange={event=>{if(event.target.value==='new'){setMenu(false);setNewWorkspace(true);return;}void switchWorkspace(event.target.value);}}>{workspaces.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}<option value="new">+ New workspace</option></select>{!newWorkspace&&<Notice error={action.error}/>}<nav aria-label="Workspace pages">{links.map(([path,label,Icon])=><NavLink to={path} end={path==='/app'} onClick={()=>setMenu(false)} key={path}><Icon size={21} strokeWidth={1.6}/>{label}</NavLink>)}</nav><div className="sidebar-bottom"><Link to="/help" onClick={()=>setMenu(false)}><HelpCircle size={21} strokeWidth={1.6}/>Help & documentation</Link><div className="profile"><span className="avatar">{user.name.slice(0,1).toUpperCase()}</span><div><strong>{user.name}</strong><span>{workspace.role} · Workspace</span></div><button type="button" className="icon-button" aria-label="Sign out" disabled={action.busy} onClick={()=>void action.run(()=>session.logout(),'')}><LogOut size={17}/></button></div></div></aside>{menu&&mobile&&<button type="button" tabIndex={-1} className="sidebar-backdrop" aria-label="Close navigation" onClick={()=>setMenu(false)}/>}<div className="app-body" inert={mobile&&menu}><header className="app-topbar"><div><button type="button" ref={menuTrigger} className="icon-button mobile-only" aria-label="Open navigation" aria-controls="workspace-navigation" aria-expanded={menu} onClick={()=>setMenu(true)}><Menu size={21}/></button><span className="muted">Workspace</span><span className="muted">/</span><span>{current}</span></div><div><ProcessingNotifications key={`${workspace.id}:${user.id}`} workspaceId={workspace.id} userId={user.id}/><span className="avatar small-avatar">{user.name.slice(0,1).toUpperCase()}</span></div></header><main className="app-main" id="main" key={workspace.id}><Outlet/></main></div><Modal title="Create a workspace" description="Keep another team's parsers and documents separate." open={newWorkspace} onOpenChange={open=>{setNewWorkspace(open);action.setError('');}}><form onSubmit={event=>{event.preventDefault();void action.run(async()=>{const result=await post('/api/workspaces',{name});await session.select(result.workspace.id);setNewWorkspace(false);setName('');navigate('/app');},'');}}><Field label="Workspace name"><input autoFocus required maxLength={100} value={name} onChange={event=>setName(event.target.value)}/></Field><Notice error={action.error}/><Button disabled={action.busy}><Plus/>Create workspace</Button></form></Modal></div>;
}
