import type { SchemaField } from './types.js';
const f = (key:string,label:string,type:SchemaField['type']='string', required=true):SchemaField=>({key,label,type,required,anchor:label});
export const presets: Record<string,{name:string;description:string;fields:SchemaField[];sample:string}> = {
 invoice:{name:'Invoices',description:'Supplier, totals and itemized charges',fields:[f('invoice_number','Invoice number'),f('supplier','Supplier'),f('invoice_date','Invoice date','date'),f('currency','Currency'),f('subtotal','Subtotal','currency'),f('tax','Tax','currency'),f('total','Total','currency'),{...f('line_items','Line items','array'),fields:[f('description','Description'),f('quantity','Quantity','number'),f('unit_price','Unit price','currency'),f('amount','Amount','currency')]}],sample:'SYNTHETIC SAMPLE — INVOICE\nInvoice number: INV-00127\nSupplier: Juniper Studio\nInvoice date: 2026-08-28\nCurrency: EUR\nSubtotal: 450.00\nTax: 103.50\nTotal: 553.50\nLine items:\nDescription | Quantity | Unit price | Amount\nDesign review | 2 | 150.00 | 300.00\nDocument setup | 1 | 150.00 | 150.00'},
 purchase_order:{name:'Purchase orders',description:'Order references, buyers and line items',fields:[f('order_number','Order number'),f('supplier','Supplier'),f('buyer','Buyer'),f('order_date','Order date','date'),f('currency','Currency'),f('total','Total','currency'),{...f('line_items','Line items','array'),fields:[f('description','Description'),f('quantity','Quantity','number'),f('unit_price','Unit price','currency'),f('amount','Amount','currency')]}],sample:'SYNTHETIC SAMPLE — PURCHASE ORDER\nOrder number: PO-00842\nSupplier: Paper & Pine\nBuyer: Acorn Projects\nOrder date: 2026-09-02\nCurrency: EUR\nTotal: 480.00\nLine items:\nDescription | Quantity | Unit price | Amount\nRecycled notebooks | 40 | 8.00 | 320.00\nDesk folders | 20 | 8.00 | 160.00'},
 receipt:{name:'Receipts',description:'Merchant, date and total spent',fields:[f('merchant','Merchant'),f('date','Date','date'),f('currency','Currency'),f('total','Total','currency')],sample:'SYNTHETIC SAMPLE — RECEIPT\nMerchant: Willow Coffee\nDate: 2026-09-03\nCurrency: EUR\nTotal: 12.80'},
 leads:{name:'Lead emails',description:'Contact details from inbound enquiries',fields:[f('name','Name'),f('email','Email'),f('company','Company'),f('message','Message','multiline',false)],sample:'SYNTHETIC SAMPLE — LEAD EMAIL\nName: Alex Morgan\nEmail: alex@example.com\nCompany: Meadow Works\nMessage: Please send details about document processing.'},
 custom:{name:'Custom parser',description:'Define the fields your workflow needs',fields:[f('reference','Reference')],sample:'SYNTHETIC SAMPLE — CUSTOM DOCUMENT\nReference: DOC-00017'}
};
