import fs from 'node:fs/promises';
import path from 'node:path';
import {generateFixtures} from './fixtures.js';
import {inspectSource} from '../server/core/source.js';
import {extractRules,rulesEngine} from '../server/core/extraction.js';
import {presets} from '../shared/presets.js';
function flatten(value:unknown,prefix=''):Record<string,unknown>{if(Array.isArray(value)){if(!value.length)return {[prefix]:[]};return Object.assign({},...value.map((v,i)=>flatten(v,`${prefix}[${i}]`)));}if(value&&typeof value==='object')return Object.assign({},...Object.entries(value).map(([k,v])=>flatten(v,prefix?`${prefix}.${k}`:k)));return {[prefix]:value};}
const {folder,manifest}=await generateFixtures();const results:any[]=[];let expectedFields=0,correctFields=0,supportedFields=0,supportedCorrect=0;
for(const f of manifest){try{const source=await inspectSource(await fs.readFile(path.join(folder,f.filename)),f.filename);if(f.pageCount&&source.pageCount!==f.pageCount)throw new Error('Unexpected page count');if(!source.pages.some(p=>p.text.trim())){results.push({name:f.name,category:f.category,state:'requires_provider',fieldsCorrect:0,fieldsExpected:Object.keys(flatten(f.expected)).length});continue;}const result=extractRules(source.pages,{fields:presets[f.useCase].fields},f.locale);const expected=flatten(f.expected),actual=flatten(result.normalizedValues);const mismatches=Object.entries(expected).filter(([key,value])=>JSON.stringify(actual[key])!==JSON.stringify(value)).map(([field,expected])=>({field,expected,actual:actual[field]??null}));const n=Object.keys(expected).length,correct=n-mismatches.length;expectedFields+=n;correctFields+=correct;if(f.category==='supported'){supportedFields+=n;supportedCorrect+=correct;}results.push({name:f.name,category:f.category,state:result.issues.length?'needs_review':'extracted',pages:source.pageCount,fieldsCorrect:correct,fieldsExpected:n,missingExpected:Object.values(expected).filter(v=>v===null).length,issues:result.issues,mismatches});}catch(e){results.push({name:f.name,category:f.category,state:'rejected',message:e instanceof Error?e.message:'unknown'});}}
const report={generatedAt:new Date().toISOString(),engine:`${rulesEngine.engine} / ${rulesEngine.model}`,aiProviderVerified:false,description:'Held-out synthetic native files. Includes a deliberately unsupported freeform layout, a scan and a malformed file. No customer-document or AI accuracy claim.',supported:{correct:supportedCorrect,total:supportedFields},allReadableLayouts:{correct:correctFields,total:expectedFields},results};await fs.mkdir('docs/evidence',{recursive:true});await fs.writeFile('docs/evidence/extraction-evaluation.json',JSON.stringify(report,null,2));const markdown=`# Synthetic extraction evaluation\n\nGenerated ${report.generatedAt}. Actual fixture bytes were decoded using the shipped source adapters and extracted using saved field-label rules. No AI provider was invoked.\n\nConfigured labelled layouts: **${supportedCorrect}/${supportedFields} leaf values correct**. All readable layouts including the intentionally unconfigured freeform example: **${correctFields}/${expectedFields}**. These counts include expected missing values; see per-fixture missing counts. This small synthetic set does not establish performance on customer documents.\n\n| Fixture | State | Correct / expected leaf values |\n|---|---|---|\n${results.map(r=>`| ${r.name} | ${r.state} | ${r.fieldsCorrect??'—'} / ${r.fieldsExpected??'—'} |`).join('\n')}\n\nScans require a configured OCR/AI provider. A freeform layout does not silently become a successful rule extraction; missing fields produce review issues. The malformed file is rejected. Source JSON includes every discrepancy and validation issue.\n`;await fs.writeFile('docs/EXTRACTION-EVALUATION.md',markdown);console.log(markdown);if(supportedCorrect!==supportedFields||results.some(r=>r.category==='malformed'&&r.state!=='rejected'))process.exitCode=1;
