import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {PDFDocument,StandardFonts} from 'pdf-lib';
import ExcelJS from 'exceljs';
import JSZip from 'jszip';
import sharp from 'sharp';
import type {ParserSchema} from '../shared/types.js';
import {presets} from '../shared/presets.js';
export interface EvaluationFixture {name:string;filename:string;useCase:string;locale:string;expected:Record<string,unknown>;category:'supported'|'unconfigured-layout'|'scan'|'malformed';pageCount?:number;}
const xml=(s:string)=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
export async function generateFixtures(){const folder=path.join(process.cwd(),'fixtures/generated');await fs.mkdir(folder,{recursive:true});const manifest:EvaluationFixture[]=[];
const save=async(f:EvaluationFixture,bytes:Buffer|Uint8Array|string)=>{await fs.writeFile(path.join(folder,f.filename),bytes);manifest.push(f);};
const invoiceExpected={invoice_number:'INV-00601',supplier:'Fern Office Supplies',invoice_date:'2026-07-15',currency:'EUR',subtotal:780,tax:179.4,total:959.4,line_items:[{description:'Folders',quantity:20,unit_price:9,amount:180},{description:'Notebooks',quantity:30,unit_price:10,amount:300},{description:'Desk pads',quantity:10,unit_price:15,amount:150},{description:'Pens',quantity:50,unit_price:3,amount:150}]};
const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica);
const pages=[['SYNTHETIC HELD-OUT INVOICE','Invoice number: INV-00601','Supplier: Fern Office Supplies','Invoice date: 15/07/2026','Currency: EUR','Subtotal: 780.00','Tax: 179.40','Total: 959.40','Line items:','Description | Quantity | Unit price | Amount','Folders | 20 | 9.00 | 180.00','Notebooks | 30 | 10.00 | 300.00'],['SYNTHETIC HELD-OUT INVOICE - continued','Description | Quantity | Unit price | Amount','Desk pads | 10 | 15.00 | 150.00','Pens | 50 | 3.00 | 150.00']];
for(const lines of pages){const page=pdf.addPage([595,842]);lines.forEach((line,i)=>page.drawText(line,{x:48,y:785-i*28,font,size:12}));}
await save({name:'Two-page native PDF with continuing line items',filename:'invoice-multipage.pdf',useCase:'invoice',locale:'en-IE',expected:invoiceExpected,category:'supported',pageCount:2},await pdf.save());
await save({name:'German decimal and day-first dates',filename:'invoice-de.txt',useCase:'invoice',locale:'de-DE',expected:{invoice_number:'0000307',supplier:'Linde Büro',invoice_date:'2026-08-31',currency:'EUR',subtotal:1234.5,tax:234.56,total:1469.06,line_items:[{description:'Papier',quantity:10,unit_price:123.45,amount:1234.5}]},category:'supported'},'SYNTHETIC HELD-OUT DOCUMENT\nInvoice number: 0000307\nSupplier: Linde Büro\nInvoice date: 31.08.2026\nCurrency: EUR\nSubtotal: 1.234,50\nTax: 234,56\nTotal: 1.469,06\nLine items:\nDescription | Quantity | Unit price | Amount\nPapier | 10 | 123,45 | 1.234,50');
await save({name:'Missing required data remains missing',filename:'receipt-missing.txt',useCase:'receipt',locale:'en-IE',expected:{merchant:'Hazel Books',date:null,currency:'EUR',total:null},category:'supported'},'SYNTHETIC HELD-OUT RECEIPT\nMerchant: Hazel Books\nCurrency: EUR');
await save({name:'Email text with independent contact layout',filename:'lead.eml',useCase:'leads',locale:'en-IE',expected:{name:'Taylor Quinn',email:'taylor@example.test',company:'Cedar Labs',message:'Please process our weekly requests.'},category:'supported'},'From: sender@example.test\r\nTo: intake@example.test\r\nSubject: Synthetic lead\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=utf-8\r\n\r\nName: Taylor Quinn\r\nEmail: taylor@example.test\r\nCompany: Cedar Labs\r\nMessage: Please process our weekly requests.');
await save({name:'CSV with labelled rows and quoted values',filename:'receipt.csv',useCase:'receipt',locale:'en-US',expected:{merchant:'Maple, Supplies',date:'2026-08-19',currency:'USD',total:39.95},category:'supported'},'Merchant,Date,Currency,Total\n"Maple, Supplies",08/19/2026,USD,39.95');
const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('Receipt');ws.addRow(['Merchant','Date','Currency','Total']);ws.addRow(['Ash Workshop','2026-08-21','EUR',75.2]);await save({name:'XLSX labelled receipt',filename:'receipt.xlsx',useCase:'receipt',locale:'en-IE',expected:{merchant:'Ash Workshop',date:'2026-08-21',currency:'EUR',total:75.2},category:'supported'},Buffer.from(await wb.xlsx.writeBuffer()));
const zip=new JSZip();zip.file('[Content_Types].xml','<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>');zip.file('_rels/.rels','<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');zip.file('word/document.xml',`<?xml version="1.0"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${['Merchant: Rowan Kitchen','Date: 2026-08-23','Currency: GBP','Total: 21.40'].map(s=>`<w:p><w:r><w:t>${xml(s)}</w:t></w:r></w:p>`).join('')}</w:body></w:document>`);await save({name:'DOCX labelled receipt',filename:'receipt.docx',useCase:'receipt',locale:'en-IE',expected:{merchant:'Rowan Kitchen',date:'2026-08-23',currency:'GBP',total:21.4},category:'supported'},await zip.generateAsync({type:'nodebuffer'}));
await save({name:'Unconfigured freeform layout',filename:'freeform-receipt.txt',useCase:'receipt',locale:'en-IE',expected:{merchant:'Oak Market',date:'2026-08-24',currency:'EUR',total:16.9},category:'unconfigured-layout'},'SYNTHETIC HELD-OUT RECEIPT\nOAK MARKET\n24 August 2026\nPaid EUR 16.90');
const scan=await sharp(Buffer.from('<svg width="800" height="600" xmlns="http://www.w3.org/2000/svg"><rect width="800" height="600" fill="white"/><g font-family="sans-serif" font-size="28" fill="black"><text x="60" y="100">SYNTHETIC SCAN</text><text x="60" y="160">Merchant: Birch Bakery</text><text x="60" y="210">Date: 2026-08-25</text><text x="60" y="260">Currency: EUR</text><text x="60" y="310">Total: 18.60</text></g></svg>')).png().toBuffer();await save({name:'Image scan requires provider',filename:'receipt-scan.png',useCase:'receipt',locale:'en-IE',expected:{merchant:'Birch Bakery',date:'2026-08-25',currency:'EUR',total:18.6},category:'scan'},scan);
await save({name:'Malformed PDF rejection',filename:'malformed.pdf',useCase:'receipt',locale:'en-IE',expected:{},category:'malformed'},'This is a deliberately invalid synthetic PDF fixture.');
await fs.writeFile(path.join(folder,'manifest.json'),JSON.stringify({synthetic:true,seed:'folio-heldout-v1',fixtures:manifest},null,2));return {folder,manifest};}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const {manifest}=await generateFixtures();console.log(`Generated ${manifest.length} synthetic held-out fixtures under fixtures/generated.`);}
