import {useLayoutEffect,useMemo,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {useQueryClient} from '@tanstack/react-query';
import {Button,Field,Notice,Tabs,Status} from '../../components/ui';
import {useData} from '../../lib/api';
import {useSession} from '../../lib/session';
import {templateFieldOptions,templateLimits,templateReasonLabels} from '../../../shared/template-selection';
import {canonicalTemplateDefinition,type SavedTemplate,type TemplateDefinition,type TemplateMutationResult} from '../../../shared/template-definitions';
import {findPdfRegionAnchor,matchPdfRegion,pdfRegionRuleSchema,pdfRegionReasonLabels,type PdfRegionRule,type PdfRegionRect} from '../../../shared/pdf-regions';
import type {ParserSchema} from '../../../shared/types';
import {readTemplateMutation,saveTemplateMutation,clearTemplateMutation,findTemplateMutation,closeTemplateMutation,submitTemplateMutation,loadNativeTemplateSource,previewNativeTemplate,nativeDefinitionDigest,type NativeTemplateScope,type PendingTemplateMutation,type NativeTemplatePreview} from '../../lib/native-template';
import NativePdfRegionCanvas from './NativePdfRegionCanvas';
import './native-template-editor.css';

type Schema=ParserSchema&{id?:string};
type Props={parserId:string;schema:Schema;templates:SavedTemplate[];canEdit:boolean;active:boolean;totalTemplates:number};
type RegionDefinition=Extract<TemplateDefinition,{kind:'native-pdf-region-v1'}>;
type DraftRule=PdfRegionRule&{rowId:number};
const emptyDefinition=():RegionDefinition=>({kind:'native-pdf-region-v1',name:'',matchText:'',enabled:true,rules:[]});
function SavedNativeDefinition({template}:{template:SavedTemplate}){const canonical=canonicalTemplateDefinition(template),[record,setRecord]=useState<{canonical:string;digest:string}|null>(null);useLayoutEffect(()=>{let disposed=false;void nativeDefinitionDigest(template).then(digest=>{if(!disposed)setRecord({canonical,digest});}).catch(()=>{});return()=>{disposed=true;};},[canonical]);return <details className="native-saved-definition"><summary>Inspect saved native definition</summary><p>Template ID: {template.id} · Revision {template.revision}</p><p>Definition digest: {record?.canonical===canonical?record.digest:'Checking definition digest…'}</p><pre>{JSON.stringify(template,null,2)}</pre><p className="small muted">Saved anchors and regions remain inspectable without the original authoring sample.</p></details>;}
export default function NativeTemplateEditor(props:Props){const session=useSession();if(!session.data)return null;return <NativeTemplateFlow key={`${session.data.user.id}:${session.data.workspace.id}:${props.parserId}:${session.data.workspace.role}`} {...props} scope={{userId:session.data.user.id,workspaceId:session.data.workspace.id,parserId:props.parserId}}/>;}
function NativeTemplateFlow({parserId,schema,templates,canEdit,active,totalTemplates,scope}:Props&{scope:NativeTemplateScope}){
 const client=useQueryClient(),[definition,setDefinition]=useState<RegionDefinition>(emptyDefinition),[rows,setRows]=useState<DraftRule[]>([]),[selected,setSelected]=useState<number|null>(null),nextRow=useRef(1);
 const [templateId,setTemplateId]=useState<string|null>(null),[baseRevision,setBaseRevision]=useState<number|null>(null),[schemaId,setSchemaId]=useState(schema.id||''),[baseline,setBaseline]=useState(canonicalTemplateDefinition(emptyDefinition()));
 const [documentPage,setDocumentPage]=useState(1),[documentId,setDocumentId]=useState(''),[source,setSource]=useState<Awaited<ReturnType<typeof loadNativeTemplateSource>>|null>(null),[page,setPage]=useState(1),[tab,setTab]=useState('Fields');
 const [preview,setPreview]=useState<NativeTemplatePreview|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState('');
 const [pending,setPending]=useState<PendingTemplateMutation|null>(()=>readTemplateMutation(scope)),[outcome,setOutcome]=useState<TemplateMutationResult|null>(null),[confirmClose,setConfirmClose]=useState(false),[confirmReset,setConfirmReset]=useState<SavedTemplate|'new'|null>(null),[confirmDelete,setConfirmDelete]=useState<SavedTemplate|null>(null),[confirmVersion,setConfirmVersion]=useState(false);
 const [pendingSource,setPendingSource]=useState<string|null>(null),[coordinateDraft,setCoordinateDraft]=useState<{x:string;y:string;width:string;height:string}|null>(null);
 const operation=useRef(new AbortController()),generation=useRef(0),mounted=useRef(false),running=useRef(false),callbacks=useRef({active}),body=useRef<TemplateDefinition|null>(null),adoptSave=useRef(false),focusField=useRef(false),fieldSelect=useRef<HTMLSelectElement>(null),feedback=useRef<HTMLDivElement>(null),addButton=useRef<HTMLButtonElement>(null),chosenDocuments=useRef(new Map<string,{id:string;sha256:string;name:string}>());
 const documents=useData<{documents:{id:string;name:string;mimeType:string;sha256:string}[];total:number}>(`/api/parsers/${parserId}/documents?page=${documentPage}&pageSize=20`);
 const fields=templateFieldOptions(schema).filter(field=>field.kind==='scalar'),selectedRule=rows.find(row=>row.rowId===selected),sourcePage=source?.geometry.pages.find(value=>value.page===page);
 const draft:RegionDefinition={...definition,rules:rows.map(({rowId:_,...rule})=>rule)},dirty=canonicalTemplateDefinition(draft)!==baseline;
 const currentTemplate=templates.find(value=>value.id===templateId),staleSchema=Boolean(schema.id&&schemaId!==schema.id),staleTemplate=Boolean(templateId&&(currentTemplate?.revision!==baseRevision));
 const locked=!active||!canEdit||Boolean(pending)||busy==='save'||busy==='close',unsupported=rows.some(rule=>!fields.some(field=>field.path===rule.field)),duplicate=new Set(rows.map(rule=>rule.field)).size!==rows.length;
 let validDefinition:RegionDefinition|null=null,validation='';try{if(!draft.name.trim())throw new Error('Enter a template name.');if(!rows.length)throw new Error('Add at least one scalar field region.');if(unsupported)throw new Error('A saved field is missing or unsupported. Remove it explicitly or restore that field before saving.');if(duplicate)throw new Error('Use each scalar field only once.');validDefinition={...draft,name:draft.name.trim(),rules:rows.map(rule=>pdfRegionRuleSchema.parse(({field:rule.field,anchor:rule.anchor,page:rule.page,reference:rule.reference,offset:rule.offset})))};}catch(cause){validation=cause instanceof Error&&!('issues'in cause)?cause.message:'Each field needs an anchor, source page and valid value region.';}
 const anchorMatch=useMemo(()=>sourcePage&&selectedRule&&sourcePage.page===selectedRule.page?findPdfRegionAnchor(sourcePage,selectedRule.anchor):null,[sourcePage,selectedRule]),anchor=anchorMatch?.matched?anchorMatch.anchor:null;
 const match=useMemo(()=>{if(!source||!selectedRule)return null;const {rowId:_,...rule}=selectedRule;return matchPdfRegion(source.geometry,rule);},[source,selectedRule]);
 const rectangle=anchor&&selectedRule?{x:anchor.rect.x+selectedRule.offset.x,y:anchor.rect.y+selectedRule.offset.y,width:selectedRule.offset.width,height:selectedRule.offset.height}:null;
 useLayoutEffect(()=>{callbacks.current={active};});
 useLayoutEffect(()=>{mounted.current=true;return()=>{mounted.current=false;generation.current++;operation.current.abort();};},[]);
 useLayoutEffect(()=>{generation.current++;operation.current.abort();operation.current=new AbortController();running.current=false;setBusy('');if(active&&pending)void checkSaved(pending);},[active]);
 useLayoutEffect(()=>{if(focusField.current){focusField.current=false;fieldSelect.current?.focus();}},[selected]);
 useLayoutEffect(()=>{if(error)feedback.current?.scrollIntoView({block:'nearest'});},[error]);
 function cancelWork(){generation.current++;operation.current.abort();operation.current=new AbortController();running.current=false;setBusy('');setPreview(null);setError('');setNotice('');}
 function edit(action:()=>void){if(locked)return;cancelWork();setOutcome(null);action();}
 async function perform(label:string,task:(current:()=>boolean,signal:AbortSignal)=>Promise<void>){if(running.current||!active)return;const version=++generation.current;operation.current.abort();operation.current=new AbortController();const signal=operation.current.signal,current=()=>mounted.current&&callbacks.current.active&&generation.current===version&&!signal.aborted;running.current=true;setBusy(label);setError('');try{await task(current,signal);}catch(cause){if(current())setError(cause instanceof Error?cause.message:'The template request could not be completed.');}finally{if(current()){running.current=false;setBusy('');}}}
 function resolved(value:PendingTemplateMutation,result:TemplateMutationResult){
  clearTemplateMutation(value);setPending(null);body.current=null;setConfirmClose(false);
  if(adoptSave.current&&result.template?.kind==='native-pdf-region-v1'&&!result.mutation.deleted&&result.mutation.currentRevision===result.mutation.acceptedRevision)loadDefinition(result.template);
  adoptSave.current=false;setOutcome(result);
  setNotice(result.mutation.state==='closed'?'This save is closed. It cannot be applied later. Your current draft is still available.':result.mutation.deleted?'That save completed, but the template is now deleted. It was not recreated.':result.mutation.currentRevision!==result.mutation.acceptedRevision?'That save completed. A newer revision now exists; load it before editing again.':'Template saved. Existing documents and runs are unchanged. Check another PDF or explicitly reprocess a document to apply it.');void client.invalidateQueries();
 }

 async function checkSaved(value=pending){if(!value)return;await perform('check',async(current,signal)=>{const result=await findTemplateMutation(value,current,signal);if(!current())return;if(result)resolved(value,result);else setNotice('The save has no confirmed result yet. Retry the same save if its draft is still here, or explicitly close this save before starting another.');});}
 function loadDefinition(value:SavedTemplate|'new'){cancelWork();setOutcome(null);setConfirmReset(null);setCoordinateDraft(null);const next=value==='new'?emptyDefinition():value as RegionDefinition;setDefinition({name:next.name,matchText:next.matchText,enabled:next.enabled,kind:'native-pdf-region-v1',rules:[]});setRows(next.rules.map(rule=>({...rule,rowId:nextRow.current++})));setSelected(null);setTemplateId(value==='new'?null:value.id);setBaseRevision(value==='new'?null:value.revision);setSchemaId(schema.id||'');setBaseline(canonicalTemplateDefinition(next));}
 function requestDefinition(value:SavedTemplate|'new'){if(pending||running.current)return;if(dirty)setConfirmReset(value);else loadDefinition(value);}
 async function loadSource(id:string){const chosen=documents.data?.documents.find(value=>value.id===id)||chosenDocuments.current.get(id);if(!chosen){cancelWork();setDocumentId('');setSource(null);return;}chosenDocuments.current.set(id,chosen);cancelWork();setDocumentId(id);setSource(null);setCoordinateDraft(null);setPendingSource(null);await perform('source',async(current,signal)=>{const value=await loadNativeTemplateSource(scope,{documentId:id,sha256:chosen.sha256},schemaId,current,signal);if(current()){setSource(value);setPage(selectedRule?.page&&selectedRule.page<=value.geometry.pageCount?selectedRule.page:1);}});}
 function updateRule(changes:Partial<PdfRegionRule>){if(!selectedRule)return;edit(()=>{setRows(value=>value.map(rule=>rule.rowId===selectedRule.rowId?{...rule,...changes}:rule));setCoordinateDraft(null);});}
 function selectRule(rule:DraftRule){if(pending||busy==='save')return;cancelWork();setSelected(rule.rowId);setPage(rule.page);setCoordinateDraft(null);setTab('Fields');}
 function setRegion(rect:PdfRegionRect){if(!anchor||!selectedRule)return;updateRule({offset:{x:rect.x-anchor.rect.x,y:rect.y-anchor.rect.y,width:rect.width,height:rect.height}});}
 async function save(def:TemplateDefinition|null=validDefinition,target:SavedTemplate|null=null,remove=false){if(pending||running.current||!canEdit)return;adoptSave.current=!target&&!remove;const id=target?.id||templateId,revision=target?.revision??baseRevision;await perform('save',async(current,signal)=>{const operationName=remove?'delete':id?'update':'create';const value:PendingTemplateMutation={version:1,...scope,requestId:crypto.randomUUID(),operation:operationName,templateId:id,baseRevision:revision,baseSchemaId:remove?null:schemaId,definitionDigest:def?await nativeDefinitionDigest(def):null};if(!current())return;saveTemplateMutation(value);body.current=def;setPending(value);setOutcome(null);const result=await submitTemplateMutation(value,def,current,signal);if(current())resolved(value,result);});}
 const coordinates=coordinateDraft||(rectangle?Object.fromEntries(Object.entries(rectangle).map(([name,value])=>[name,(value*100).toFixed(4).replace(/\.?0+$/,'')]))as {x:string;y:string;width:string;height:string}: {x:'',y:'',width:'',height:''});
 return <div className="native-template-editor">
  <header className="native-template-heading"><div><h2>Native PDF regions</h2><p>Capture scalar fields from complete searchable text blocks. A unique anchor moves the value region with its label on the same page.</p><p className="small muted">PDF native text only. No OCR, tables, changing page sizes or automatic layout scaling. Checking a draft creates no documents or page charges.</p></div></header>
  <section className="native-region-saved-list" aria-label="Saved native PDF templates">{templates.length?templates.map(template=><article className="panel" key={template.id}><div className="template-card-heading"><div><h3>{template.name}</h3><p className="small">Revision {template.revision} · {template.rules.length} field regions</p></div><Status value={template.enabled?'enabled':'disabled'}/></div><SavedNativeDefinition template={template}/>{<div className="actions"><Button type="button" variant="secondary" disabled={Boolean(pending)||Boolean(busy)} onClick={()=>requestDefinition(template)}>{canEdit?'Edit native template':'View native template'}</Button>{canEdit&&<><Button type="button" variant="ghost" disabled={Boolean(pending)||Boolean(busy)||!schema.id} onClick={()=>void save({...template,enabled:!template.enabled},template)}>{template.enabled?'Disable native template':'Enable native template'}</Button><Button type="button" variant="ghost" disabled={Boolean(pending)||Boolean(busy)} onClick={()=>setConfirmDelete(template)}>Delete native template</Button></>}</div>}</article>):<p className="small muted">No native PDF region templates are saved.</p>}</section>
  {confirmDelete&&<section className="native-save-recovery" role="group" aria-label="Confirm native template deletion"><p>Delete “{confirmDelete.name}”? Existing runs keep their saved template and source evidence.</p><div className="actions"><Button type="button" variant="danger" disabled={Boolean(pending)||Boolean(busy)} onClick={()=>{const target=confirmDelete;setConfirmDelete(null);void save(null,target,true);}}>Delete this template</Button><Button type="button" variant="secondary" onClick={()=>setConfirmDelete(null)}>Keep template</Button></div></section>}
  <div ref={feedback}><Notice error={error} message={notice}/></div>
  {pending&&<section className="native-save-recovery" aria-label="Recover template save"><h3>Check your saved request</h3><p>The same save ID is retained. New saves are blocked until this request completes or is explicitly closed.</p><div className="actions"><Button type="button" variant="secondary" disabled={Boolean(busy)} onClick={()=>void checkSaved()}>Check save result</Button>{(body.current||pending.operation==='delete')&&<Button type="button" variant="secondary" disabled={Boolean(busy)} onClick={()=>void perform('save',async(current,signal)=>{const result=await submitTemplateMutation(pending,body.current,current,signal);if(current())resolved(pending,result);})}>Retry same save</Button>}<Button type="button" variant="ghost" disabled={Boolean(busy)} onClick={()=>setConfirmClose(true)}>Close unknown save</Button></div>{confirmClose&&<><p>If this save already completed, its result will be recovered. Otherwise it will be permanently closed so a delayed request cannot apply it.</p><Button type="button" variant="secondary" disabled={Boolean(busy)} onClick={()=>void perform('close',async(current,signal)=>{const result=await closeTemplateMutation(pending,current,signal);if(current())resolved(pending,result);})}>Confirm close or recover save</Button><Button type="button" variant="ghost" onClick={()=>setConfirmClose(false)}>Keep checking</Button></>}</section>}
  {outcome?.mutation.state==='accepted'&&<p className="small">Recorded save revision {outcome.mutation.acceptedRevision}. {outcome.mutation.deleted?'The current template is deleted.':`Current revision: ${outcome.mutation.currentRevision}.`}</p>}
  {canEdit&&<>
   <div className="actions"><h3>{templateId?'Edit native template':'Create a native template'}</h3>{templateId&&<Button type="button" variant="ghost" disabled={Boolean(pending)||Boolean(busy)} onClick={()=>requestDefinition('new')}>Create another native template</Button>}<span className="native-template-dirty">{dirty?'Unsaved draft':'No unsaved changes'}</span></div>
   {confirmReset&&<section className="native-save-recovery"><p>Discard the current unsaved draft and {confirmReset==='new'?'start a new template':'load the selected saved template'}?</p><Button type="button" variant="secondary" onClick={()=>loadDefinition(confirmReset)}>Discard draft and continue</Button><Button type="button" variant="ghost" onClick={()=>setConfirmReset(null)}>Keep draft</Button></section>}
   {(staleSchema||staleTemplate)&&<section className="native-save-recovery"><p>The saved template or parser fields changed. Your draft is preserved. Resolve the current version before saving.</p>{currentTemplate&&<Button type="button" variant="secondary" disabled={Boolean(pending)} onClick={()=>requestDefinition(currentTemplate)}>Load current saved definition</Button>}<Button type="button" variant="ghost" disabled={Boolean(pending)||Boolean(templateId&&!currentTemplate)} onClick={()=>setConfirmVersion(true)}>Keep draft with current version</Button>{confirmVersion&&<><p>This keeps your draft and uses the current saved revision for your next explicit save. Review the draft before replacing that revision.</p><Button type="button" variant="secondary" onClick={()=>{setSchemaId(schema.id||'');setBaseRevision(currentTemplate?.revision||null);setConfirmVersion(false);setPreview(null);}}>Use current version for this draft</Button><Button type="button" variant="ghost" onClick={()=>setConfirmVersion(false)}>Cancel version change</Button></>}</section>}
   <fieldset disabled={locked} className="template-form-fields"><div className="form-grid"><Field label="Native template name"><input maxLength={100} value={definition.name} onChange={event=>edit(()=>setDefinition(value=>({...value,name:event.target.value})))}/></Field><Field label="Native document contains" hint="Optional exact, case-sensitive document phrase."><input maxLength={1000} value={definition.matchText} onChange={event=>edit(()=>setDefinition(value=>({...value,matchText:event.target.value})))}/></Field></div><label className="template-enabled"><input type="checkbox" checked={definition.enabled} onChange={event=>edit(()=>setDefinition(value=>({...value,enabled:event.target.checked})))}/>Enable this native template</label></fieldset>
  </>}
  <section className="native-template-source">{!canEdit&&<p className="small muted">You can inspect saved definitions and recorded run evidence. Editing access is required to preview or change native regions.</p>}<Field label="PDF sample document"><select disabled={!canEdit||Boolean(pending)||busy==='save'||!schemaId} value={documentId} onChange={event=>{const id=event.target.value;if(source&&dirty)setPendingSource(id);else void loadSource(id);}}><option value="">Choose a retained PDF</option>{documents.data?.documents.filter(value=>value.mimeType==='application/pdf').map(value=><option key={value.id} value={value.id}>{value.name}</option>)}</select></Field>{documents.error&&<Button type="button" variant="ghost" onClick={()=>void documents.refetch()}>Retry loading sample documents</Button>}{(documents.data?.total||0)>20&&<div className="actions"><Button type="button" variant="ghost" disabled={documentPage<=1||Boolean(busy)} onClick={()=>setDocumentPage(value=>value-1)}>Previous sample documents</Button><span className="small">Page {documentPage}</span><Button type="button" variant="ghost" disabled={documentPage*20>=(documents.data?.total||0)||Boolean(busy)} onClick={()=>setDocumentPage(value=>value+1)}>Next sample documents</Button></div>}{pendingSource&&<><p>Keep this draft’s relative regions and check them against another sample? The page geometry and anchors must still match.</p><Button type="button" variant="secondary" onClick={()=>void loadSource(pendingSource)}>Keep regions and load sample</Button><Button type="button" variant="ghost" onClick={()=>setPendingSource(null)}>Keep current sample</Button></>}{documentId&&!source&&busy!=='source'&&<Button type="button" variant="secondary" onClick={()=>void loadSource(documentId)}>Retry loading PDF sample</Button>}{source&&<><p className="small">{source.source.name} · {source.source.pageCount} pages · source hash verified</p><Link className="link small" to={`/app/documents/${source.source.documentId}`}>Open source for review or explicit reprocessing</Link></>}{busy==='source'&&<p role="status" className="small">Loading verified PDF and native text geometry…</p>}</section>
  {source&&<><div className="native-template-mobile-tabs"><Tabs items={['Fields','Document']} value={tab} onChange={setTab} label="Native template editor view"/></div><div className={`native-template-columns mobile-${tab.toLowerCase()}`}><section className="native-template-controls" aria-label="Native field regions">
   <Field label="Sample PDF page"><select value={page} disabled={Boolean(busy)||Boolean(pending)} onChange={event=>{cancelWork();setPage(Number(event.target.value));setSelected(null);setCoordinateDraft(null);}}>{source.geometry.pages.map(value=><option key={value.page} value={value.page}>Page {value.page}{value.reason?' — native text unavailable':''}</option>)}</select></Field>
   <ul className="native-rule-list">{rows.map(rule=><li key={rule.rowId} className={rule.rowId===selected?'selected':''}><Button type="button" variant="ghost" onClick={()=>selectRule(rule)}>{fields.find(field=>field.path===rule.field)?.label||rule.field||'Choose a field'} · page {rule.page}</Button>{canEdit&&<Button type="button" variant="ghost" aria-label={`Remove native region ${fields.find(field=>field.path===rule.field)?.label||rule.field||rule.rowId}`} disabled={locked} onClick={()=>edit(()=>{const next=rows.filter(value=>value.rowId!==rule.rowId);setRows(next);if(selected===rule.rowId)setSelected(next[0]?.rowId||null);setCoordinateDraft(null);addButton.current?.focus();})}>Remove</Button>}</li>)}</ul>
   {canEdit&&<button ref={addButton} type="button" className="button secondary" disabled={locked||rows.length>=templateLimits.rules||!fields.length||!sourcePage||Boolean(sourcePage.reason)} onClick={()=>edit(()=>{const rowId=nextRow.current++;focusField.current=true;setRows(value=>[...value,{rowId,field:fields.find(field=>!rows.some(rule=>rule.field===field.path))?.path||fields[0].path,anchor:'',page,reference:{width:sourcePage!.width,height:sourcePage!.height,rotation:sourcePage!.rotation},offset:{x:0,y:0,width:0.2,height:0.05}}]);setSelected(rowId);setCoordinateDraft(null);})}>Add field region</button>}
   {selectedRule&&<fieldset disabled={locked}><Field label="Region field"><select ref={fieldSelect} value={selectedRule.field} onChange={event=>updateRule({field:event.target.value})}>{!fields.some(field=>field.path===selectedRule.field)&&<option value={selectedRule.field}>Unsupported saved field: {selectedRule.field}</option>}{fields.map(field=><option key={field.path} value={field.path}>{field.label}</option>)}</select></Field><Field label="Region source page" hint="The anchor is checked on this fixed page."><select value={selectedRule.page} onChange={event=>{const next=source.geometry.pages.find(value=>value.page===Number(event.target.value))!;updateRule({page:next.page,reference:{width:next.width,height:next.height,rotation:next.rotation}});setPage(next.page);}}>{source.geometry.pages.map(value=><option key={value.page} value={value.page}>Page {value.page}</option>)}</select></Field><Field label="Exact anchor text" hint="Case-sensitive; spaces and line breaks count as one space. One occurrence is required on the selected page."><input value={selectedRule.anchor} maxLength={200} onChange={event=>updateRule({anchor:event.target.value})}/></Field><Field label="Select a whole anchor block"><select value="" onChange={event=>{if(event.target.value)updateRule({anchor:sourcePage?.items.find(item=>item.id===Number(event.target.value))?.text||''});}}><option value="">Choose searchable text</option>{sourcePage?.items.map(item=><option key={item.id} value={item.id}>{item.text}</option>)}</select></Field>
    {anchor?<p className="native-region-help">Matched whole anchor block: “{anchor.capturedText}”. Green is the anchor block; the dashed box is the value region.</p>:<p className="small native-region-status" role="status">{anchorMatch&&!anchorMatch.matched?pdfRegionReasonLabels[anchorMatch.reason]:'Choose an anchor on this page.'}</p>}
    <div className="native-region-coordinates">{(['x','y','width','height']as const).map(name=><Field key={name} label={`Region ${name==='x'?'left':name==='y'?'top':name} (%)`}><input type="number" step="0.01" value={coordinates[name]} onChange={event=>edit(()=>setCoordinateDraft({...coordinates,[name]:event.target.value}))}/></Field>)}</div><Button type="button" variant="secondary" disabled={!anchor||!coordinateDraft} onClick={()=>{const rect=Object.fromEntries(Object.entries(coordinates).map(([key,value])=>[key,Number(value)/100]))as unknown as PdfRegionRect;if(Object.values(coordinates).some(value=>!value.trim())||Object.values(rect).some(value=>!Number.isFinite(value))||rect.width<=0||rect.height<=0||rect.x<0||rect.y<0||rect.x+rect.width>1||rect.y+rect.height>1){setError('Enter a positive region fully inside the page.');return;}setRegion(rect);}}>Apply numeric region</Button>
    <p className="small native-region-status" role="status">{match?.matched?`Captured native text: ${match.text}`:match?pdfRegionReasonLabels[match.reason]:'Choose a value region.'}</p>
   </fieldset>}
  </section><NativePdfRegionCanvas selectionKey={`${selected}:${selectedRule?.anchor||''}:${active}:${coordinateDraft?'numeric':'applied'}`} bytes={source.bytes} geometry={source.geometry} page={page} anchor={anchor?.rect||null} region={rectangle} disabled={locked||!selectedRule||selectedRule.page!==page} onAnchor={text=>updateRule({anchor:text})} onRegion={setRegion} onError={setError}/></div></>}
  {canEdit&&<><p className="small" role="status">{coordinateDraft?'Apply or correct the numeric region before previewing or saving.':!templateId&&totalTemplates>=templateLimits.templates?'This parser has reached its saved-template limit. Delete a template before creating another.':validation||'Preview the draft to inspect complete text blocks and normalized values before saving.'}</p><div className="actions"><Button type="button" variant="secondary" disabled={Boolean(busy)||Boolean(pending)||!source||!validDefinition||Boolean(coordinateDraft)||staleSchema||staleTemplate} onClick={()=>void perform('preview',async(current,signal)=>{setPreview(null);const result=await previewNativeTemplate(scope,source!.source,schemaId,validDefinition!,current,signal);if(current())setPreview(result);})}>{busy==='preview'?'Checking draft…':'Preview unsaved draft'}</Button><Button type="button" disabled={Boolean(busy)||Boolean(pending)||!validDefinition||!schemaId||Boolean(coordinateDraft)||!templateId&&totalTemplates>=templateLimits.templates||staleSchema||staleTemplate} onClick={()=>void save()}>{busy==='save'?'Saving…':templateId?'Save native template changes':'Save native template'}</Button></div></>}
  {preview&&<section className="native-draft-result" aria-label="Unsaved native template preview"><h3>Unsaved draft preview</h3><p>{preview.selection.outcome==='template'?(preview.evaluatedWhileDisabled?'This disabled draft would be a complete match if enabled and saved.':'This draft is a complete match. AI would not be used.'):'This draft is not a complete match. Check the source and every required field.'} This check saved no extraction result and used no page credits.</p>{preview.evaluatedWhileDisabled&&<p>This template remains disabled. Previewing does not enable or save it.</p>}{preview.candidates.flatMap(candidate=>candidate.reasons.map(reason=><p className="small" key={`${candidate.name}:${reason}`}>{templateReasonLabels[reason]||pdfRegionReasonLabels[reason as keyof typeof pdfRegionReasonLabels]||'This field could not be matched. Review its anchor and value region.'}</p>))}{preview.result&&<><h4>Exact source values</h4><pre>{JSON.stringify(preview.result.rawValues,null,2)}</pre><h4>Normalized values</h4><pre>{JSON.stringify(preview.result.normalizedValues,null,2)}</pre>{preview.result.issues.map((issue,index)=><p className="small" key={index}>{issue.field}: {issue.message}</p>)}</>}</section>}
 </div>;
}
