import {useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {FileText,ReceiptText,ShoppingBag,Mail,FilePlus,ArrowRight} from 'lucide-react';
import {presets} from '../../../shared/presets';
import {Button,Field,Notice} from '../../components/ui';
import {post,useAction} from '../../lib/api';
import {useSession} from '../../lib/session';
import {useAiAvailability} from '../../lib/ai';
const icons={invoice:FileText,receipt:ReceiptText,purchase_order:ShoppingBag,leads:Mail,custom:FilePlus};
export default function Onboarding(){
  const [kind,setKind]=useState('invoice'),[name,setName]=useState('Supplier invoices'),[nameEdited,setNameEdited]=useState(false),[mode,setMode]=useState('rules');const action=useAction(),navigate=useNavigate(),ai=useAiAvailability();const canEdit=useSession().data?.workspace.role!=='viewer';
  if(!canEdit)return <div className="onboarding"><h1>Parser creation needs editor access.</h1><p>Ask a workspace owner or admin to change your role.</p><Link className="button secondary" to="/app/parsers">View parsers</Link></div>;
  return <div className="onboarding"><div className="steps"><div className="step active"><span>1</span>Create a parser</div><div className="step"><span>2</span>Add a document</div><div className="step"><span>3</span>Review & export</div></div><h1>What would you like to extract?</h1><p className="lead">Give your parser a name and choose a starting schema.</p><form onSubmit={e=>{e.preventDefault();void action.run(async()=>{const result=await post('/api/parsers',{name,useCase:kind,mode});navigate(`/app/parsers/${result.parser.id}?onboarding=1`);},'');}}><Field label="Parser name"><input required autoFocus maxLength={100} value={name} onChange={e=>{setName(e.target.value);setNameEdited(Boolean(e.target.value.trim()));}}/></Field><Field label="Extraction mode" hint={mode==='ai'?'AI mode sends document content to the configured AI provider. Review every result.':'Text-anchor rules use labels and templates in readable text. Scans and images need AI mode.'}><select value={mode} disabled={action.busy} onChange={event=>setMode(event.target.value)}><option value="rules">Text-anchor rules</option><option value="ai" disabled={ai.configured!==true}>{ai.optionLabel}</option></select></Field><fieldset style={{border:0,padding:0,margin:0}}><legend style={{fontWeight:500,marginBottom:10}}>Start with a schema</legend><div className="schema-options">{Object.entries(presets).map(([key,p])=>{const Icon=icons[key as keyof typeof icons];return <label className={`schema-option ${kind===key?'selected':''}`} key={key}><Icon size={30} strokeWidth={1.4}/><div><strong>{p.name}</strong><span>{p.description}</span></div><input type="radio" name="useCase" checked={kind===key} onChange={()=>{setKind(key);if(!nameEdited||!name.trim()){setName(p.name);setNameEdited(false);}}}/></label>})}</div></fieldset><Notice error={action.error}/><div className="onboarding-footer"><p>You can change the fields later.</p><Button disabled={action.busy||(mode==='ai'&&ai.configured!==true)}>{action.busy?'Creating parser…':'Create parser'}<ArrowRight/></Button></div></form><p className="small muted" style={{marginTop:30}}>{ai.message} <Link className="link" to="/help">How extraction works</Link></p></div>;
}
