import {useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {FileText,ReceiptText,ShoppingBag,Mail,FilePlus,ArrowRight} from 'lucide-react';
import {presets} from '../../../shared/presets';
import {Button,Field,Notice} from '../../components/ui';
import {post,useAction,useData} from '../../lib/api';
import {useSession} from '../../lib/session';
import {useAiAvailability} from '../../lib/ai';
const icons={invoice:FileText,receipt:ReceiptText,purchase_order:ShoppingBag,leads:Mail,custom:FilePlus};
export default function Onboarding(){
  const [kind,setKind]=useState('invoice'),[name,setName]=useState('Supplier invoices'),[nameEdited,setNameEdited]=useState(false),[mode,setMode]=useState('rules'),[setupMode,setSetupMode]=useState<'sample'|'preset'>('preset');const action=useAction(),navigate=useNavigate(),ai=useAiAvailability();const canEdit=useSession().data?.workspace.role!=='viewer';
  const availability=useData<{providers:{setup?:{configured:boolean}}}>('/api/presets');
  const sampleAvailable=!availability.error&&availability.data?.providers.setup?.configured===true;
  function chooseSetup(value:'sample'|'preset'){setSetupMode(value);action.setError('');if(!nameEdited)setName(value==='sample'?'My documents':presets[kind as keyof typeof presets].name);}
  if(!canEdit)return <div className="onboarding"><h1>Parser creation needs editor access.</h1><p>Ask a workspace owner or admin to change your role.</p><Link className="button secondary" to="/app/parsers">View parsers</Link></div>;
  return <div className="onboarding"><div className="steps"><div className="step active"><span>1</span>Create a parser</div><div className="step"><span>2</span>{setupMode==='sample'?'Add a sample':'Add a document'}</div><div className="step"><span>3</span>Review & export</div></div><h1>What would you like to extract?</h1><p className="lead">Start with your own sample or choose the fields yourself.</p>
    <form onSubmit={e=>{e.preventDefault();if(setupMode==='sample'&&!sampleAvailable)return;void action.run(async()=>{const result=await post('/api/parsers',setupMode==='sample'?{name,setupMode:'sample',useCase:'custom',mode:'ai'}:{name,setupMode:'preset',useCase:kind,mode});navigate(`/app/parsers/${result.parser.id}?onboarding=1${setupMode==='sample'?'&tab=setup':''}`);},'');}}>
      <fieldset className="parser-setup-choice" disabled={action.busy}><legend>How would you like to start?</legend><div className="schema-options">
        <label className={`schema-option ${setupMode==='sample'?'selected':''}`}><div><strong>Set up with a sample</strong><span>AI discovers and saves your initial fields, then extracts your first document for review.</span></div><input type="radio" name="setupMode" value="sample" checked={setupMode==='sample'} onChange={()=>chooseSetup('sample')}/></label>
        <label className={`schema-option ${setupMode==='preset'?'selected':''}`}><div><strong>Choose fields yourself</strong><span>Start with a preset or custom fields. Choose AI extraction or text-anchor rules.</span></div><input type="radio" name="setupMode" value="preset" checked={setupMode==='preset'} onChange={()=>chooseSetup('preset')}/></label>
      </div></fieldset>
      <Field label="Parser name"><input required autoFocus disabled={action.busy} maxLength={100} value={name} onChange={e=>{setName(e.target.value);setNameEdited(Boolean(e.target.value.trim()));}}/></Field>
      {setupMode==='sample'?<div className="parser-setup-disclosure"><p>Your first accepted sample is sent to the configured AI provider to discover fields and extract values. Folio saves the initial fields automatically. You can edit them afterward.</p><p>Review every result before approving or exporting. Field discovery uses no extra page credits; 10 suggestions per workspace every 24 hours.</p>{!sampleAvailable&&<p role="status">{availability.isPending?'Checking sample setup availability…':availability.error?'Sample setup availability could not be checked. Retry or choose fields yourself.':'AI sample setup is unavailable. Both field suggestions and extraction need provider setup. You can choose fields yourself.'}</p>}{availability.error&&<Button type="button" variant="secondary" onClick={()=>void availability.refetch()}>Retry availability check</Button>}</div>:<>
        <Field label="Extraction mode" hint={mode==='ai'?'AI mode sends document content to the configured AI provider. Review every result.':'Text-anchor rules use labels and templates in readable text. Scans and images need AI mode.'}><select value={mode} disabled={action.busy} onChange={event=>setMode(event.target.value)}><option value="rules">Text-anchor rules</option><option value="ai" disabled={ai.configured!==true}>{ai.optionLabel}</option></select></Field><fieldset className="parser-setup-choice" disabled={action.busy}><legend>Start with a schema</legend><div className="schema-options">{Object.entries(presets).map(([key,p])=>{const Icon=icons[key as keyof typeof icons];return <label className={`schema-option ${kind===key?'selected':''}`} key={key}><Icon size={30} strokeWidth={1.4}/><div><strong>{p.name}</strong><span>{p.description}</span></div><input type="radio" name="useCase" checked={kind===key} onChange={()=>{setKind(key);if(!nameEdited||!name.trim()){setName(p.name);setNameEdited(false);}}}/></label>})}</div></fieldset>
      </>}
      <Notice error={action.error}/><div className="onboarding-footer"><p>{setupMode==='sample'?'Next, add one representative sample.':'You can change the fields later.'}</p><Button disabled={action.busy||(setupMode==='sample'?!sampleAvailable:mode==='ai'&&ai.configured!==true)}>{action.busy?'Creating parser…':'Create parser'}<ArrowRight/></Button></div>
    </form><p className="small muted" style={{marginTop:30}}>{setupMode==='preset'?ai.message:'AI can miss or misinterpret fields. Compare extracted values with your sample.'} <Link className="link" to="/help">How extraction works</Link></p></div>;
}
