import {useState} from 'react';
import {Link,useParams,useSearchParams} from 'react-router-dom';
import {Plus,Layers3,ChevronRight,Archive,RotateCcw,Trash2} from 'lucide-react';
import {useData,useAction,post,patch,api} from '../../lib/api';
import {useSession} from '../../lib/session';
import {useAiAvailability} from '../../lib/ai';
import {PageHeader,Loading,ErrorState,Empty,Button,Notice,Tabs,Field,Status} from '../../components/ui';
import SchemaEditor from './SchemaEditor';
import Documents from '../documents/Documents';
import Upload from '../documents/Upload';
export default function Parsers(){
  const {data,isPending,error,refetch}=useData('/api/parsers');const [archived,setArchived]=useState(false);const action=useAction();const canEdit=useSession().data?.workspace.role!=='viewer';
  if(isPending)return <Loading/>;if(error)return <ErrorState error={error} retry={()=>void refetch()}/>;
  const parsers=data.parsers.filter((p:any)=>p.archived===archived);
  return <><PageHeader title="Parsers" description="A home for every kind of document.">{canEdit&&<Link className="button primary" to="/app/parsers/new"><Plus size={18}/>Create parser</Link>}</PageHeader><Tabs items={['Active','Archived']} value={archived?'Archived':'Active'} onChange={v=>setArchived(v==='Archived')}/><Notice error={action.error} message={action.message}/>{parsers.length?<div className="parser-list">{parsers.map((parser:any)=><div className="parser-row" key={parser.id}><div className="parser-icon"><Layers3 size={24} strokeWidth={1.5}/></div><Link className="parser-row-info" to={`/app/parsers/${parser.id}`}><h3>{parser.name}</h3><p>{parser.mode==='rules'?'Text-anchor rules':'AI extraction'} · {parser.locale}</p></Link><div className="parser-count"><strong>{parser.documentCount}</strong><span>documents</span></div>{parser.reviewCount>0&&<span className="status needs_review">{parser.reviewCount} to review</span>}{canEdit&&<button className="icon-button" aria-label={archived?`Restore ${parser.name}`:`Archive ${parser.name}`} onClick={()=>void action.run(()=>patch(`/api/parsers/${parser.id}`,{archived:!archived}),archived?'Parser restored.':'Parser archived.')} >{archived?<RotateCcw size={17}/>:<Archive size={17}/>}</button>}<Link to={`/app/parsers/${parser.id}`} aria-label={`Open ${parser.name}`}><ChevronRight size={20}/></Link></div>)}</div>:<Empty title={archived?'No archived parsers.':'Choose what you want to extract.'} description={archived?'Archived parsers will appear here.':'Create an invoice, receipt, purchase-order, lead-email or custom parser.'}>{!archived&&canEdit&&<Link className="button primary" to="/app/parsers/new">Create a parser</Link>}</Empty>}</>;
}
export function ParserDetail(){
  const {id}=useParams();const [params]=useSearchParams();const [tab,setTab]=useState(params.get('onboarding')?'Add a document':'Documents');const result=useData(`/api/parsers/${id}`);const canEdit=useSession().data?.workspace.role!=='viewer';
  if(result.isPending)return <Loading/>;if(result.error)return <ErrorState error={result.error} retry={()=>void result.refetch()}/>;
  const {parser,schema,templates}=result.data;const items=params.get('onboarding')?['Add a document','Documents','Fields','Templates','Settings']:['Documents','Fields','Templates','Settings'];
  return <><PageHeader title={parser.name} description="Choose what this parser extracts."><Button variant="secondary" onClick={()=>setTab('Fields')}>{canEdit?'Edit fields':'View fields'}</Button>{parser.archived&&<Status value="archived"/>}</PageHeader><Tabs items={items} value={tab} onChange={setTab}/>{tab==='Add a document'&&<div className="onboarding"><h2>Add your first document.</h2><p>Try the synthetic sample to see a complete extraction, review and export workflow.</p><Upload parserId={id} compact/></div>}{tab==='Documents'&&<Documents parserId={id} embedded/>}{tab==='Fields'&&<SchemaEditor key={schema.id} parserId={id!} schema={schema} canEdit={canEdit}/>} {tab==='Templates'&&<TemplateEditor parserId={id!} templates={templates} fields={schema.fields} canEdit={canEdit}/>} {tab==='Settings'&&<ParserSettings key={JSON.stringify(parser)} parser={parser} canEdit={canEdit}/>}</>;
}
function ParserSettings({parser,canEdit}:{parser:any;canEdit:boolean}){
  const [form,setForm]=useState({name:parser.name,mode:parser.mode,instructions:parser.instructions,locale:parser.locale,timezone:parser.timezone});const action=useAction(),ai=useAiAvailability();
  return <form className="settings-form" onSubmit={e=>{e.preventDefault();void action.run(()=>patch(`/api/parsers/${parser.id}`,form),'Parser settings saved. These apply when you next upload or reprocess a document.');}}><div className="form-grid"><Field label="Parser name"><input disabled={!canEdit} required maxLength={100} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Extraction mode" hint={ai.message}><select disabled={!canEdit} value={form.mode} onChange={e=>setForm({...form,mode:e.target.value})}><option value="rules">Text-anchor rules</option><option value="ai" disabled={ai.configured!==true}>{ai.optionLabel}</option></select></Field><Field label="Locale" hint="Sets how dates and numbers are read, including day/month order and decimal separators."><select disabled={!canEdit} value={form.locale} onChange={e=>setForm({...form,locale:e.target.value})}>{['en-IE','en-US','en-GB','de-DE','fr-FR','es-ES'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Timezone" hint="Saved with this parser. Date fields keep the written calendar date; timestamp and timezone conversion are not supported."><select disabled={!canEdit} value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})}>{['Europe/Dublin','Europe/London','Europe/Berlin','America/New_York','America/Los_Angeles','Asia/Singapore','UTC'].map(v=><option key={v}>{v}</option>)}</select></Field></div><Field label="Extraction instructions" hint="These instructions guide AI extraction. AI mode sends document content to the configured AI provider. Text-anchor rules use labels, anchors and templates instead."><textarea disabled={!canEdit} rows={4} maxLength={8000} value={form.instructions} onChange={e=>setForm({...form,instructions:e.target.value})}/></Field><Notice error={action.error} message={action.message}/><Button disabled={!canEdit||action.busy||(form.mode==='ai'&&ai.configured!==true)}>Save settings</Button></form>;
}
function TemplateEditor({parserId,templates,fields,canEdit}:{parserId:string;templates:any[];fields:any[];canEdit:boolean}){
  const [name,setName]=useState(''),[matchText,setMatchText]=useState(''),[anchors,setAnchors]=useState<Record<string,string>>({});const action=useAction();
  return <><h2>Saved text templates</h2><p>Match a document by a literal phrase, then read values from labelled anchors. The first matching enabled template is used. Blank matching text applies to all documents.</p>{templates.map(template=><div className="integration-row" key={template.id}><div className="integration-copy"><h3>{template.name}</h3><p>{template.matchText?`Contains “${template.matchText}”`:'Matches all documents'} · {template.rules.length} anchors</p></div><Button variant="secondary" disabled={!canEdit} onClick={()=>void action.run(()=>patch(`/api/templates/${template.id}`,{...template,enabled:!template.enabled}),template.enabled?'Template disabled.':'Template enabled.')}>{template.enabled?'Disable':'Enable'}</Button><button className="icon-button" disabled={!canEdit} aria-label={`Delete template ${template.name}`} onClick={()=>void action.run(()=>api(`/api/templates/${template.id}`,{method:'DELETE'}),'Template deleted.')}><Trash2 size={17}/></button></div>)}{canEdit&&<form onSubmit={e=>{e.preventDefault();void action.run(async()=>{await post(`/api/parsers/${parserId}/templates`,{name,matchText,rules:fields.filter(f=>anchors[f.key]?.trim()).map(f=>({field:f.key,anchor:anchors[f.key].trim()})),enabled:true});setName('');setMatchText('');setAnchors({});},'Template saved. Reprocess a document to apply it.');}} style={{marginTop:30,maxWidth:800}}><h3>Create a template</h3><div className="form-grid"><Field label="Template name"><input required value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Document contains"><input value={matchText} onChange={e=>setMatchText(e.target.value)} placeholder="A supplier name or unique phrase"/></Field></div><div className="form-grid">{fields.map(field=><Field key={field.key} label={`${field.label} anchor`}><input value={anchors[field.key]||''} onChange={e=>setAnchors({...anchors,[field.key]:e.target.value})} placeholder={field.anchor||field.label}/></Field>)}</div><Button disabled={action.busy}><Plus/>Save template</Button></form>}<Notice error={action.error} message={action.message}/></>;
}
