import React from 'react';
import ReactDOM from 'react-dom/client';
import {BrowserRouter} from 'react-router-dom';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {SessionProvider} from './lib/session';
import App from './App';
import {capturePasswordResetLink} from './features/auth/PasswordRecovery';
import './styles/tokens.css';
import './styles/app.css';
import './features/parsers/parser-setup.css';
import './features/parsers/template-editor.css';
import './features/parsers/copy-parser.css';
import './features/documents/pdf-split.css';
import './features/auth/auth.css';
capturePasswordResetLink();
const captureNewResetLink=()=>{if(window.location.pathname==='/reset-password'&&window.location.hash)capturePasswordResetLink();};
window.addEventListener('popstate',captureNewResetLink);
window.addEventListener('hashchange',captureNewResetLink);
const client=new QueryClient({defaultOptions:{queries:{retry:1,staleTime:5000,refetchOnWindowFocus:false}}});
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={client}><BrowserRouter><SessionProvider><App/></SessionProvider></BrowserRouter></QueryClientProvider></React.StrictMode>);
