import React from 'react';
import ReactDOM from 'react-dom/client';
import {BrowserRouter} from 'react-router-dom';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {SessionProvider} from './lib/session';
import App from './App';
import './styles/tokens.css';
import './styles/app.css';
const client=new QueryClient({defaultOptions:{queries:{retry:1,staleTime:5000,refetchOnWindowFocus:false}}});
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={client}><BrowserRouter><SessionProvider><App/></SessionProvider></BrowserRouter></QueryClientProvider></React.StrictMode>);
